### ISSUE TITLE
Removing trailing slashes adds /public/ to url

### ISSUE THREAD

**Issue by ejerskov** [nova-framework/framework#1000]
Hi

When uncommenting the "# Remove Trailing slash uncomment to activate" code, the url is formatted with /public/ in it.
That is not correct behaviour I assume.

```
# Remove Trailing slash uncomment to activate
        RewriteCond %{REQUEST_URI} (.+)/$
        RewriteRule ^ %1 [R=301,L]
```

Eg, when I enter "http://www.test.com/test/" it is transformed into "http://www.test.com/public/test".

Did I misunderstand anything or is it a bug?

**Comment by LuckyCyborg** [comment]
You talk about code present in a previous Nova version. 

Please update to latest Nova version and go back.

**Comment by ejerskov** [comment]
I was running a fairly new version, 3.59.1, but I can see the newest check-in in /public/.htaccess fixed my problem, thanks!

**Comment by geomorillo** [comment]
please always use latest version before asking here
