### ISSUE TITLE
can not connect to database

### ISSUE THREAD

**Issue by eagle-design** [nova-framework/framework#1002]
In ..\app\Config\database : 

```
Config::set('database', array(
    'fetch' => PDO::FETCH_CLASS,
    'default' => 'mysql',
    'connections' => array(
       /*sqlite...*/
        'mysql' => array(
            'driver'    => 'mysql',
            'hostname'  => 'localhost',
            'database'  => 'soundcloud',
            'username'  => 'root',
            'password'  => '',
            'prefix'    => PREFIX,
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
        ),
        /*pgsql...*/
    ),
));
```

and in system\functions.php - i need to load db in each page
```
use Database\Connection;
$db = Connnection::getInstance(); // line 48
$prefix = $db->getTablePrefix();
```
error: `<b>Fatal error</b>:  Uncaught Error: Class 'Connnection' not found in F:\xampp\htdocs\system\functions.php:48`

**Comment by LuckyCyborg** [comment]
You are denied to modify in any way the components of **system** folder.

Please find other solution for your problems.

**Comment by LuckyCyborg** [comment]
Maybe you do not like, but the **system** folder contains the true Nova Framework, and it should be modified only by the Nova's developers. Also, on Nova 4, this folder is moved in a separate Composer package.

Any customization should be done outside this Nova's System.

**Comment by eagle-design** [comment]
so what should i do ?
1. you say to don't change functions.php
2. i have my function ( and they should be in each pages)
3. where should I use db ? and how ? i went followed by docs

**Comment by LuckyCyborg** [comment]
You should use the Database as supposed by MVC design.

In fact, there is the problem, you try to use a MVC framework on a NON-MVC way.

**Comment by LuckyCyborg** [comment]
BTW, you seen there?
```php
use Database\Connection;
$db = Connnection::getInstance(); // line 48 <-- THERE!
$prefix = $db->getTablePrefix();
```
Surely, Nova does NOT contains any class called **Connnection**, so the error message is well justified.

**Comment by eagle-design** [comment]
http://novaframework.com/documentation/v3/database-api#basic-usage
i was write these codes 
i'm using it on `app\Boot\Global.php`

**Comment by LuckyCyborg** [comment]
Perfect. So, there is a typo, but how about to think five seconds? 

You ask for a `Database\Connection`, right?

**Comment by amiroperator** [comment]
He should use DB\Connection

**Comment by LuckyCyborg** [comment]
Nope. The correct code is:
```php
$db = DB::connection(); // 

$prefix = $db->getTablePrefix();
```
BUT, the result is the same as:
```php
$prefix = PREFIX;
```
Why to complicate the life?

**Comment by amiroperator** [comment]
Right, But he used old docs because of that he got an error.

**Comment by LuckyCyborg** [comment]
@Kingorgg is aware about.
