### ISSUE TITLE
lastInsertId of table

### ISSUE THREAD

**Issue by eagle-design** [nova-framework/framework#1005]
* How to get last id on Nova ? 
`$id = DB::getPdo()->lastInsertId(); ` (which table ?)
* Which  one is faster ? 
```
1. $id = DB::getPdo()->lastInsertId(); 
2. $id = DB::select("SELECT max(ID) FROM ".PREFIX."posts");
```

**Comment by LuckyCyborg** [comment]
There is no support for "last insert ID" on low level API; aka retrieving it on **Database\Connection**. 

BUT, if you are "forced" to use only the low level API, you can retrieve the ID using:
```php
$id = DB::getPdo()->lastInsertId(); 
```

In other hand, is better to use the QueryBuilder for:
```php
$id = DB::insertGetId($values);
```
