### ISSUE TITLE
please release a clean version

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1006]
dear David we don't use sample data in master version nova, we must spend many time to remove all.

**Comment by LuckyCyborg** [comment]
Dear @vahidalvandi , sadly you do not represent the majority of Nova community, and after all, the examples are being reduced to two Templates, two Controllers and several Modules. Things to remove on several minutes.

So, if you do not like them, is really very fast to remove those examples, specially for one like you, which made it several times.

**Comment by vahidalvandi** [comment]
i also download nova4 it is clean an simple , can i use it in my production version?

**Comment by LuckyCyborg** [comment]
You are kidding, right? You want to use **pre-alpha** code on production?

If you want **to test it**, you are welcome, but be warned that there is no guarantee that it even work.

**Comment by vahidalvandi** [comment]
thanks

**Comment by LuckyCyborg** [comment]
Again, to understand right: is a very bad idea to use Nova 4 right now on production sites. Because it is NOT stable.
