### ISSUE TITLE
After update on 7-75-2016 U.S. CST just blank screen

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#1016]
@daveismyname and @LuckyCyborg 
I am at version 3.61.4 just updated and nothing but blank screen all worked prior to updating.  
Prior to this last update was at comment e201908

**Comment by LuckyCyborg** [comment]
Sorry, but I cannot confirm the problem. In my installations, on up-to-date master, everything works fine.

Maybe you messed something?

**Comment by jimgwhit** [comment]
A composer update fixed it.
