### ISSUE TITLE
how i can get parameter from url

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1018]
in nova how i get parameter  in url 

site.com/?id=6

$id = filter_input(INPUT_GET,"id", FILTER_VALIDATE_INT);

**Comment by geomorillo** [comment]
Reading the docs should work https://github.com/nova-framework/framework/wiki/Input

**Comment by geomorillo** [comment]
Reading the docs should work https://github.com/nova-framework/framework/wiki/Input
