### ISSUE TITLE
how to connect multiply database

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1026]
how to connect multiply database in my sql. with username and password from other database like SaaS model

**Comment by LuckyCyborg** [comment]
**SaaS** is not for rookies, trust me!

That's really Rocket Science, you have still to learn around 50 years to arrive there.

**Comment by vahidalvandi** [comment]
answer my question . how i can connect multi database in novA

**Comment by LuckyCyborg** [comment]
http://novaframework.com/documentation/v3/database-api

**Comment by vahidalvandi** [comment]
dont have document about multi database...

**Comment by daveismyname** [comment]
use the query builder:

````
DB::connection('mysql')->table('users')->get();
````

the name from app/Config/Database.php can be set in the connection()

**Comment by vahidalvandi** [comment]
Give more explanation

**Comment by daveismyname** [comment]
that's it, with the above set which connection to use as per the connections from app\Config\Database.php

for instance:

````
'mysql' => array(
            'driver'    => 'mysql',
            'hostname'  => 'localhost',
            'database'  => 'nova',
            'username'  => 'root',
            'password'  => 'root',
            'prefix'    => PREFIX,
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
        ),
        'remote' => array(
            'driver'    => 'mysql',
            'hostname'  => 'remote ip address',
            'database'  => 'nova',
            'username'  => 'root',
            'password'  => 'root',
            'prefix'    => PREFIX,
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
        ),
````

the second connection type has a name of remote it would need a valid host setting it can then be used:

````
$users = DB::connection('remote')->table('users')->get();
````

Then the remote connection is used.

**Comment by vahidalvandi** [comment]
ok this work just in remote connection. i have multiply module like crm,cms,mlm ,.. each module have detect database , who i can run model with related database ?

**Comment by daveismyname** [comment]
by using the query builder in any php file controller, model etc

**Comment by vahidalvandi** [comment]
how i user this query in Helpers\Database like

$this->db->select("SELECT firstName, lastName FROM ".PREFIX."contacts");

or how i switch to other database?

**Comment by daveismyname** [comment]
your can't mix the old and new database it's one or the other to use helpers\database I think you can pass the name via a Database::get('name');

**Comment by vahidalvandi** [comment]
finally
Database::get('db1');
$result_db1 = $this->db->select("SELECT firstName, lastName FROM ".PREFIX."contacts");
--------
Database::get('db2');
$result_db2 = $this->db->select("SELECT firstName, lastName FROM ".PREFIX."contacts");

can work ?

**Comment by daveismyname** [comment]
$this->db will be using the connection made from core\model so that will be the default.

instead store the connection to a local property:

$db2 = Database::get('db2');

then use $db2-> for calls to use db2 you may need to experiment to get what you want.

**Comment by vahidalvandi** [comment]
i have one code and multi database , each database store data of one client , like saas model

**Comment by LuckyCyborg** [comment]
That is not SaaS, is a Epic Complication!

**Comment by vahidalvandi** [comment]
ok , very thanks

**Comment by vahidalvandi** [comment]
in vertion 2.2 



`  public static function get($group = false)
    {
        // Determining if exists or it's not empty, then use default group defined in config
        $group = !$group ? array (
            'type' => DB_TYPE,
            'host' => DB_HOST,
            'name' => DB_NAME,
            'user' => DB_USER,
            'pass' => DB_PASS
        ) : $group;

        // Group information
        $type = $group['type'];
        $host = $group['host'];
        $name = $group['name'];
        $user = $group['user'];
        $pass = $group['pass'];

        // ID for database based on the group information
        $id = "$type.$host.$name.$user.$pass";

        // Checking if the same
        if (isset(self::$instances[$id])) {
            return self::$instances[$id];
        }

        try {
            // I've run into problem where
            // SET NAMES "UTF8" not working on some hostings.
            // Specifiying charset in DSN fixes the charset problem perfectly!
            $instance = new Database("$type:host=$host;dbname=$name;charset=utf8", $user, $pass);
            $instance->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // Setting Database into $instances to avoid duplication
            self::$instances[$id] = $instance;

            return $instance;
        } catch (PDOException $e) {
            //in the event of an error record the error to ErrorLog.html
            Logger::newMessage($e);
            Logger::customErrorMsg();
        }
    }
`
but in version 3

`    public static function get($name = null)
    {
        $name = $name ?: Config::get('database.default');

        // Check if the instance is the same.
        if (isset(self::$instances[$name])) {
            return self::$instances[$name];
        }

        // Set the Database into $instances to avoid any potential duplication.
        return self::$instances[$name] = new static($name);
    }`

i need to set username,pass,databsae name manual by each call model.

how i can connect database with this method

**Comment by daveismyname** [comment]
the credentials are set in app/Config/Database.php set an array for each set with it's own name.

**Comment by vahidalvandi** [comment]
ok , dear david this static mode. how i can set username , password by parameter ? like vertion 2.2

**Comment by LuckyCyborg** [comment]
The **Database API** from Nova 3 is completely different from Database Helper from SMVC. 

Rather, I could compare the **Database API** from Nova 3 as being similar with **Laravel 4** instead.

IF you really need the strict way from SMVC for Database, and your application depend on that, I suggest you to use the last SMVC version instead of Nova.

**Comment by vahidalvandi** [comment]
what is best solution in nova 3 for my targht?

**Comment by LuckyCyborg** [comment]
Like @daveismyname said.

And please use at least the **QueryBuilder** and the **Database\Model** instead of **Helpers\Database**, which is removed on next version, Nova 4.
