### ISSUE TITLE
Pagination Presenter.php

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#1027]
@LuckyCyborg last night you changed ver 4 line 99 from
```
$content = $this->getPageSlider($adjacent);
```
to
```
$content = $this->getPageSlider();
```
Shouldn't ver 3 also be changed?
I just figured instead of me doing a PR, quicker if you do it.  

Oh, I notice in the API pagination that instead of page=2 it has offset=2 or whatever page you are on.  
Could you change ver 3 and ver 4 from saying offset to page, looks better.

**Comment by LuckyCyborg** [comment]
> Could you change ver 3 and ver 4 from saying offset to page, looks better.

Nope. The name "offset" was chosen with a reason, not being common used by developers. 

In other hand, there is a big NO-NO to use that name yourself on queries.
