### ISSUE TITLE
Name is already in use

### ISSUE THREAD

**Issue by 834rd** [nova-framework/framework#1041]
Hey Dave,

i've an problem, after download and installation with composer:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot use Symfony\Component\HttpFoundation\Cookie as Cookie because the name is already in use
```

I've set all configurations, but still not working. Same error. Should i remove this line? Better not, i think.

Sorry for my bad english.

Thank you, Kevin.

**Comment by LuckyCyborg** [comment]
Still, you do not point to the affected file and line.

**Comment by 834rd** [comment]
Sorry, you're right!

Look here, is my demo-page: http://elearning.pixelbart.de/

**Comment by LuckyCyborg** [comment]
PHP7 ?

**Comment by 834rd** [comment]
That is true, PHP7.

**Comment by LuckyCyborg** [comment]
If you hit this problem on you particular PH7 server, probably Nova will need some heave patches to work on it.

I strongly suggest you to try PHP56.

**Comment by 834rd** [comment]
Thanks! PHP5 worked!

But now i have a new error: http://php5.834rd.com

**Comment by LuckyCyborg** [comment]
I said PHP 5,6 not 5.4

**Comment by 834rd** [comment]
You're right. Sorry. Done... new error: http://php5.834rd.com/

**Comment by LuckyCyborg** [comment]
If this is on PHP 5.6, then I can say that Nova is not for your particular hosting. Basically, even will "fix" this issue, there should be made changes on almost every file. Sorry!

IF you run a VPS, please look on PHP configuration, eventually on PH  compilation options. Eventually change the operating system.

**Comment by LuckyCyborg** [comment]
BTW, please apply this: https://github.com/nova-framework/framework/pull/1042

And see if something is changes. My bet is that you will hit on another error, but let's try.

**Comment by 834rd** [comment]
Wow, working now! Thank you very much!

http://php5.834rd.com <- you can see!
