### ISSUE TITLE
Error with root  router (default router)

### ISSUE THREAD

**Issue by saclychan** [nova-framework/framework#1062]
/ => 404 error
/subpage => OK
/welcomeindex => Ok
![image](https://cloud.githubusercontent.com/assets/5512429/17541980/dd3d05aa-5eee-11e6-8113-1455fea14674.png)

![image](https://cloud.githubusercontent.com/assets/5512429/17542017/4f79ac40-5eef-11e6-92d5-d2000be2d660.png)
![image](https://cloud.githubusercontent.com/assets/5512429/17542024/603fb146-5eef-11e6-8dc7-8be1aa5f214e.png)
![image](https://cloud.githubusercontent.com/assets/5512429/17542033/6a4aa66e-5eef-11e6-9c47-199845f4c98a.png)

**Comment by daveismyname** [comment]
I'm unable to reproduce this when I try this the ending slash is removed automatically.

**Comment by saclychan** [comment]
In chrome slash automatic add in end
in firefox, ending slash is removed
![image](https://cloud.githubusercontent.com/assets/5512429/17546367/fb5dcb24-5f0b-11e6-9aed-39016024823c.png)

But i still  get error

**Comment by amyouni** [comment]
hello

I'm getting the same error. 404 on root but other routes work

Tried a fresh install on two different machines. On windows running xampp.

**Comment by LuckyCyborg** [comment]
About what Nova version you talk, Gentlemen?

IF you do not are on latest Nova version, make no sense to discuss.

**Comment by amyouni** [comment]
I'm on 3.65.1. 

Is there a later version?

**Comment by daveismyname** [comment]
yes I'm about to do a 3.65.2 release in a moment.

**Comment by LuckyCyborg** [comment]
And it is all about Routing optimizations and improvements.

I strongly recommend to upgrade to and we will discuss back.

**Comment by daveismyname** [comment]
it's now up - https://github.com/nova-framework/framework/releases/tag/v3.65.2

**Comment by LuckyCyborg** [comment]
As a side note, I ask you to show me the variable "app" from **app/Config/App.php**

**Comment by LuckyCyborg** [comment]
Yes, I managed to reproduce the issue. Confirmed.

A patch will come on short time. :smirk:

**Comment by amyouni** [comment]
thanks :)

**Comment by LuckyCyborg** [comment]
@daveismyname The issue was introduced by adjusting Routing for "prefixed empty patterns".

**Comment by daveismyname** [comment]
ah I can't have been testing against the latest version.

thanks!

**Comment by LuckyCyborg** [comment]
@daveismyname That should fix the issue: https://github.com/nova-framework/framework/pull/1064

**Comment by daveismyname** [comment]
Great, can you try this now guys https://github.com/nova-framework/framework/releases/tag/v3.65.3

**Comment by amyouni** [comment]
Nice work. Issue is fixed
Thanks
