### ISSUE TITLE
ajax call status 200 

### ISSUE THREAD

**Issue by geomorillo** [nova-framework/framework#1084]
using version 3.70.0

I have this ajax call with jquery to a **non existing** route

		$.post('myroute',function(respuesta){
			console.log(respuesta);
		})

it gives a status 200 is this on purpose? shouldn't it be 404?

On chrome console it returns
Error in exception handler: Undefined variable: meta in C:\sites\geonet\app\Templates\Morillo\default.php:14

**Comment by LuckyCyborg** [comment]
@geomorillo Well, basically, you receive the Whoops!, because you have a variable undefined in your **default.php** layout, from Morillo template.

Also, for a improved AJAX experience, one can improve the the `App::missing()` handler living on **app/Boot/Global.php**.

**Comment by geomorillo** [comment]
ok thanks
