### ISSUE TITLE
Erorr with Route

### ISSUE THREAD

**Issue by saclychan** [nova-framework/framework#1086]
My Route
![image](https://cloud.githubusercontent.com/assets/5512429/17887771/2820088e-6952-11e6-823e-07b03c18aca5.png)

/test => OK
![image](https://cloud.githubusercontent.com/assets/5512429/17887831/6dda3c28-6952-11e6-901a-c97f7a1c2b8b.png)

/test/anything1 => 404 error
![image](https://cloud.githubusercontent.com/assets/5512429/17887873/94ee54b6-6952-11e6-907a-9cd77d9f8f16.png)
I use Nova 3.70.0 fresh install visa composer

i use win 10 64 bit
XAMPP Version: 5.6.12.
I need STABLE version

**Comment by daveismyname** [comment]
replace (:any) to {name} Nova now uses named params as default to use unnamed params edit app/Config/Routing.php

**Comment by saclychan** [comment]
thank david

**Comment by LuckyCyborg** [comment]
@saclychan I strongly recommend you to use the default **Named Parameters** on Route patterns, which are net superior Design, and also are the single way available on the future **Nova 4**.

**Comment by daveismyname** [comment]
Yes good point 👍
