### ISSUE TITLE
i have error in php 7 with sourcegardan encoder

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1091]
in smvc 2.2

Date: Sep 01, 2016 18:04PM

Message: Cannot access self:: when no class scope is active

Code: 0

File: /home/httphorjin/public_html/app/Helpers/Hooks.php

Line: 107

Stack trace:

#0 /home/httphorjin/public_html/app/Helpers/Hooks.php(109): Helpers\Hooks::loadPlugins('/home/httphorji...')
#1 /home/httphorjin/public_html/app/Helpers/Hooks.php(62): Helpers\Hooks::loadPlugins('/home/httphorji...')
#2 /home/httphorjin/public_html/app/Core/routes.php(41): Helpers\Hooks::get()
#3 /home/httphorjin/public_html/index.php(81): require('/home/httphorji...')
#4 {main}

**Comment by LuckyCyborg** [comment]
I do not believe that SMVC 2.2 is still maintained, after all now we work on version 4.

Then, I will close this issue as referring to a obsolete version.

**Comment by daveismyname** [comment]
like @LuckyCyborg has said this is very old and has not been updated to work on php 7 only 3+ has been.
