### ISSUE TITLE
Call to undefined function Routing\starts_with()

### ISSUE THREAD

**Issue by amyouni** [nova-framework/framework#1097]
Hi guys

I'm getting this error when trying to login from the login page

I can see the login page but the error pops up after clicking the Login Button

Same error screen on the register page after submission, but the new user is added to the database.

I'm on 3.71.3, the default website and navigation to subfolder works. And I have imported the relevant sql scripts.

My App.php has `    'url' => 'http://localhost:8989/',`

Thanks

![error1](https://cloud.githubusercontent.com/assets/13069721/18230816/44e9951c-72c0-11e6-93bc-03449c84a38c.png)

![error2](https://cloud.githubusercontent.com/assets/13069721/18230747/e73dcc4a-72be-11e6-96fd-56a2561a9768.png)

**Comment by LuckyCyborg** [comment]
Please apply https://github.com/nova-framework/framework/pull/1098 for confirmation that the issue was fixed.

**Comment by amyouni** [comment]
line 162 should be **Str::contains** instead of Str:contains (missing one colon)
Its working now. Thanks for the quick response

**Comment by LuckyCyborg** [comment]
OK, then we can close that.
