### ISSUE TITLE
nova speed

### ISSUE THREAD

**Issue by speedwheel** [nova-framework/framework#1116]
I just installed the latest version of Nova on Nginx + php 7 both latest versions on fresh digitalocean droplet and I barely get 50 requests per second (from which half are failed requests) with ab for out of the box nova (demo content).

I have another website done with nova (older version) and there I get around 400 requests per second without any caching and it's a full blow website.

My server is fine, with hello world I get around 3000 requests per second.

Any thoughts?

    Concurrency Level:      2
    Time taken for tests:   4.674 seconds
    Complete requests:      200
    Failed requests:        149
    (Connect: 0, Receive: 0, Length: 149, Exceptions: 0)
    Keep-Alive requests:    0
    Total transferred:      799529 bytes
    HTML transferred:       682149 bytes
    Requests per second:    42.79 [#/sec] (mean)
    Time per request:       46.744 [ms] (mean)
    Time per request:       23.372 [ms] (mean, across all concurrent requests)
    Transfer rate:          167.03 [Kbytes/sec] received

**Comment by LuckyCyborg** [comment]
There is no reason of eight times performance drop from a old Nova version to latest. Check your configuration.

BTW, that "old" Nova version which version is, after all? Look on `VERSION.txt` or `system/Foundation/Application.php`.

**Comment by speedwheel** [comment]
There is no Foundation folder in system folder. But the framework dates back to april - may 2016.

Anyway I just installed now on the same server nova framework older release, out of the box settings with demo content and I get 400-500 requests/second.


    Concurrency Level:      10
    Time taken for tests:   0.417 seconds
    Complete requests:      200
    Failed requests:        0
    Keep-Alive requests:    0
Total transferred:      353000 bytes
HTML transferred:       292000 bytes
Requests per second:    479.41 [#/sec] (mean)
Time per request:       20.859 [ms] (mean)
Time per request:       2.086 [ms] (mean, across all concurrent requests)
Transfer rate:          826.32 [Kbytes/sec] received

**Comment by LuckyCyborg** [comment]
That's not a response. If you claim help and you make comparations with a different release, you should say precise.

In other hand, the latest Nova v3.73.3 is a Framework with the size and complexity of Laravel 4.2, while the initial releases of Nova 3 was just a improved SMVC, supporting the public folder as webroot.

You compare two entire different things, then I will close your issue as being not essential or useful.

**Comment by speedwheel** [comment]
Alright thanks, now I understood what happened.

**Comment by LuckyCyborg** [comment]
@speedwheel 

> I am little disappointed that it got so slow, **even though it's a micro-framework**, it's more like wordpress speed now.

There is where you are wrong on your thoughts, because the SMVC **was** a micro-framework, while **Nova v3.73.3** is a framework, similar and size, complexity and features with **Laravel 4.2**.

**Comment by speedwheel** [comment]
I understand now, I didn't know that. 

Is there any way I can still find/download the latest version of Nova when it was still an SMVC?

**Comment by daveismyname** [comment]
latest ever release of 2.2 https://github.com/nova-framework/framework/tree/2.2

**Comment by speedwheel** [comment]
I think I have a newer version than that, because mine has little more features and in the config it says:

/**
 * Optional create a constant for the name of the site.
 */
define('SITETITLE', 'Nova V3.0');

**Comment by daveismyname** [comment]
it could have been one of these early releases going back to last april https://github.com/nova-framework/framework/tags?after=v3.4.0
