### ISSUE TITLE
Dynamic Routing on nova 3.73

### ISSUE THREAD

**Issue by Oluwafemikorede** [nova-framework/framework#1134]
Hello Everyone, its been a while on this framework, I have been using the previous versions for all my projects so far and will like to move on to the new version, but I will like to know dynamic(classic) routing is done on this new version.

**Comment by daveismyname** [comment]
the classic style of routing has been removed and is no longer supported you'll need to use the standard routing style ie:

````
Route::get('somepage/edit/{id}', 'App\Controllers\SomeController@index');
````

**Comment by Oluwafemikorede** [comment]
okay, may I ask if thats for a security reason as I am already using the classic routing in my projects using the previous versions

**Comment by daveismyname** [comment]
it was to speed up the internal processing supporting 2 very different ways takes up processing time reducing simplifying them makes the code cleaner and able to run quicker and focus on it's task.

**Comment by daveismyname** [comment]
There was no security concerns with the classic way.

**Comment by Oluwafemikorede** [comment]
okay, thanks, if I am to reintroduce the classic routing to my own project on the new framework, can you give a direction on what to do or file to work on.

**Comment by daveismyname** [comment]
it's not that simple to do to be honest, I would highly recommend using the standard way also it's recommended not to touch the system directory it will make upgrading a lot harder.

I'm at a point now where I don't touch the system only @LuckyCyborg does and I document the usage.
