### ISSUE TITLE
Autoload Dependencies

### ISSUE THREAD

**Issue by Oluwafemikorede** [nova-framework/framework#1135]
Hi Everyone, i am having issues when installing the nova dependencies through composer, Here is the output of my composer

Problem 1
    - The requested package monolog/monolog ^1.19 exists as monolog/monolog[1.0.0, 1.0.0-RC1, 1.0.1, 1.0.2, 1.1.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.9.1, dev-master, 1.16.x-dev] but these are rejected by your constraint.

I searched google but couldnt get help there

**Comment by daveismyname** [comment]
I'm unable to reproduce this just downloaded the folder and down composer install everything downloaded and then I was able to run it fine.

**Comment by Oluwafemikorede** [comment]
okay, thanks, I think the issue is with my composer, I will clear my cache and install.
