### ISSUE TITLE
MIME type text/html - CSS

### ISSUE THREAD

**Issue by opessoa** [nova-framework/framework#1145]
Hi guys. 

All my templates folders, css files has get this:

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: 
"http://opessoa.info/templates/o-finance/assets/css/font-awesome.min.css".


```
If I put this files in my public folder Assets this works.

How to solve this?

**Comment by LuckyCyborg** [comment]
This is not a framework issue, but there you ask for help.

Then, be kind to go https://gitter.im/nova-framework/framework/novausers
