### ISSUE TITLE
remove demo parts

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1202]
mr david please remove demo part in module , set in clean like symfony , laravel..

i love nova and work it in version 1 , but i come back from symfony to nova because nova is very simple but i dont like , sample and demo part , i need to remove it in each project.

**Comment by LuckyCyborg** [comment]
@vahidalvandi Feel free to use the bare applications, then...
```php
composer create-project nova-framework/app foldername 3.* -s dev
```

```php
composer create-project nova-framework/app foldername 4.* -s dev
```
