### ISSUE TITLE
bug in CLI

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1205]
after run create controller add this Routes

Router::any('lists', 'App\Controllers\Lists@index');
Router::any('lists/add', 'App\Controllers\Lists@add');
Router::any('lists/edit', 'App\Controllers\Lists@edit');
Router::any('lists/view', 'App\Controllers\Lists@view');
Router::any('lists/delete', 'App\Controllers\Lists@delete');

and error Console

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Router' not found

it correct

**Route::any('lists', 'App\Controllers\Lists@index');
Route::any('lists/add', 'App\Controllers\Lists@add');
Route::any('lists/edit', 'App\Controllers\Lists@edit');
Route::any('lists/view', 'App\Controllers\Lists@view');
Route::any('lists/delete', 'App\Controllers\Lists@delete');**

**Comment by Kingorgg** [comment]
Thanks 👍 , I'll work on a fix.

**Comment by Kingorgg** [comment]
A fix has been merged, please do a `composer update`.

**Comment by LuckyCyborg** [comment]
@vahidalvandi I hope you installed the latest Nova version, because you will receive bug-fixes exactly on top of it.

Like you see, the use of latest version is not optional, but very recommended.
