### ISSUE TITLE
4.0 file_put_contents

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#1235]
@LuckyCyborg trying to navigate to a page that uses the default template, I am getting this error:

 ErrorException (E_WARNING)
file_put_contents(C:\Bitnami\wampstack-5.6.22-0\apache2\htdocs\nova40\cache\cache-0-40cd750bba9870f18aada2478b24840a.css): failed to open stream: No such file or directory  

This was after updating nova4 on 12-28-2016.  All worked perfect on 12-26-2016

**Comment by LuckyCyborg** [comment]
@jimgwhit This is not a Nova 4 issue, but just an collateral effect generated by a Nova installation failure, generated by your messing around with the Framework files.
