### ISSUE TITLE
error after install in sub directory

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1275]
i have error after install nova 3 with composer , i correctly set DIR 

[2016-12-31 17:47:26] production.ERROR: BadMethodCallException: Call to undefined method error in D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Support\Facades\Response.php:130
Stack trace:
#0 D:\xampp\htdocs\gitlab\nova_dev\app\Filters.php(60): Nova\Support\Facades\Response::__callStatic('error', Array)
#1 [internal function]: {closure}(Object(Nova\Routing\Route), Object(Nova\Http\Request))
#2 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Events\Dispatcher.php(193): call_user_func_array(Object(Closure), Array)
#3 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Events\Dispatcher.php(151): Nova\Events\Dispatcher->fire('router.filter: ...', Array, true)
#4 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Routing\Router.php(1447): Nova\Events\Dispatcher->until('router.filter: ...', Array)
#5 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Routing\Router.php(1411): Nova\Routing\Router->callRouteFilter('referer', Array, Object(Nova\Routing\Route), Object(Nova\Http\Request))
#6 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Routing\Router.php(1315): Nova\Routing\Router->callAttachedBefores(Object(Nova\Routing\Route), Object(Nova\Http\Request))
#7 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Routing\Router.php(1023): Nova\Routing\Router->callRouteBefore(Object(Nova\Routing\Route), Object(Nova\Http\Request))
#8 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Routing\Router.php(994): Nova\Routing\Router->dispatchToRoute(Object(Nova\Http\Request))
#9 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Foundation\Application.php(749): Nova\Routing\Router->dispatch(Object(Nova\Http\Request))
#10 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Foundation\Application.php(717): Nova\Foundation\Application->dispatch(Object(Nova\Http\Request))
#11 D:\xampp\htdocs\gitlab\nova_dev\shared\Http\ContentGuard.php(61): Nova\Foundation\Application->handle(Object(Nova\Http\Request), 1, true)
#12 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Session\Middleware.php(77): Shared\Http\ContentGuard->handle(Object(Nova\Http\Request), 1, true)
#13 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Cookie\Queue.php(49): Nova\Session\Middleware->handle(Object(Nova\Http\Request), 1, true)
#14 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Cookie\Guard.php(54): Nova\Cookie\Queue->handle(Object(Nova\Http\Request), 1, true)
#15 D:\xampp\htdocs\gitlab\nova_dev\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Nova\Cookie\Guard->handle(Object(Nova\Http\Request), 1, true)
#16 D:\xampp\htdocs\gitlab\nova_dev\vendor\nova-framework\system\src\Foundation\Application.php(615): Stack\StackedHttpKernel->handle(Object(Nova\Http\Request))
#17 D:\xampp\htdocs\gitlab\nova_dev\public\index.php(44): Nova\Foundation\Application->run()
#18 {main} [] []

**Comment by LuckyCyborg** [comment]
The installation on **sub-directory** is specified as UNSUPPORTED, sorry. 

In other hand, on the latest Nova 3, the DIR defines does NOT exists anymore.

Long story short: You are on your own, if you do not follow the Nova's creators specifications.

**Comment by vahidalvandi** [comment]
i dont  install in sub directory ...

when i click to sub url .

nova.dev/fa

show error

**Comment by LuckyCyborg** [comment]
Oh, that's another story! 👍 

Yet, looks like you do not use the latest Nova 3, which now is on version **3.75.11**.

Using always the latest Nova version **is not optionally**, as on the new releases we introduce features and bug-fixes. For example, the series **3.75.x** received a whooping **11 bug-fix releases**.
