### ISSUE TITLE
module rul 404  error

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1278]
in last version nova 3 when i create module and set route and controller .. and after enter url get 404 error. i work fine it in smvc 2.2 

do module need to enable ?

nova problem is that No documentation
👎

**Comment by LuckyCyborg** [comment]
Guess what?

There is a shiny file called app/Config/Modules.php 

You wonder for what it serve? Use the full application, with demos and examples, for... examples.

BTW, this is not a Module Route's 404 Error, but your failure to configure the application, then I will close the issue.

OH, and please stop posting issues about nothing, please use https://gitter.im/nova-framework/framework/novausers for help, or I will close your issues with no further comments. 

I do not want to see another issue open by you!

**Comment by vahidalvandi** [comment]
very thanks

**Comment by vahidalvandi** [comment]
i lose the usr gitter , please add it in readme.md master
