### ISSUE TITLE
add default module enable in config module

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1310]
after answer in gitter i try to enable a module , i add a important point to config module !!

why in module removed default code for enable ??

	'modules' => array(
        'demos' => array(
            'namespace' => 'Crm',
            'enabled'   => true,
            'order'     => 10001,
        ),
 
    ),

**Comment by LuckyCyborg** [comment]
@vahidalvandi There is not possible to have default enabling of the Modules on Nova 3.

The Modules Service from Nova 3 just read its configuration file and process the modules specified there.

Please stop comparing Nova 3 with the previous SMVC! 

They are completely different Frameworks, and they have almost nothing in common as source code.
