### ISSUE TITLE
"after" not working

### ISSUE THREAD

**Issue by jtiq** [nova-framework/framework#1315]
"after" function not working in controller...
How I can do JSONP response?

**Comment by LuckyCyborg** [comment]
@jtiq The Controller's Middleware was changed long time ago, being replaced with a better version. 

So, the `after()` methods do not work anymore. You should have to know that, if you have visited frequently the NOVA USERS chat.

> How I can do JSONP response?

Guess what? You have to return a `Response::jsonp()` from the Controller's Method.

I hope we talk on the latest Nova 3, aka **v3.75.11**, to make sense the discusion...
