### ISSUE TITLE
add redit cache like symfony , yii 

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#1318]
i research about redit and cache system , i found a open source redit , it use in many sites like facebook ,..

this document

[](https://github.com/nrk/predis/wiki)

**Comment by daveismyname** [comment]
This is a request not an issue.

**Comment by vahidalvandi** [comment]
how i can send my request ?

**Comment by daveismyname** [comment]
the best place would be to talk about it in the chat room, best to keep issues to actual issue with Nova.
