### ISSUE TITLE
Initial install fails to load for 3.75.15

### ISSUE THREAD

**Issue by flrrrhoffpauir** [nova-framework/framework#1490]
Following the installation instructions and then navigating to the local url produces the following error:
`Missing argument 2 for Nova\Config\Repository::__construct(), called in /Applications/MAMP/htdocs/sparkles_new/webapp/app/Boot/Start.php on line 127 and defined`

Where is the environment variable meant to be set?

**Comment by LuckyCyborg** [comment]
You have done the installation exactly *when the System is already updated* for certain features and improvements, while *the Application still waits for merging* its https://github.com/nova-framework/framework/pull/1488

In short time, this pull request on Application will be merged, a new release made, then everything would be OK.

**Comment by dcblogdev** [comment]
try it now.

**Comment by flrrrhoffpauir** [comment]
Great, it worked. Thank you

**Comment by LuckyCyborg** [comment]
Nice. 👍 

For further questions and talks about Nova, you can come here:

https://gitter.im/nova-framework/framework/novausers
