### ISSUE TITLE
path issue with symlinked install

### ISSUE THREAD

**Issue by sztan** [nova-framework/framework#1654]
Hello, not sure if the title is really relevant, perhaps I'll be able to change it later :

I don't exactly know wether the way I installed `nova-framework` is ok or not, although I tried to follow the recommended options on the official site.

Shortly, I installed the project in my home directory, then made a symlink to its `webroot` directory from `/var/www/html/myApp` (`myApp` is the symlink. On Jessie, `/var/www/html` is the apache's default webroot).

The problem is that certain resoures can't be found ('resolved'), as the used path should be `../`, and it appears it is `./` instead. For example, an image cannot be displayed, as its containing folder is searched in the webroot directory, instead of the above one...

Any advice ? To be honest, there's a thing that confuses me on the official site, it's saying :

> This framework was designed and is strongly recommended to be
> installed above the document root directory, with it pointing to the
> webroot folder.
> 
> Additionally, installing in a sub-directory, on a production server,
> will introduce severe security issues. If there is no choice still
> place the framework files above the document root and have only
> index.php and .htacess from the webroot folder in the sub folder and
> adjust the paths accordingly.

I don't really get it...

**Comment by LuckyCyborg** [comment]
Sorry to disappoint you, but a `Help me, Obi-wan Kenobi!` call is not a Framework issue, then I will close this "issue", while I invite you on NOVAUSERS chat: https://gitter.im/nova-framework/framework/novausers
