### ISSUE TITLE
Problem to Install Nova whits composer

### ISSUE THREAD

**Issue by MultiStorm** [nova-framework/framework#1663]
Hello i try to install nova frankework by Composer on a Ubuntu 16.04 system incl apache2
composer say:

Script php forge optimize handling the post-update-cmd event returned with an error

                                                                                                                                              
  [RuntimeException]                                                                                                                          
  Error Output: PHP Fatal error:  Class 'Nova\Foundation\Support\Providers\AuthServiceProvider' not found in /var/www/html/framework/foldern  
  ame/app/Providers/AuthServiceProvider.php on line 9 

i have checkout the Nova Sources to /var/www/html/
git have create -> /var/www/html/framework and i have create a virtual host file for the nova Document Root cn xou help me?

**Comment by LuckyCyborg** [comment]
To create a new Nova Framework application you should use the command:
```bash
composer create-project nova-framework/framework foldername 3.* -s dev
```

**Comment by MultiStorm** [comment]
i have it:

> /var/www/html/framework$ composer create-project nova-framework/framework foldername 3.* -s dev
Installing nova-framework/framework (v3.77.25)
  - Installing nova-framework/framework (v3.77.25)
    Downloading: 100%         

Created project in foldername
Loading composer repositories with package information
Updating dependencies (including require-dev)            
  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing filp/whoops (2.1.8)
    Loading from cache

  - Installing predis/predis (v1.1.1)
    Loading from cache

  - Installing monolog/monolog (1.22.1)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.7)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.3.0)
    Loading from cache

  - Installing symfony/translation (v3.2.8)
    Loading from cache

  - Installing nesbot/carbon (1.22.1)
    Loading from cache

  - Installing patchwork/utf8 (v1.3.1)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing symfony/debug (v3.2.8)
    Loading from cache

  - Installing symfony/event-dispatcher (v3.2.8)
    Loading from cache

  - Installing symfony/http-foundation (v3.1.10)
    Loading from cache

  - Installing symfony/http-kernel (v3.1.10)
    Loading from cache

  - Installing stack/builder (v1.0.4)
    Loading from cache

  - Installing symfony/var-dumper (v3.1.10)
    Loading from cache

  - Installing symfony/routing (v3.1.10)
    Loading from cache

  - Installing symfony/process (v3.1.10)
    Loading from cache

  - Installing symfony/finder (v3.1.10)
    Loading from cache

  - Installing symfony/console (v3.1.10)
    Loading from cache

  - Installing nova-framework/system (v3.77.23)
    Cloning 89f79f0e4c43af3979c8472762a3a1b222c35459

  - Installing almasaeed2010/adminlte (v2.3.11)
    Loading from cache

  - Installing twbs/bootstrap (v3.3.7)
    Loading from cache

filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
patchwork/utf8 suggests installing ext-intl (Use Intl for best performance)
patchwork/utf8 suggests installing ext-mbstring (Use Mbstring for best performance)
patchwork/utf8 suggests installing ext-wfio (Use WFIO for UTF-8 filesystem access on Windows)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
Writing lock file
Generating autoload files
> php forge optimize
PHP Fatal error:  Class 'Nova\Foundation\Support\Providers\AuthServiceProvider' not found in /var/www/html/framework/foldername/app/Providers/AuthServiceProvider.php on line 9
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Nova\\Foundation\\Support\\Providers\\AuthServiceProvider' not found","file":"\/var\/www\/html\/framework\/foldername\/app\/Providers\/AuthServiceProvider.php","line":9}}Script php forge optimize handling the post-update-cmd event returned with an error

                                                                                                                                              
  [RuntimeException]                                                                                                                          
  Error Output: PHP Fatal error:  Class 'Nova\Foundation\Support\Providers\AuthServiceProvider' not found in /var/www/html/framework/foldern  
  ame/app/Providers/AuthServiceProvider.php on line 9                                                                                         
                                                                                                                                              
                                                                                                                                              

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by LuckyCyborg** [comment]
You are sure that you checked the installation requirements?

Looks like you do not have a PHP extension enabled, then the Composer is stuck in an old System, aka **nova-framework/system**.

I talk about **MBstring**, specially.

**Comment by MultiStorm** [comment]
Yes you were right, "mbstring" was missing
