### ISSUE TITLE
Error when installing with Composer

### ISSUE THREAD

**Issue by flrrrhoffpauir** [nova-framework/framework#1892]
When I run
`composer create-project nova-framework/framework newproject 3.77.4 -s dev`

I get the following error (including a few lines for context):

```Writing lock file
Generating autoload files
> php forge optimize

Fatal error: Class 'Patchwork\Utf8\Bootup' not found in /Applications/MAMP/htdocs/newproject/app/Boot/Start.php on line 42
Script php forge optimize handling the post-update-cmd event returned with error code 255```

**Comment by LuckyCyborg** [comment]
We are now at `3.78.20` / Kernel `3.78.20`, so you are some dozen versions in the past.

Most likely you updated to this Kernel version, while you are not updating the application.

**Comment by dcblogdev** [comment]
use

```
composer create-project nova-framework/framework newproject 3.* -s dev
```

**Comment by flrrrhoffpauir** [comment]
Thanks, I used:
`composer create-project nova-framework/framework newproject 3.78.20 -s dev`
and it seems to have installed successfully

when I tried:
`composer create-project nova-framework/framework newproject 3.* -s dev`

I got:
`zsh: no matches found: 3.*`

**Comment by dcblogdev** [comment]
strange I use that command myself on bash, but if specify the version works then great.
