### ISSUE TITLE
Class 'Nova\Module\ModuleServiceProvider' not found

### ISSUE THREAD

**Issue by Koredeoluwafemi** [nova-framework/framework#1906]
Hello Friends,

I get this after update one of my libraries with vendor, what can I do. I am working on an inherited project. Please kindly suggest how to go about this.

**Comment by dcblogdev** [comment]
in each module the module service provider's use statement:

```php
use Nova\Module\Support\Providers\ModuleServiceProvider as ServiceProvider;
```

needs replacing to Modules:

```php
use Nova\Modules\Support\Providers\ModuleServiceProvider as ServiceProvider;
```

**Comment by LuckyCyborg** [comment]
@Exolve I suggest you to make a clean application of the latest Nova 3 from https://github.com/nova-framework/app/ , then to put back into site the modules, themes and other customization you have.

Most likely, there are many other (small) issues in you site, which you need to fix.

The faster way is like I said, a clean (re-)start. 

Eventually, you can do a installation of the demo application from https://github.com/nova-framework/framework/ to study the given examples.

**Comment by dcblogdev** [comment]
I concur.

**Comment by Koredeoluwafemi** [comment]
Thanks a lot for your response.
I reverted the change by using the backup vendor folder instead.
