### ISSUE TITLE
Full Application - Module seeding not working

### ISSUE THREAD

**Issue by hoekie** [nova-framework/framework#1993]
Hi there!

The following errors are shown when i try to seed the modules:
1. Unknown column 'required' in 'field list'.
2. Unknown column 'validation' in 'field list'.

I noticed the following:
1. In the CreateFieldsTable class, the 'required' field is missing.
2. 'validation' must be 'validate' in the $fields->create array of ProfileSeeder.php.

When i fixed those errors,  the Users table was not seeded and i noticed that ProfileSeeder.php has the same classname as UsersTableSeeder.php but when i changed the classname of ProfileSeeder.php to ProfileSeeder the error 'App\Modules\Users\Database\Seeds\UsersTableSeeder does not exist' is shown.

Any suggestions?

Thanks!

Richard Hoek

By the way...
In the 'Install' section, the documentation says: 'php forge seed'. I gues that it must be 'php forge db:seed'... :)

**Comment by LuckyCyborg** [comment]
To initialize the database used by the full app, you need to execute the following sequence:
```txt
php forge migrate
php forge db:seed
php forge module:migrate
php forge module:seed
```
And thanks for noticing the seeder name mismatch. In fact is some stalled file.

Will be fixed (removed) in the next release. 

PS. You talk about the full app, which gives you examples and demos, the production app, from where you should develop your sites has no modules: https://github.com/nova-framework/app
