### ISSUE TITLE
404 Page being loaded by Bootstrap theme instead of custom theme

### ISSUE THREAD

**Issue by flrrrhoffpauir** [nova-framework/framework#2003]
It looks like by default the `404.php` page in `app/Views/Errors` is being rendered by `app/Themes/Bootstrap/Layouts/Default.tpl`

How can I change it so that my custom theme's Default.tpl renders it?

**Comment by LuckyCyborg** [comment]
Nope, it is even tragic: it use the default Layout for Errors, also Bootstrap based, with no themes usage at all.

Reason: this thing should do not do mistakes.
 
So, you have two options:

- You edit the default Layout used for Error Views: `Layouts/Default`, that's located in `app/Views`
- You adapt `App\Exceptions\Handler@renderHttpException` 

Both options are at App level. Customize as you like.

To note that my suggestions are valid for the latest version of Nova 3.
