### ISSUE TITLE
Translating simplemvcframework.com?

### ISSUE THREAD

**Issue by nekomajin** [nova-framework/framework#209]
@daveismyname: As mentioned in #205 and many other issues you just rebuild / redesign the website http://simplemvcframework.com. Are you planning a translation of the website?
I ask for the reason, because I'm planning a german blog for SMVC framework to begin. This I write for german users and other interested parties: about the development progresses, what's going on GitHub, tutorials and much more ...

**Comment by daveismyname** [comment]
I haven't considered that, I only know english I could use a translater like Google Translate but the wording may not be accurate, it's something to think about.

When looking at other peoples sites in different languages I tend to let Google translate the page.

**Comment by nekomajin** [comment]
On the website http://pointlinux.org/ po files are used for the translation. In the [wiki](http://wiki.pointlinux.org/index.php?title=Localization) is the process of translation explained. There are also many tutorials about [gettext](https://en.wikipedia.org/wiki/Gettext) / [po](https://lingohub.com/blog/2013/07/php-internationalization-with-gettext-tutorial/) and [PHP](http://php.net/manual/de/book.gettext.php) is supported. We can send you the po files with translations and you take it on the website.
Another possibility would be the SMVC core class "Language". Depending on whether you want to and the expense is not too great.

**Comment by 834rd** [comment]
Good idea! I can help with german...

**Comment by geomorillo** [comment]
I could help with Spanish and maybe Dutch

**Comment by volter9** [comment]
I could help with Russian

**Comment by yoelrola** [comment]
i have no problem helping with translate to spanish

2015-11-10 1:14 GMT-03:00 volter9 <notifications@github.com>:

**Comment by daveismyname** [comment]
Wow thanks a lot guys that settles it then! I'll add the site to GitHub once I've got the language changes in place 

The community has spoken lol!

**Comment by QsmaPL** [comment]
I could help with Polish :)

**Comment by jimgwhit** [comment]
@volter9  I used to watch Star Trek, and even aliens clear across the galaxy spoke English. Okay guys that was just a joke.

**Comment by volter9** [comment]
@jimgwhit, seems like a good joke to me :D

**Comment by josecarlosweb** [comment]
I could help with Portuguese ;-)

**Comment by daveismyname** [comment]
I'm going to close this for now, something to revisit in the future.
