### ISSUE TITLE
"Language" and "Logs" instead to "language" and "logs"

### ISSUE THREAD

**Issue by LuckyCyborg** [nova-framework/framework#680]
While I noticed with great satisfaction that the common sense take over over democratically voted "who is for willingly eating our own guns" (aka "nova" folder idea), still I believe that will be even more cool to use a consistent naming of folders into Application. 

Like the title say:

"Language" and "Logs"  folders name,  instead to "language" and "logs".

**Comment by daveismyname** [comment]
yes agreed I'm having huge problems at the moment with committing files to github seems to have well and truly messed up!

routing the default css files on my localhost pauses for ages, I'm assuming something vital has been changed/messed by my the same issue.

**Comment by LuckyCyborg** [comment]
@daveismyname OKay, then I will take a look. Your tree is already stabilized to shoot PRs?

**Comment by daveismyname** [comment]
it's all gone horribly wrong! yes please I think it's partly due to my github desktop software ignore case when they are changed.

**Comment by tomvlk** [comment]
Or it could be Windows related maybe..? Best option would be to remove folder, commit, add the same folder with upper case and commit again. 
Not the best solution tho. Maybe git add --force would help too.

**Comment by LuckyCyborg** [comment]
@daveismyname Just describe well where you want to arrive and watch for my PRs. I'm there to help you, as always...

**Comment by daveismyname** [comment]
@tomvlk @LuckyCyborg I'm on MAC I was doing a whole bunch of things last night. I'm not sure where I messed up.

Lesson is don't be making critical changes when it's 2 in the morning!!

OK so where I need to be is the folders within app should start with a capital letter and see where I've gone wrong or missed a file/s for the routing of assets.

I miss the goold old days of putting everything in a zip and uploaded ;)

**Comment by LuckyCyborg** [comment]
@daveismyname Okay, then. 

Give me 30 minutes to configure a new testing site (virtual host) using your latest work, to look into the real thing, then I will start to propose fixes...

**Comment by daveismyname** [comment]
thanks I appreciate this I've got myself all mixed up.

**Comment by LuckyCyborg** [comment]
@daveismyname No problem, eventually if everything literally going South, I could/would call for Emergency Squad Helping... ;)

**Comment by LuckyCyborg** [comment]
@daveismyname Then, please stop pushing now into Master branch, I will use (now) it as reference.

**Comment by daveismyname** [comment]
Yes I've stopped doing anything from this end.

**Comment by daveismyname** [comment]
oh I don't believe it, the problem I was having with my local server was due to putting the wrong address in my SITEURL constant!!!

Everyday is a school day! how embarrassing.

@LuckyCyborg are you doing anything still? I'm going to update server.php with the updated path.

**Comment by LuckyCyborg** [comment]
@daveismyname Go with. 

Right now I carefully read the code and compare with (my) expectations.

But, looks that we already we in a safe harbor.

**Comment by daveismyname** [comment]
great thanks for your help. :+1:
