### ISSUE TITLE
assets and image not working

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#683]
@daveismyname In ver 3.0 prior to you finalizing nova I had this in my header
```
<link href="<?php echo Helpers\Url::resourcePath(); ?>css/style.css" rel="stylesheet">
```
It isn't working in new nova.  see these screenshots
* ver 3.0
https://drive.google.com/file/d/0B1_PFw--3o74TXZwMEpmUVRDbkU/view?usp=sharing  
* nova
https://drive.google.com/file/d/0B1_PFw--3o74cnpDbVBEYmxlU0E/view?usp=sharing  
And in ver 3.0 I have an upload folder this code
```
if (empty($row->dogpic)) {
                    echo '<td class="imgtd">' . '&nbsp;' . '</td>';
                    //echo '<td style="width:100px;">' . '&nbsp;' . '</td>';
                } else {
                    $linev = '';
                    $linev = '<td class="imgtd"><a href="' . DIR . 'dog/view?dogid=' . $row->dogid . '">';
                    //$linev = '<td style="width:100px;"><a href="' . DIR . 'dog/view?dogid=' . $row->dogid . '">';
                    $linev = $linev . '<img src="' . DIR . 'upload/imgdogs/' . $row->dogpic . '" alt="" class="image"></a></td>';
                    echo $linev;
                }
```
would show the image. However it is not showing an image now as you can see in screen shots.  Ver 3.0 was all working just before the final step to nova.  Can you help sort out why it's not working.  Data is retrieved from database ok.

**Comment by daveismyname** [comment]
Where is your css if it's within your theme then you would use:

````
<link href="<?php echo Url::templatePath(); ?>css/style.css" rel="stylesheet">
````

It looks like you're asking for css to load from nova/assets/css/style.css

**Comment by LuckyCyborg** [comment]
@daveismyname Hey! You made release?

There is a problem with your changing to **basepath** of the generic assets folder. It should be "assets" not capitalized "Assets".

**Comment by daveismyname** [comment]
yes I've corrected both the repo and the release.

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg how about my upload folder mentioned above, that falls under
```
mysite/upload
```
Why isn't images loading any longer from this folder, see screenshots and code above please.

**Comment by daveismyname** [comment]
they should just load since there is the public already, have happens if you put the pull image path including the image in the browser url, does it load?

**Comment by jimgwhit** [comment]
```
http://localhost/novadave/upload/imgdogs/kate144.jpg  /ver 3.0 works
```
```
http://localhost/nova/upload/imgdogs/kate144.jpg  // don't work get 404 error
```
The page you were looking for could not be found

**Comment by daveismyname** [comment]
OK I'm investigating this now.

**Comment by daveismyname** [comment]
OK found the issue remove/comment out this lines from your .htaccess file.

````
#comment out to keep trailing slashes
RewriteRule ^(.+)/$ $1 [R=301,L]
````

**Comment by LuckyCyborg** [comment]
@daveismyname A last nitpicking:

We should have into app/Config.example.php 

```php
define('LANGUAGE_CODE', 'En');
```

Notice the capitalized **En**

**Comment by LuckyCyborg** [comment]
@daveismyname 

> RewriteRule ^(.+)/$ $1 [R=301,L]

And why we need that, while your brand-new Routing manage the cases without a grr?

**Comment by daveismyname** [comment]
to be honest I'm not sure at what point it was put in, I think it's legacy code from 2.2 I don't see it being needed anymore.

**Comment by jimgwhit** [comment]
@daveismyname I will try that, but I moved css and js to app\templates\default\assets and I even tried hard coding like
```
<link href="http://localhost/nova/app/Templates/Default/assets/css/style.css" rel="stylesheet">
<link href="http://localhost/nova/app/templates/default/assets/css/style.css" rel="stylesheet">
<link href="http://localhost/nova/app/templates/Default/assets/css/style.css" rel="stylesheet">
<link href="http://localhost/nova/app/Templates/default/assets/css/style.css" rel="stylesheet">
```
None of these lines will load the css.

**Comment by jimgwhit** [comment]
@daveismyname commenting that worked so far, now should I have css and js
* in assets in root 
or
* app\Templates\Default\assets  
Or does it make any difference?

**Comment by daveismyname** [comment]
I'd say in app\Templates\Default\Assets

**Comment by LuckyCyborg** [comment]
@daveismyname 

Dave, the we have "Assets" into Template and "assets" into base path.

**Comment by daveismyname** [comment]
yes since your first introduction to Assets it's been that way, are you now saying it should be assets? it's Assets in your branch too.

**Comment by LuckyCyborg** [comment]
@daveismyname Sure, those folders are OK.

/assets
/app/Templates/Default/Assets

But I wonder what you want todo with **relativeTemplatePath**, where you do not compute the correct URI path, but also you do not compute the correct filesystem path...

**Comment by daveismyname** [comment]
I think it should be the same as templatePath just not including SITEURL, what are your thoughts?

**Comment by LuckyCyborg** [comment]
@daveismyname To be the same as templatePath we should also apply the path transformation, then to have:

```php
public static function relativeTemplatePath($custom = TEMPLATE, $folder = '/assets/')
    {
        $template = Inflector::tableize($custom);

        return 'templates/' .$template .$folder;
    }
```

To note that templatePath() return a virtual URL path, using the Routing conventions, then able to be transformed back.

I supposed the relativeTemplatePath should return the real relative filesystem path toTemplate  assets.

**Comment by LuckyCyborg** [comment]
@daveismyname The relative real path was supposed to be useful into **Helpers\Assets**.

Which helper you missed to adjust to the new structure. Like it is now, the caching will not work.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, you Nova log is really, but really inspiring. You made it yourself or you asked for a graphic designer?

**Comment by daveismyname** [comment]
> Which helper you missed to adjust to the new structure. Like it is now, the caching will not work.

yes I'll look at this next.

> BTW, you Nova log is really, but really inspiring. You made it yourself or you asked for a graphic designer?

It was designed by my partner I can't design that well.

**Comment by daveismyname** [comment]
assets helper now works I didn't need to alter the relativeTemplatePath()

**Comment by LuckyCyborg** [comment]
@daveismyname You are sure? Under Linux or any case sensitive operating system and  filesystem, for 

```php
$path = APPDIR.Url::relativeTemplatePath().'js/compressed.min.js';
```

we will have, under any any Linux based shared hosting something like

```
/home3/novafan/public_html/app/templates/Default/assets/js/compressed.min.js
```

while the **real path** is:

```
/home3/novafan/public_html/app/Templates/Default/Assets/js/compressed.min.js
```

And there the file serving will kick the bucket.

I hope that in one day you'll understand **why** my Team Leader strongly "recommend" us to use Linux even when we watch our favorite Porn and if one of us will be found using Windows or MAC, we are simply out.

**Comment by daveismyname** [comment]
of course you are correct! I should test on a live server instead of relying on results from a local server, I should try Linux as an OS one day, I love my shiny mac though :)

Got the cache to work on a realt server http://nova.theonecrm.co.uk

**Comment by LuckyCyborg** [comment]
@daveismyname Still, commenting in your 0bbbae0ff4378b222a151bd075c97d1ac25b2e05

Why you apply the **strtolower**?

To make a compatible URL for Routing's files serving is more complex. Think that for a Template called **ShinyOne** you should have a snake_case transformation to **shiny_one**

**Comment by daveismyname** [comment]
ah I didn't consider that it was so to the output in the source code was lower case but that's not essential. I'll remove the strtolower.

**Comment by LuckyCyborg** [comment]
@daveismyname How about to really calculate a Routing compatible URL path?

It is simple: the filesystem path could be calculated with **APPDIR .relativeTemplatePath()** while the other is given by **templatePath()**.

**Comment by kowston** [comment]
> BTW, your Nova logo is really, but really inspiring. You made it yourself or you asked for a graphic designer?

@LuckyCyborg just curious, when you say 'Nova logo is really, but really inspiring', it almost seems like there is a word missing that would suggest a way the logo could be improved. Let me know if this is the case and I will improve however I can.

**Comment by daveismyname** [comment]
@LuckyCyborg I've altered it now I have a theme DefaultOne which comes out:

````
<link href="/templates/default_one/assets/css/compressed.min.css" rel="stylesheet" type="text/css">
````

Any problems with this change?

**Comment by LuckyCyborg** [comment]
@daveismyname That's good. It is really what the Routing expects for a properly back transformation from URL to file path.

@kowston Please, do not over-read my statements; like Dave already know, I barely speak the Albion's noble Language. And I really loved that logo. Congratulations for it!

**Comment by daveismyname** [comment]
Great, I'm done for today. Tomorrow I can start doing some screencasts was holding off until the structure was good to go.

**Comment by kowston** [comment]
@LuckyCyborg Thank you very much.

**Comment by LuckyCyborg** [comment]
@daveismyname @kowston Good night; and again, congratulations for the superb work made!

**Comment by daveismyname** [comment]
Thanks and thanks for pointing the improvements and to @jimgwhit for pointing out the assets problem.
