### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#684]
@daveismyname Good issue here, you did a real good job on Nova, and the install video you made.  You were able to enhance the framework, yet keep it flexible and simple.  Great Job. And thank you for making installation flexible as well.  How do you do it?  Oh and good job on enhancing the CSRF helper and the cli tool. And thanks for taking the time for US, the users of Nova, It has been a GREAT framework.

**Comment by daveismyname** [comment]
Thanks Jim, I appreciate all the testing you've done for a long time, really help to iron out what's not caught.

Thanks for the kind words too :) it wasn't easy but we got there in the end, I'm really happy with the outcome.
