### ISSUE TITLE
Having trouble with Routes

### ISSUE THREAD

**Issue by daveozoalor** [nova-framework/framework#687]
After installing nova and renaming Config.example.php
localhost/nova = 404 page you are looking for not found.

I had to manually navigate to localhost/nova/public
To see the link saying "open subpage".
When i clicked the link, it redirected to localhost/subpage
Instead of localhost/nova/subpage

Then the localhost/nova/subpage does not show up with any of its css designs. Just plain white page with writeups.

I have mode_rewrite enabled and I'm using wamp

**Comment by daveismyname** [comment]
I've put a video together showing how to install into a sub folder https://www.youtube.com/watch?v=IdVb3C_4xj8
