### ISSUE TITLE
subfolder video

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#695]
@daveismyname I have been playing around with the install.  As you know the subfolder video you just did is the way I was installing anyway.  All works except the one thing I mentioned before. 
If I have this header (the one that comes with nova)
```
<!DOCTYPE html>
<html lang="<?php echo LANGUAGE_CODE; ?>">
<head>
    <meta charset="utf-8">
    <title><?php echo $title.' - '.SITETITLE;?></title>
    <?php
    echo $meta;//place to pass data / plugable hook zone
    Assets::css([
        'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css',
        Url::templatePath().'css/style.css',
    ]);
    echo $css; //place to pass data / plugable hook zone
    ?>
</head>
<body>
<?php echo $afterBody; //place to pass data / plugable hook zone?>

<div class="container">

<p><img src='<?=Url::templatePath();?>images/nova.png' alt='<?=SITETITLE;?>'></p>
```
The welcome page works, somehow bootstrap css loads. However, this line
```
Url::templatePath().'css/style.css',
```
still doesn't work without changing 
```
public static function templatePath($custom = TEMPLATE, $folder = '/assets/')
    {
        $template = Inflector::tableize($custom);

        return SITEURL .'templates/' .$template .$folder;
    }
```
to
```
public static function templatePath($custom = TEMPLATE, $folder = '/assets/')
    {
        $template = Inflector::tableize($custom);

        return SITEURL .'app/templates/' .$template .$folder;
    }
```
But I am not asking you to change anything, just confirm this and perhaps put a line in ReadMe MD file to add app on that line for subfolder install.  
It isn't apparent unless you have a custom style.css file with something in it.  Perhaps you could do one with background color or something just to test..  
And this was a fresh install, following the video 100%.  
Again to me it is no big deal adding app/ in front of templates.  And remember you have to have something in the css file to see what I mean.

**Comment by LuckyCyborg** [comment]
@jimgwhit You are living and kicking example for why I ask Dave to NOT encourage the installation of the framework in a subfolder in **localhost**, and why should be used,, even for the local development, a **Virtual Host**. If not for else, creating a Virtual Host give a basic knowledge about how Apache configuration work.

In fact, you have a configuration problem into your Apache web-server (and I suspect what is it), which make your .htaccess to not act well, but, instead you look to changing critical elements on framework and to bypass the Routing file serving.

And you known what? Your so said "solution" work in a particular case.

Do not trust me? Please use a template called "ShinyDogs" and see what happen... ;)

I hope that one day everyone will understand that for being able to do that stunt of serving files who live in fact above the webroot, the framework become more strict about the web-server configuration.

**Comment by daveismyname** [comment]
> But I am not asking you to change anything, just confirm this and perhaps put a line in ReadMe MD file to add app on that line for subfolder install.

I've still got my copy from the video and that css file is loading fine for me, I do agree with @LuckyCyborg  that it's better to have files above the root / use a virtual host but I know you @jimgwhit so I'll so no more on that.

**Comment by jimgwhit** [comment]
@LuckyCyborg virtualhost, htaccess has nothing to do with it it's the fact that the framework is using assets helper and routing them. Otherwise there would be no issues no matter how you install the framework. So the URL helper doesn't pickup app unless using the built-in helper to do so and that is right in the documentation how that works. The only thing I don't agree with it's being forced to use a helper to load CSS I like loading my CSS manually as we've discussed before and there is absolutely nothing wrong with loading it the way I do. Even if I do a virtual host the way I load my CSS that would still be problems because you are forced to use a loading helper so to speak. But you should know that.  
So even in a virtual host or moving above public or installing the framework exactly as you would install the framework but loading my css manual way I would still have to do this
~~~
 return SITEURL .'app/templates/' .$template .$folder;
~~~
In the URL helper.
