### ISSUE TITLE
Short tags

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#699]
@daveismyname I did an install, one in which the main files are above document root (public_html), and all was working except the nova image  nova.png wasn't displaying.  After playing around with it for a while I had to change
```
<p><img src='<?=Url::templatePath();?>images/nova.png' alt='<?=SITETITLE;?>'></p>
```
to
```
<p><img src='<?php echo Url::templatePath();?>images/nova.png' alt='<?php echo SITETITLE;?>'></p>

```
Then everything worked.  I am wondering would it be better to have default regular tags rather than short tags?

**Comment by LuckyCyborg** [comment]
@jimgwhit The short tags shall be on by default into PHP 5.5 or greater, like the README.md ask for.

Something is wrong with your **php.ini** or maybe you should reconfigure/change/update your LAMP stack.

**Comment by daveismyname** [comment]
I agree they should be on according to the php manual:

````
5.4.0	The tag <?= is always available regardless of the short_open_tag ini setting.
````

Users can always change them since they're used in the demo files that will nearly always be changed by the end user.
