### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by paulokruz** [nova-framework/framework#700]
Hello,

I try NOVA, and have problem routes when use GET.

When try buid a blog with Screen cast tutorial, all is ok but when use Helper Paginator, i can´t get it work.
I have controller Blog with 2 functions index and post, in index function i use Helper paginator and paginator apear correctly but when try go to another page i receive this error : Missing argument 1 for App\Controllers\Blog::post() in C:\xampp\htdocs\www\NOVA_FRAMEWORK\app\Controllers\Blog.php on line 51.

Line 51 is function post and seems router try to load function post and not function index for next posts pages.

In attachment test files.
[NOVA_FRAMEWORK.zip](https://github.com/nova-framework/framework/files/203516/NOVA_FRAMEWORK.zip)

**Comment by paulokruz** [comment]
Thansk,

I can confirm patch fix the issue. Thaks for help.

**Comment by jimgwhit** [comment]
@LuckyCyborg if you guys would put the router back to the way it was in version 2.2 it wouldn't be having all of these problems.

**Comment by LuckyCyborg** [comment]
And why we should do that, Jim? 

Because a particular case of an empty URI with query parameters generating an issue fixed in 5 minutes?

Guess what, Jim! There is always the branch **2.2** for you, all the way... :smirk:
