### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#714]
@daveismyname  could 3.0-nova which is @LuckyCyborg s branch be renamed? You have  
a 3.0-nova and nova framework 3.#. this could cause confusion look at the latest PR it appears that someone wanted to integrate all of that into the current real master.

**Comment by daveismyname** [comment]
I'll leave that up to @LuckyCyborg. Any confusion should be clear for anyone who read the readme in 3.0-nova:

"This is a standalone Personal Project, initially being the development branch of Nova Framework"
