### ISSUE TITLE
i have a solution in multilanguage

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#719]
hi
in nova we can use language this just change static text to dynamic source array

we need change language like laraval , site.com => default and site.com/fa => persian 

i version 2.2 i add new pattern lang and same change in controller , after this i can route two language with change url .

i build a cms switch any language bellow web site use this

[](http://webineh.net/)

**Comment by vahidalvandi** [comment]
http://webineh.net/

**Comment by LuckyCyborg** [comment]
@vahidalvandi First of all, your CMS is not full multi-language, for example, the Error 404 is **only** into Arabian (?)

In other hand, I believe that to create a real full multi-language framework is way beyond the target of Nova Framework, but the final decision is not in my hand.

Finally, I believe that to make for real a multi-language framework we need to have into Routing the support for Filters or Middleware, which is not available right now. Maybe into future.

**Comment by daveismyname** [comment]
language support is now built in, languages are loaded by going to language/de or language/en etc
