### ISSUE TITLE
Class Language

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#731]
@daveismyname  After the most recent updates I am getting this error:
~~~
PHP Fatal error:  Class 'Language' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\nova\\system\\bootstrap.php on line 37
~~~
This is from apache error.log, framework worked fine til the very latest changes.  
the whole error reads:  
[Tue Apr 12 12:51:24.278374 2016] [:error] [pid 4304:tid 1192] [client ::1:50771] PHP Fatal error:  Class 'Language' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\nova\\system\\bootstrap.php on line 37  
No errors are showing up in the framework error.log, just apache.

**Comment by daveismyname** [comment]
I'm running the latest and not getting that, add this:

````
use Core\Language;
````

I'll update the file too.

**Comment by jimgwhit** [comment]
@daveismyname I figured that out, but now getting this:  
```
Class 'APPROUTER' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\nova\\system\\Core\\Router.php on line 67
```

**Comment by LuckyCyborg** [comment]
See that into framework are big changes into app/Config.php

Reconfigure it from Example

Also, big changes into bootstrap, you should update

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg that was it, when I copied the new config over, it renamed it Config_1.php, using netbeans. Working now.

**Comment by LuckyCyborg** [comment]
@jimgwhit Check for this files:

/app/Config.php
/app/Routes.php
/public/index.php
/system/boostrap.php
/system/functions.php

See if you need updates

**Comment by jimgwhit** [comment]
@LuckyCyborg see my previous comment, I got it working, thanks.

**Comment by LuckyCyborg** [comment]
@jimgwhit Okay, then...
