### ISSUE TITLE
Updates after apr-12-2016

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#740]
@daveismyname  and @LuckyCyborg I updated my framework again today apr 16, 2016.  All was working prior to latest update. Now I get this error:
~~~
2016-04-16 20:30PM - require(C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\nova\app\Modules\\Views\dog\view.php): failed to open stream: No such file or directory in C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\nova\system\Core\View.php on line 72
~~~
I am not even using a Module, so what is causing an error.  Again all worked after the april 12th update I did.  
The list page shows, but the error comes from a link to either edit or view more detail
like
```
if (empty($row->dogpic)) {
                    echo '<td class="imgtd">' . '&nbsp;' . '</td>';
                    //echo '<td style="width:100px;">' . '&nbsp;' . '</td>';
                } else {
                    $linev = '';
                    $linev = '<td class="imgtd"><a href="' . DIR . 'dog/view?dogid=' . $row->dogid . '">';
                    $linev = $linev . '<img src="' . DIR . 'upload/imgdogs/' . $row->dogpic . '" alt="" class="image"></a></td>';
                    echo $linev;
                }
```
the line 
```
$linev = '<td class="imgtd"><a href="' . DIR . 'dog/view?dogid=' . $row->dogid . '">';
```
If that link is clicked the above error occurs, but was working before.
The url would be for example:
```
http://localhost/nova/dog/view?dogid=159
```
Same thing happens with this
```
http://localhost/nova/dog/edit?dogid=160
```
No edit page comes up just 
```
An error occurred, The error has been reported.
```
To re-cap, all was working apr 12th 2016, only updated latest pr's

I tryed something, I replaced the View.php with my old apr12th 2016 file and it works, so @daveismyname there has to be some sort of error in the current View.php file.  
Or am I now forced into that new fetch thing?  All I know is the old View file works.

**Comment by daveismyname** [comment]
Do you have $error as the third param in your render call? if so remove it.

**Comment by LuckyCyborg** [comment]
@jimgwhit Please show the complete code of the faulty Method and I will take a look.

Also, no, you are not forced to use the "!fetch thing". Like I said, you can ignore it.

**Comment by jimgwhit** [comment]
Okay I did have error and removed it works. How do you do $error now please short example. Also show example in view.

**Comment by daveismyname** [comment]
you still put the errors into an array:

````
if (strlen($username) < 3) {
    $error[] = 'Username must be more then 3 characters.';
} else {
    $check = $this->model->getUserByUsername($username);
    if (strtolower($check[0]->username) == strtolower($username)) {
        $error[] = 'Username already exists!';
    }
}

if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    $error[] = 'Please enter a valid email address';
} else {
    $check = $this->model->getUserByEmail($email);
    if (strtolower($check[0]->email) == strtolower($email)) {
        $error[] = 'Email address already exists!';
    }
}
````

Then attach the errors to the data:

````
$data['error'] = $error;
````

**Comment by jimgwhit** [comment]
@daveismyname Thanks, I imagine I only need to pass $error if I am doing a custom error otherwise I don't need to worry about it.
