### ISSUE TITLE
Big slow down

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#774]
Right after PR #743 I noticed an increase in speed of the site loading and even in pagination. I was extra happy about this.  However after a couple of the latest PR's and PR #772 it is taking twice as long to load and even taking longer between pagination.  
I wonder if that $data array is being passed more than once.  Perhaps a $data array for data, and a $template array for header footer would be better.  I think some how everything in $data is being passed all around and slowing page loads down.

**Comment by geomorillo** [comment]
Sometimes is the server that goes "slow" give him a couple of days to normalize if not then comeback and yell to LuckyCyborg
