### ISSUE TITLE
New rendering not working

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#775]
I have tryed
```
$template = Template::make('default', $data);
$template->render();
        
```
Just get blank screen.

**Comment by LuckyCyborg** [comment]
@jimgwhit You probably do not copied all the files, in the right positions. You should obtain a page with header and footer, without content.

Oh, and you started to figure it that $template is an Template instance?

**Comment by Kingorgg** [comment]
Aye, works fine.

````php
        $data['title'] = $this->language->get('welcomeText');
        $data['welcomeMessage'] = $this->language->get('welcomeMessage');

        $data['content'] = View::fetch('Welcome/Welcome', $data);

        $template = Template::make('default', $data, 'Default');
        $template->render();
```

**Comment by jimgwhit** [comment]
@Kingorgg in
```
$template = Template::make('default', $data, 'Default');
```
What is the third parameter Default?  And thank you for an answer. 
If Default is a module, I don't use modules, please explain.

**Comment by Kingorgg** [comment]
You should take a look at the Template class ...

````php
    /**
     * Create a Template instance
     *
     * @param string $path
     * @param array $data
     * @param string $custom
     * @return Template
     */
    public static function make($path, array $data = array(), $custom = TEMPLATE)
    {
        // Prepare the file path.
        $filePath = str_replace('/', DS, "Templates/$custom/$path.php");

        return new Template(APPDIR .$filePath, $data);
    }
```

**Comment by jimgwhit** [comment]
@Kingorgg you have for first parameter default, shouldn't that be a path?

**Comment by Kingorgg** [comment]
$path is default.php
$custom is the Default folder

so it is Templates/Default/default.php

I mean, you don't have to do use the $custom as it has already been defined in the config file, I just prefer doing it this way (personal preference)

**Comment by jimgwhit** [comment]
This
```
        $data['content'] = View::fetch('ShinyDogs/Index', $data);
        $template = Template::make('default', $data);
        $template->render();     
```
is working, but the previous example
```
        $data['content'] = View::fetch('ShinyDogs/Index', $data);
        View::renderTemplate('default', $data);
```
makes more sense,looks easier.  
And if using the $view variable, I still don't have a good example of how the $view variable and the $template variable all gets tied together to render a view.  He included simple controller examples, but no detailed example.
