### ISSUE TITLE
Why so many template rendering techniques, overwhemed

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#776]
Currently the framework has this default.php file:
```
/**
 * Default Composed Layout - make a layout from the classic Header and Footer files.
 */

require dirname(__FILE__) .'/header.php';

echo $content;

require dirname(__FILE__) .'/footer.php';
```
A better idea is to have a template / default file like
```
/**
 * Default Composed Layout - make a layout from the classic Header and Footer files.
 */

require dirname(__FILE__)  . '/' . $header;

echo $content;

require dirname(__FILE__)  . '/' . $footer;
```
And have a way to pass in the currently wanted header / footer like mycustomerheader.php.  
The current way of
```
require dirname(__FILE__) .'/header.php';
```
the header name is hard coded in.  By passing in parameters, one custom file would work for many custom header / footer combinations.  Right now if you had 10 custom headers, you would need 10 new files also setup like:
```
require dirname(__FILE__) .'/anotherheader.php';

echo $content;

require dirname(__FILE__) .'/anotherfooter.php';
```
Now this would be a good thing.

**Comment by LuckyCyborg** [comment]
@jimgwhit Nope. The Default Layout is supposed to be an example, composing the classic elements header and footer. In real life, a Layout is supposed to be, well... a Layout. Something like:

```php
<!DOCTYPE html>
<html lang="<?php echo LANGUAGE_CODE; ?>">
<head>
    <meta charset="utf-8">
    <title><?php echo $title.' - '.SITETITLE;?></title>
    <?php
    echo $meta;//place to pass data / plugable hook zone
    Assets::css([
        'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css',
        Url::templatePath().'css/style.css',
    ]);
    echo $css; //place to pass data / plugable hook zone
    ?>
</head>
<body>
<?php echo $afterBody; //place to pass data / plugable hook zone?>

<div class="container">

<p class="pull-right">
<a href='<?=DIR;?>language/cs'>Czech</a> |
<a href='<?=DIR;?>language/en'>English</a> |
<a href='<?=DIR;?>language/de'>German</a> |
<a href='<?=DIR;?>language/fr'>French</a> |
<a href='<?=DIR;?>language/it'>Italian</a> |
<a href='<?=DIR;?>language/nl'>Dutch</a> |
<a href='<?=DIR;?>language/pl'>Polish</a> |
<a href='<?=DIR;?>language/ro'>Romanian</a> |
<a href='<?=DIR;?>language/ru'>Russian</a>
</p>
<div class="clearfix"></div>

<p><img src='<?=Url::templatePath();?>images/nova.png' alt='<?=SITETITLE;?>'></p>

<?= $content ?>

</div>

<?php
Assets::js([
	'https://code.jquery.com/jquery-1.12.1.min.js',
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js',
]);
echo $js; //place to pass data / plugable hook zone
echo $footer; //place to pass data / plugable hook zone
?>

</body>
</html>
``` 

Feel free to use 10 different Layouts, if you want to pass to Layout-based rendering, even I believe that you do something very wrong on the Dogs Site, considering that I use three Layouts in a medium CRM.

**Comment by jimgwhit** [comment]
@LuckyCyborg that looks good. In the last example
~~~
Pubic function index()
    {
        $dogsearch = (isset($_REQUEST['psch']) <> '' ? $_REQUEST['psch'] : "");
        Session::set('dogsearch', $dogsearch);
        $dogrows = $this->Dog->dogCount($dogsearch);
        Session::set('dogrows', $dogrows);
        $pages = new HelpersPaginator('10', 'p');
        Session::set('dogpage', $pages->getInstance());
        $pages->setTotal($dogrows);
        $data['pageLinks'] = $pages->pageLinks();
        $data['dogs'] = $this->Dog->getDogs($pages->getLimit2(), $pages->getPerpage(), $dogsearch);
        $viewOutput = View::fetch('ShinyDogs/Index', $data);
        $data['content'] = $viewOutput;
        View::renderTemplate('default', $data);
    }
~~~
Mainly this part
~~~
       $viewOutput = View::fetch('ShinyDogs/Index', $data);
        $data['content'] = $viewOutput;
        View::renderTemplate('default', $data);
~~~
How would these three lines be changed to use the layout you shown above?  In what folder do I create a layout file. Again I like what you did up above looks easy.

**Comment by LuckyCyborg** [comment]
Amazing, but you have to change **nothing** in your Controller's Method.

**Comment by jimgwhit** [comment]
@LuckyCyborg I think I catch your drift, is this correct instead of a template file like this
~~~
require dirname(__FILE__) .'/headerdg.php';
echo $data['content']; 
require dirname(__FILE__) .'/footer.php';
~~~
Change that same file be
~~~
The actual code here for the header
echo $data['content']; 
The actual code here for the footer
~~~
IS THAT CORRECT?   
I am literally changing this require dirname(__FILE__) .'/headerdg.php'; with actual header code.  
Please tell me that's correct and if not please explain.  Or is it actually that simple. But like I said there was never know crud example done so that threw me off.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> IS THAT CORRECT?

Yes.

**Comment by jimgwhit** [comment]
@LuckyCyborg 😊 did you see my edit about fetch will fetch remain in the framework now that I've learned that please please please don't take that out.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> please don't take that out.

Nope, I have no intention to remove the Compatibility API.

**Comment by jimgwhit** [comment]
@LuckyCyborg would you be willing to show how my controller code would change to make the same layout work with your latest techniques in the latest PR if I could get that down that would be wonderful.  
That $view and $template thing.

**Comment by LuckyCyborg** [comment]
@jimgwhit You have only to change:

```php
$viewOutput = View::fetch('ShinyDogs/Index', $data);
$data['content'] = $viewOutput;
View::renderTemplate('default', $data);
```
TO
```php
$view = View::make('ShinyDogs/Index', $data);
$data['content'] = $view;
Template::make('default', $data)->display();
```
OR, better:
```php
$data['content'] =  View::make('ShinyDogs/Index', $data);
return Template::make('default', $data);
```

**Comment by jimgwhit** [comment]
@LuckyCyborg thanks for the new examples. And when I said crud what I meant in your original example you had  
~~~
require dirname(__FILE__) .'/header.php';
echo $data['content']; 
require dirname(__FILE__) .'/footer.php';
~~~  
I didn't know I could change require dirname(__FILE__) .'/header.php'; with the actual header code. Where as a fresh crud example would have demonstrated this. I was following your instructions as given.

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous in case you missed edits.

**Comment by jimgwhit** [comment]
@LuckyCyborg you said use
```
$view = View::make('ShinyDogs/Index', $data);
$data['content'] = $view;
Template::make('default', $data)->display();
```
or better
```
$data['content'] =  View::make('ShinyDogs/Index', $data);
return Template::make('default', $data);
```
On last one, the one with
```
return Template::make('default', $data);
```
Did not work, but
```
Template::make('default', $data)->display();
```
Did work.  
What is the difference in these three here
```
View::renderTemplate('default', $data);
```
and this
```
Template::make('default', $data)->display();
```
and this
```
$template->render();
```
I mean with so many rendering techniques, it is very confusing to know which is the correct one to use, why so many?  
And the one return Template::make('default', $data); did not work.  Really over wheamed.

**Comment by LuckyCyborg** [comment]
@jimgwhit Considering that you upgrade the framework as copy/paste replace please all the files from system/Core with the latest ones from **v3.10**

**Comment by LuckyCyborg** [comment]
@jimgwhit And, if you started again to play stupid, I record you the **Rule #1** : 

# If something really overwhemed.you, just ignore it

**Comment by jimgwhit** [comment]
@LuckyCyborg funny you said I copy / paste.  Well not exactly, yeah I xcopy to gather changed files, then copy changed files to dev folder:
```
rem @ECHO OFF
SET /P mm=Month MM
SET /P dd=Day DD
SET /P yy=Yeay YYYY
IF "%mm%"=="" GOTO Error
Xcopy "C:\Users\jimcompq\Documents\GitHub\framework\*.*" "C:\Users\jimcompq\Documents\gittmp\framework" /d:%mm%-%dd%-%yy% /s
GOTO End
:Error
ECHO You did not enter your name! Bye bye!!
:End
pause
```
Now after your pr 777 and 778 what 2 files you suppose it got me, care to guess?  
answer:
```
Controller.php
View.php
```
With correct folder structure for auto copying to dev folder  
Well I be dang gum I didn't fall of the turnup truck yesterday.

**Comment by LuckyCyborg** [comment]
@jimgwhit I'm glad that you managed to get a Secret Sauce to keep in sync your reference and development trees.

But, I'm afraid that reading the changes from the new files is too much for your lazy ass. For example, you may find that App\Controllers\Wellcome@subPage use the New Style rendering... :smirk:

**Comment by geomorillo** [comment]
lol its too much for me also...

**Comment by daveismyname** [comment]
I'm using the old template loading for my needs works perfectly.

**Comment by Kingorgg** [comment]
I'm just using

````php
public function login()
{
    // more code....
        $data['content'] = View::fetch('Auth/Login', $data);
        return $data;
}
```

and

````php
    public function after($data)
    {
        View::renderTemplate('authentication', $data);
    }
```

I quite like this way :+1: .

**Comment by jimgwhit** [comment]
@daveismyname and @Kingorgg  actually after @LuckyCyborg detail example above I have the new technique figured out now and it does work. The only problem I had is he included a controller example but I didn't relate what was needed in the template to make it all work so again the above example explained better and got me going. That's all I ask for is if there is a change maybe a little more detail in the example, thanks.

**Comment by jimgwhit** [comment]
Yah no pull request so far today.

**Comment by LuckyCyborg** [comment]
@jimgwhit 
Last time when you seen me silent, the result was the rebuilding of **Core\View**. You aren't afraid? :smirk: 

PS Today is a special day in Italy. Think about 4 July in the Italian style. :+1:

**Comment by jimgwhit** [comment]
@LuckyCyborg 😯 oh no what are you up to now you're not working up another pull request are you?

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> @daveismyname and @Kingorgg actually after @LuckyCyborg detail example above I have the new technique figured out now and it does work. The only problem I had is he included a controller example but I didn't relate what was needed in the template to make it all work so again the above example explained better and got me going. That's all I ask for is if there is a change maybe a little more detail in the example, thanks.

Out of respect for you, I refuse to believe that a barely intelligent guy with vague PHP knowledge can't figure that instead to **require** a file, you can literally insert its content.

**Comment by LuckyCyborg** [comment]
@jimgwhit 
> oh no what are you up to now you're not working up another pull request are you?

Worry not. My today work is called barbecue.

**Comment by jimgwhit** [comment]
@LuckyCyborg I should have got the require thing somehow I just drew a blank but when you put your top example it hit me that's why I asked above it couldn't be that simple could it.

**Comment by jimgwhit** [comment]
@LuckyCyborg well you got me again in the sub page example
~~~
 return View::make('Welcome/SubPage')
            ->shares('title', $this->trans('subpageText'))
            ->withWelcomeMessage($this->trans('subpageMessage'));
    }
~~~
$this->trans is nothing like the other examples that you shared with me I have no idea what this even is doing.  
A bug you gave this example
~~~
$view = View::make('ShinyDogs/Index', $data);
$data['content'] = $view;
Template::make('default', $data)->display();
~~~
But sub page example you have
~~~
return View::make('Welcome/SubPage')
            ->shares('title', $this->trans('subpageText'))
            ->withWelcomeMessage($this->trans('subpageMessage'));
~~~
The two don't look nothing alike I don't even know what the bottom one is doing can anyone jump in here and help?  How would I convert top one to bottom one. I guess I understand examples when dealing with data not just nonsense messages.

**Comment by Kingorgg** [comment]
@jimgwhit $this->trans is a new method in Controller.php which helps with translation for multi language sites.


````php
    /**
     * Return a translated string.
     * @return string
     */
    protected function trans($str, $code = LANGUAGE_CODE)
    {
        return $this->language->get($str, $code);
    }
```

It is basically a shorter way to to do $this->language->get()

**Comment by LuckyCyborg** [comment]
@jimgwhit The **Core\View** and **Core\Template** design permit directly to **nest** a View instance and leave its fetching to parent instance.

There is no bug there; if you return a View or Template instance, by default, the Controller Middleware will process them according:

A View instance will be nested in a default Template instance and everything displayed.
A Template instance will be displayed.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

>  I guess I understand examples when dealing with data not just nonsense messages.

Got you a simple Laravel-style API implementation? You don't get what "with" and "withX" do?

How the Hell you written those Laravel sites, then?

Also, you read the Release Notes which @daveismyname publish? 

You even read the freaking Framework Source Code before to play stupid there?

**Comment by jimgwhit** [comment]
@Kingorgg so I can continue with 
~~~
$view = View::make('ShinyDogs/Index', $data);
$data['content'] = $view;
Template::make('default', $data)->display();
~~~ 
Right? Or is this method going to be deprecated? I thought this was the very latest technique.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Or is this method going to be deprecated?

At this question I'm one able to respond:

No, this rendering style will NOT be deprecated, because is use the New Style API native commands.

Long story short, this is one of the ways supported native by New Style API.

**Comment by jimgwhit** [comment]
@LuckyCyborg I did that way already. And just as an example here is some documentation from laravel notice Taylor gives complete example including View, path.
~~~
Sometimes you may wish to pass a view into another view. For example, given a sub-view stored at app/views/child/view.php, we could pass it to another view like so:

$view = View::make('greeting')->nest('child', 'child.view');

$view = View::make('greeting')->nest('child', 'child.view', $data);
The sub-view can then be rendered from the parent view:

<html>
    <body>
        <h1>Hello!</h1>
        <?php echo $child; ?>
    </body>
</html>
~~~
I completely understand that example and how to implement it because he gave controller and view example. And path locations. I guess I am just used to having complete examples including controller, view,  any templates, paths.   A person could copy that example and easily experiment with it.  
Sorry I did not understand your example at first, but thank you for giving a more detailed example.  
Now relax some.

**Comment by LuckyCyborg** [comment]
@jimgwhit You can use **nest()** also into latest Nova. Example:
```php
Template::make('default', $data)->nest('content', 'ShinyDogs/Index', $data)->display();
```

**Comment by jimgwhit** [comment]
@LuckyCyborg I will play around with that thanks. And I may not use all of these new techniques but I at least want to learn them so thank you for your better examples. And again I cannot believe I missed the require thing you are right I should have caught that. My focus was elsewhere, just trying to study the controller code and formulate how it all works.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> And I may not use all of these new techniques...

Of course you should NOT use all those techniques in the same time. Your site, as code, will look WTF.

I guess that you have to choose a style which you like better and stuck with it. 

Like @Kingorgg chosen his View fetching combined with returning **$data** and customization of Controller's Middleware.

**Comment by jimgwhit** [comment]
@LuckyCyborg look at this  
~~~
public function ownerpet() {
            $ownerid = $_GET['ownerid'];
            $data['owners']=Powner::find($ownerid);
            $data['pets'] = DB::table('pets')
                        ->where('ownerid', '=', $ownerid)
                        ->orderBy('petname', 'asc')->get();

            return View::make('owner/ownerpet')->with('data',$data['owners'])->with('data2',$data['pets']);
        }
~~~
Then view  
~~~
<html>
<head>
</head>
<body>


<?php
echo $data->oname;  // the petowner
echo "<br>";
echo "======================";
echo "<br>";
foreach ($data2 as $pet){
    echo $pet->petid."   ".$pet->petname."<br>";  //pets owned by petowner

}    
?>
</body>
</html>
~~~  
A laravel quick example showing a pet owner with their pets. What would the controller code be in nova to do this.

**Comment by LuckyCyborg** [comment]
@jimgwhit Similar, with View filepath change and not using 'data' as keywork, because from compatibility reasons there will exists that. Then something like:

```php
return View::make('Owner/OwnerPet')->with('data1',$data['owners'])->with('data2',$data['pets']);
```
Also, I guess that you already figured that into Nova NO QueryBuilder exists...

**Comment by jimgwhit** [comment]
@LuckyCyborg said  
> Also, I guess that you already figured that Nova ships NO QueryBuilder, thanks also to your Big Mouth...  
Now that's funny.  But remember someone can easily use illuminate, which has query builder built in.  Very easy to set up.  Remember, In old PR's I showed examples of dbal and illuminate.

**Comment by jimgwhit** [comment]
@LuckyCyborg I modified your line, this
```
return View::make('Owner/OwnerPet')->with('data1',$data['owners'])->with('data2',$data['pets']);
```
to this for a test:
```
$data['pageLinks'] = $pages->pageLinks();
        $data['dogs'] = $this->Dog->getDogs($pages->getLimit2(), $pages->getPerpage(), $dogsearch);
        $data['owners'] = 'Jimbo';
        return View::make('ShinyDogs/Index')->with('data1',$data['owners'])->with('data2',$data['dogs'])->with('data3',$data['pageLinks']);
```
Notice I included ->with('data3',$data['pageLinks'])  
But here is the question, how do I choose which template to use with this?  Say my template is named dogheader.php instead of default.php.
By the way it worked, but the only template working in default.php.  So that template question now is key to all universe.

**Comment by jimgwhit** [comment]
@LuckyCyborg never mind, I got it, had to combine info from 2 PR's.  
I made a template named dogtmpl.php
~~~
$data['content'] = View::make('ShinyDogs/Index')->with('data1', $data['owners'])->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
Template::make('dogtmpl', $data)->display();
~~~
But this is what I meant with with the various rendering techniques, it is tricky to catch on to what combination to use.  But this worked.  
Again Taylor in the laravel docs gives detailed examples, maybe you need a teaching class.  You are a good programmer, but sorry I just didn't completely follow all short examples.  But I think this is correct, right?  
Did you enjoy the bar-b-que?

**Comment by geomorillo** [comment]
A hate love relationship? lol

**Comment by jimgwhit** [comment]
@LuckyCyborg see my last reply.
