### ISSUE TITLE
language changer

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#779]
hi 
// The Framework's Language Changer.
 Router::any('language/(:any)', 'App\Controllers\Language@change');

how work ??

do change url and change language ??

i version 2.2 just change view nad language and not change url code

**Comment by geomorillo** [comment]
Read this https://github.com/nova-framework/framework/releases/tag/v3.3.0

**Comment by vahidalvandi** [comment]
ok this good but i create a simple language changer to change and route with lang code after all url but in ver smvc 2.2 have same problem 

site.com/post/new
site.com/fa/post/خبر

and i create two folder in default template like "fa" , "en"
in each fa , en have footer and header whit self config and detached nav  and logo
---------
i add a pattern in Core/Router.php
':lang'=>'[a-z]{2}'

this pattern just get 2 character like fa,en,ge and i define same routing

Router::any('(:lang)','Modules\Site\Controllers\frontend\cn_lang_other@index'); 
Router::any('','Modules\Site\Controllers\frontend\cn_lang_default@index'); 

but i need have default lang have copy router without '(:lang)' this post language code to controller in controller i define same data about selected language 
code = en| id = 1 | dir = ltr
code = fa | id = 2 | dir = rtl 

after get this , we can fetch all post with fa language because in admin i set id language inside each post or i can get one post with url site.com/fa/post/خبر 
first get fa after get id code fa , then fetch post with id slug خبر and lang id 1

by this technic i build one cms to switch to each language

http://horjin.com/ 

use this cms.

I expect in nova 3 can change route with url and each lang have deducted footer and header and Global CSS for all language 

if in your develop in nova 3 can select language like fr in simple green button subpage add lang code after link and update dynamically with 
site.com/fr/subpage  and with this code get all data about subpage in fr 

this thechnic important for Crawl Google because if each language dont have unique address dont index and just index default language and search users dot see other language site in google.

**Comment by LuckyCyborg** [comment]
@vahidalvandi We talked about the implementing of Language support into Routing and arrived at conclusion that that is far away from the objectives of Nova Framework.

Sure, it is possible an end-user to implement a multi-language site, but this is usually connected with a CMS, while Nova is NOT a CMS, but a **Framework**, then the final response is no.
