### ISSUE TITLE
The use statement with non-compound name 'Event' has no effect

### ISSUE THREAD

**Issue by daveismyname** [nova-framework/framework#838]
I’ve just done a fresh install and getting this error for Events in system and the modules: The use statement with non-compound name 'Event' has no effect.

This problem occurs in system/Events.php and app/Modules/Demo/Events.php and app/Modules/Users/Events.php

**Comment by amiroperator** [comment]
You can fix it with using "use Event as Event;"

**Comment by daveismyname** [comment]
perfect.
