### ISSUE TITLE
Login submit

### ISSUE THREAD

**Issue by amiroperator** [nova-framework/framework#839]
**After submiting login form:**

> 
> Exception information:
> 
>            Date: May 18, 2016 23:23PM
> 
>            Message: Argument 1 passed to Database\Query\Builder::compileSelect() must be an instance of Database\Query\Query, instance of Database\Query\Builder given, called in E:\Amir\Projects\nova\system\Database\Query\Builder.php on line 1136
> 
>            Code: 0
> 
>            File: E:\Amir\Projects\nova\system\Database\Query\Builder.php
> 
>            Line: 1486
> 
>            Stack trace:
> 
>            #0 E:\Amir\Projects\nova\system\Database\Query\Builder.php(1136): Database\Query\Builder->compileSelect(Object(Database\Query\Builder))
> #1 E:\Amir\Projects\nova\system\Database\Query\Builder.php(1126): Database\Query\Builder->toSql()
> #2 E:\Amir\Projects\nova\system\Database\Query\Builder.php(1116): Database\Query\Builder->runSelect()
> #3 E:\Amir\Projects\nova\system\Database\Query\Builder.php(1037): Database\Query\Builder->get(Array)
> #4 E:\Amir\Projects\nova\system\Auth\Guard.php(243): Database\Query\Builder->first()
> #5 E:\Amir\Projects\nova\system\Auth\Guard.php(170): Auth\Guard->retrieveUser(Array)
> #6 [internal function]: Auth\Guard->attempt(Array, true)
> #7 E:\Amir\Projects\nova\system\Auth\Auth.php(99): call_user_func_array(Array, Array)
> #8 E:\Amir\Projects\nova\app\Modules\Users\Controllers\Users.php(63): Auth\Auth::__callStatic('attempt', Array)
> #9 [internal function]: App\Modules\Users\Controllers\Users->login()
> #10 E:\Amir\Projects\nova\system\Core\Controller.php(78): call_user_func_array(Array, Array)
> #11 E:\Amir\Projects\nova\system\Core\Base\Router.php(187): Core\Controller->execute('login', Array)
> #12 E:\Amir\Projects\nova\system\Core\Base\Router.php(218): Core\Base\Router->invokeController('App\\Modules\\Use...', 'login', Array)
> #13 E:\Amir\Projects\nova\system\Core\Router.php(260): Core\Base\Router->invokeObject('App\\Modules\\Use...', Array)
> #14 E:\Amir\Projects\nova\system\bootstrap.php(61): Core\Router->dispatch()
> #15 E:\Amir\Projects\nova\public\index.php(68): require('E:\\Amir\\Project...')
> #16 {main}
> 
>            ---------
>

**Comment by LuckyCyborg** [comment]
@amiroperator PR incoming...
