### ISSUE TITLE
Another fatal error problem

### ISSUE THREAD

**Issue by amiroperator** [nova-framework/framework#857]
Fatal error: Cannot use Translation\Translator as Translator because the name is already in use in E:\Amir\Projects\PHP\Nova Framework\system\Validation\Factory.php on line 12

**Comment by LuckyCyborg** [comment]
Ok, thanks!

I will take a look.

**Comment by amiroperator** [comment]
All of demo method, check it please.

**Comment by LuckyCyborg** [comment]
Please replace in **Validation\Factory**:
```php
use Translation\Translator;
```
WITH
```php
use Validation\Translator;
```
and report the result.

**Comment by amiroperator** [comment]
no change.

when I opened http://novaframework.dev/demo/validate, I got that error

**Comment by LuckyCyborg** [comment]
@amiroperator Please look careful: is about replacing **Translation** with **Validation**

**Comment by amiroperator** [comment]
No just error changed:
Fatal error: Cannot use Translation\Translator as Translator because the name is already in use in E:\Amir\Projects\PHP\Nova Framework\system\Validation\Validator.php on line 13

This happened when I opened /demo/validate

**Comment by LuckyCyborg** [comment]
Please show me the first 20 line of your class **Validation\Factory**

**Comment by amiroperator** [comment]
```
<?php
/**
 * Factory - Implements the Validator Factory.
 *
 * @author Virgil-Adrian Teaca - virgil@giulianaeassociati.com
 * @version 3.0
 */

namespace Validation;

use Helpers\Inflector;
use Validation\Translator;

use Closure;


class Factory
{
    /**
     * The Translator implementation.
```

**Comment by amiroperator** [comment]
Install php 7 and make things easy

**Comment by LuckyCyborg** [comment]
I can't do it in my computer for job. :smirk:

The rule is to develop code for PHP 5.6.x which is available on servers.

**Comment by Kingorgg** [comment]
Did you also change line 13 in Validation/Validator.php from

````php
use Translation\Translator;
```
to
````php
use Validation\Translator;
```
or just the Factory?

**Comment by amiroperator** [comment]
just factory

**Comment by amiroperator** [comment]
I changed both now and it works

**Comment by Kingorgg** [comment]
Cool :+1:

**Comment by LuckyCyborg** [comment]
There is no such thing as **Translation\Translator**, That's only in one of our internal trees and it was cut off to Nova.

**Comment by Kingorgg** [comment]
Want me to submit a patch for that for the master branch? or have you got it?

**Comment by amiroperator** [comment]
@Kingorgg You can do it

**Comment by LuckyCyborg** [comment]
Already I'm prepared for pushing, guys...

**Comment by Kingorgg** [comment]
Okay, no problem :)

**Comment by amiroperator** [comment]
hehe

**Comment by LuckyCyborg** [comment]
Thanks, Gentlemen!

**Comment by LuckyCyborg** [comment]
@amiroperator BTW, you would like to be "on duty" to test the Framework under PHP7 and report quickly back the issues? This way, you cloud be my eyes on PHP7.

**Comment by Kingorgg** [comment]
I'm running on PHP7 also, so if you need two pairs of eyes ...

**Comment by LuckyCyborg** [comment]
I will be glad to have at my disposition a "hunting squad" lurking on PHP7 ! :smile:
