### ISSUE TITLE
Language validator

### ISSUE THREAD

**Issue by amiroperator** [nova-framework/framework#859]
I changed language to persian and then I translate one of messages:

`'The :attribute must be at least :min characters.' => ':attribute با?د حداقل :min کاراکتر باشد.',`

and it doesn't translated and original message just shown to me:

```
array (
  0 => 'The username must be at least 3 characters.',
)
```

**Comment by LuckyCyborg** [comment]
You talk as in being under Persian meantime, right?

**Comment by amiroperator** [comment]
except this in login page and and dashboard language didn't changed

**Comment by LuckyCyborg** [comment]
Ok. I will take a look.

**Comment by LuckyCyborg** [comment]
Yes, I found where is the problem.

**Comment by amiroperator** [comment]
Good

**Comment by LuckyCyborg** [comment]
Hehe, you don't translated the Language files from Templates and System... :smirk:

BTW, now it works, I will push that.

**Comment by amiroperator** [comment]
I know, I just tested them 
and I report the prolem

**Comment by LuckyCyborg** [comment]
Thanks for reporting and good luck with translation!

**Comment by LuckyCyborg** [comment]
@amiroperator 

This should fix the problem:

https://github.com/nova-framework/framework/pull/858/commits/29307c341e44211b15c9d7931754b735af2284e0

**Comment by amiroperator** [comment]
Ok I wait for merge

**Comment by daveismyname** [comment]
I've now merged this.

**Comment by amiroperator** [comment]
The problem doesn't fixed

**Comment by LuckyCyborg** [comment]
OK, then what say now?

**Comment by amiroperator** [comment]
Solved.
thanks

**Comment by LuckyCyborg** [comment]
No problem

**Comment by LuckyCyborg** [comment]
@amiroperator A note if you want to translate also the attributes:

```php
$attributes = array(
    'username' => __('Username'),
    'password' => __('Password')
);

$validator = Validator::make($data, $rules, array(), $attributes);

// Do something with the Validator instance.
```
To note that for translation is used the implicit domain (app), if you want a specific language domain, use **__d()**
