### ISSUE TITLE
Jim have a bunch of questions

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#863]
I get this now   
PHP Fatal error:  Class 'PHPMailer' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\nova\\system\\Helpers\\Mailer.php on line 17  
I don't even user mailer yet.

**Comment by jimgwhit** [comment]
Scratch that, I had forgot to delete old mail stuff no longer used, and dump autoload. Works now. @LuckyCyborg you are killing me with so many pull request.  
Why is there an htacces file in vendor with
```
Deny from all
```
When would this be used and how?

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> @LuckyCyborg you are killing me with so many pull request.

You are welcome! Thanks! :smirk: 

> Why is there an htaccess file in vendor with
> ```
> Deny from all
> ```
> When would this be used and how?

Those files try to save the asses of some crazy bunnies who still install Nova in sub-directory and not in my **recommended way**. 

Think some sort of Shield which you should/could ignore but maybe one day would save your ass from being fired.

> Also what is up with all the language files? When I used to watch Star Trek even aliens across the galaxy spoke English. There was the creature that looked like an aligator, he even spoke english.
Got you.

Facts are that compared with the Star Trek's aliens on the third planet of the Sol star, colloquially called Earth, are spoken much much more Languages, not only English. 

And technically, it is said that a third part of the Homo Sapiens Sapiens population speaks **Chinese** as native Language. 

Shamefully, Nova Framework doesn't have yet have Chinese Language support.

In other hand, feel free to submit translations for Klingon Language, I guess @daveismyname wil be glad to merge them.

**Comment by Kingorgg** [comment]
> In other hand, feel free to submit translations for Klingon Language,

@LuckyCyborg and @jimgwhit I was going to submit a Klingon translation after reading this, but after getting halfway through, I realised that the online translators are not very good :smile:

**Comment by daveismyname** [comment]
Whilst I speak only English I appreciate a lot of countries do not or it's not their primary language so yes we should have support for them where possible. 

Closed, issues has been resolved.
