### ISSUE TITLE
Use multiple databases

### ISSUE THREAD

**Issue by amiroperator** [nova-framework/framework#866]
What is the standard way to connect multiple databases ?

**Comment by LuckyCyborg** [comment]
In the **Database API** ?

You can define multiple configurations for database on Config.php, as additional entries beyond 'default', then you can use:

```php
$connection = Connection::getInstance('custom');

// Where custom is your 'custom' configuration entry on app/Config.php
```

**Comment by amiroperator** [comment]
What about models how connect them to those databases

**Comment by LuckyCyborg** [comment]
@amiroperator Good point! I will make today a pull request to improve this way.

**Comment by amiroperator** [comment]
@LuckyCyborg I said that because I want make a cms and it should connect to 3 db except website db.

**Comment by LuckyCyborg** [comment]
But all of them are MySQL, right?

This is the only way supported by Nova now.

**Comment by amiroperator** [comment]
Yeah All of them

**Comment by LuckyCyborg** [comment]
Perfect!

Wait for my next PR for today.

**Comment by amiroperator** [comment]
Okay. thanks
