### ISSUE TITLE
PhpFastCache version

### ISSUE THREAD

**Issue by Geolim4** [nova-framework/framework#867]
Hi Nova Team,

As i see you make use of PhpFastCache and it's a good thing :)
We are coming soon announcing the [v5](https://github.com/PHPSocialNetwork/phpfastcache/tree/v5) which is a major release that follow the psr6 and also comes with a [Symfony bundle](https://github.com/PHPSocialNetwork/phpfastcache-bundle)

Cheers,
Georges

**Comment by LuckyCyborg** [comment]
@Geolim4 Thanks for your kind notice!

**Comment by daveismyname** [comment]
We'll update when it's released ;)

**Comment by Geolim4** [comment]
You're welcome :)

**Comment by geomorillo** [comment]
All ok

**Comment by Geolim4** [comment]
Hi,

as I see you used to extends phpFastCache, as of the V5 [we provide a proxy](https://github.com/PHPSocialNetwork/phpfastcache/blob/v5/examples/extendedPhpFastCache.php) especially for this.

Of course, [the wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V5]-Extending-phpFastCache) also provide some help.

For your information we reached the RC1 status, a first release should appears very soon.
However we still will maintain the [V4 for 2 years](https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V4]-Support-timeline).

Cheers,
Georges

**Comment by LuckyCyborg** [comment]
@Geolim4 Thanks for hints, all we want is that to enclose the **PhpFastCache** as our **Helpers\FastCache**. :smirk: 

Sure, making singletons with singletons is not the best idea, if there is a way to use on our Singleton the PhpFastCache engine, I will glad for your suggestions.

**Comment by Geolim4** [comment]
So you will have only one singleton but can be any driver kind ? (Memcached, Files etc)

**Comment by LuckyCyborg** [comment]
@Geolim4 Basically, is a Facade which enclose and give instances of PhpFastCache, but for different drivers:

```php
    /**
     * Constructor.
     *
     * @param string $storage The Storage type.
     */
    protected function __construct($storage)
    {
        $config = Config::get('cache');

        $config['storage'] = $storage;

        // Initialize the PhpFastCache instance.
        $this->cache = CacheManager::getInstance($storage, $config);
    }

    /**
     * Get the FastCache instance of specified Storage type.
     *
     * @param string $storage
     * @return mixed
     */
    public static function getInstance($storage = 'files')
    {
        if (! isset(self::$instances[$storage])) {
            static::$instances[$storage] = new static($storage);
        }

        return static::$instances[$storage];
    }
```

**Comment by Geolim4** [comment]
For the v4 you can keep it like that.
For the V5 the thing can be much easier:

```php

<?php
/**
 * FastCache - A simple Cache Management built on top of phpFastCache.
 *
 * @author Virgil-Adrian Teaca - virgil@giulianaeassociati.com
 * @version 3.0
 */

namespace Helpers;

use Core\Config;

use phpFastCache\Proxy\phpFastCacheAbstractProxy;

/**
 * FastCache
 */
class FastCache extends phpFastCacheAbstractProxy
{
    // The FastCache instances.
    protected static $instances = array();

    // The phpFastCahe instance.
    // The proxy handle this
    // protected $cache = null;


    /**
     * Constructor.
     *
     * @param string $storage The Storage type.
     */
    protected function __construct($storage)
    {
        $config = Config::get('cache');
        parent::__construct($config);
        // That's all
    }

    /**
     * Get the FastCache instance of specified Storage type.
     *
     * @param string $storage
     * @return mixed
     */
    public static function getInstance($storage = 'files')
    {
        if (! isset(self::$instances[$storage])) {
            static::$instances[$storage] = new static($storage);
        }

        return static::$instances[$storage];
    }

    /**
     * Provide transparent access to any of \phpFastCache Methods.
     *
     * @param $method
     * @param $params
     * @return mixed
     */
    public function __call($method, $params = null)
    {
       // Already handled by the proxy with annotations
       // This will help out your IDE to find the public methods
       // return call_user_func_array(array($this->cache, $method), $params);
    }
}


```

**Comment by LuckyCyborg** [comment]
@Geolim4 Thanks you very much, for your literal example, and to say that it looks wonderful!

Be sure that when you go stable release for **V5**, we will pass to, it looking be exactly what we need for.

**Comment by Geolim4** [comment]
Here is a quick migration guide we made to help out guys like you that makes use of pfc :)

https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V4]-Migrating-your-code-to-the-V5

**Comment by Geolim4** [comment]
Also be sure to remove the empty __call() magic method to avoid parent overriding.

**Comment by LuckyCyborg** [comment]
@Geolim4 Thanks again, for those tons of details about your Project!

BTW, you have a ETA for **V5** ? The **phpFastCacheAbstractProxy** looks spectacular useful for those (like us) who will to use **PhpFastCache** as native Caching System for their Framework.

**Comment by Geolim4** [comment]
The V5 will be probably maintained until 2019 at least with 5.1, 5.2 and 5.3

**Comment by LuckyCyborg** [comment]
Thanks!

**Comment by Geolim4** [comment]
As you requested for the date, we are releasing the v5 this weekend :)
Regards,
Georges

**Comment by Geolim4** [comment]
Hi Lucky, we just released the V5.
Regards,
Georges

**Comment by Geolim4** [comment]
Hello,

FYI, the V6 is gonna be out for Feb 2017, it has for main new features Cache Events and an ActOnAll helper for multiple instances projects.
Ofc the V5 will be kept updated for at least two years, but the V6 does not includes major breaking changes.

Cheers,
Georges
