### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#884]
After updating all PR's through #882 when I try to edit a record I get
```
An error has occurred. This error has been reported.
```
But nothing is written to error.log like before.

**Comment by Kingorgg** [comment]
I'm not sure which version you updated from, but check **app/Storage/Logs/error.log**, as the log file was moved.

**Comment by LuckyCyborg** [comment]
@jimgwhit

WHEN you try to edit a record?

Using of course **Helpers\Database**, right?

**Comment by jimgwhit** [comment]
@LuckyCyborg found log, remind me, how do I redirect now, dug through PR's can't find it.  I also changed the use for session.

**Comment by LuckyCyborg** [comment]
I do not understand you question about redirect

**Comment by Kingorgg** [comment]
Instead of

````php
Url::redirect()
``` 
You can now use:

````php
Redirect::to()
```

and you can pass an optional parameter like: **Redirect::to('login')->with('message', 'Wrong Username or Password');**

**Comment by LuckyCyborg** [comment]
@Kingorgg That Redirect instance should be returned, else nothing happen...

**Comment by Kingorgg** [comment]
@LuckyCyborg Changed my comment, thanks, forgot to put that in.

**Comment by jimgwhit** [comment]
@LuckyCyborg normally after an edit I redirect back to the page I click edit on like
```
Url::redirect('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
```
But I am not supposed to use Url::redirect anymore, is that correct? I am going to change it ot the new
```
return Redirect::to //style
```
I can't find what top use statement I need for this. It is not in release log.

**Comment by Kingorgg** [comment]
@jimgwhit 

````php
use Core\Redirect;
```

**Comment by LuckyCyborg** [comment]
@Kingorgg Do not exists anymore. Should be:

```php
use Redirect;
```

**Comment by jimgwhit** [comment]
@Kingorgg 
```
return Redirect::to('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
```
is not redirecting any where

**Comment by Kingorgg** [comment]
@jimgwhit Sorry, see @LuckyCyborg's comment.

**Comment by jimgwhit** [comment]
here are current use
```
namespace App\Controllers;

use Core\View;
use Core\Controller;
use Core\Redirect;
use Helpers\Clnsantize as Cln;
use Helpers\Url; // as Url;
use Session; // as Session;
use Helpers\Paginator as HelpersPaginator;
```
what needs changing?

**Comment by Kingorgg** [comment]
````php
use Core\Redirect;
```
to
````php
user Redirect;
```

**Comment by jimgwhit** [comment]
Changed to use Redirect; and got
Exception information:

           Date: May 25, 2016 15:46PM

           Message: The HTTP status code is not a redirect ("200" given).

           Code: 0

           File: C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\nova\vendor\symfony\http-foundation\RedirectResponse.php

           Line: 42

           Stack trace:

**Comment by LuckyCyborg** [comment]
> But I am not supposed to use Url::redirect anymore, is that correct?

Is a wonderful idea to stop using that method.

```php
use Redirect;
```

But, if you use the new Response API, is better to use also the new Request API and the new Session API. In few words, the new APIs.

**Comment by LuckyCyborg** [comment]
What is your command?

And please write with code, for the name of Gods.

**Comment by jimgwhit** [comment]
@LuckyCyborg 
> What is your command?

I don't understand, what command?

**Comment by LuckyCyborg** [comment]
Show me the entire redirect code, on shiny code tag know by Markdown

**Comment by jimgwhit** [comment]
last I got was
```
Date: May 25, 2016 15:46PM

           Message: The HTTP status code is not a redirect ("200" given).

           Code: 0

           File: C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\nova\vendor\symfony\http-foundation\RedirectResponse.php

           Line: 42

           Stack trace:
```

**Comment by LuckyCyborg** [comment]
Show me the entire Controller method, to understand right.

**Comment by jimgwhit** [comment]
```
return Redirect::to('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
```

**Comment by jimgwhit** [comment]
```
function edit()
    {
        //function edit($id, $tvar){
        //if(isset($_POST['dogid'])){
        if (isset($_POST['submit'])) {
            if (!isset($_SESSION['token'])) {
                $_SESSION['token'] = md5(uniqid(rand(), TRUE));
            }
            if ($_POST['token'] != $_SESSION['token']) {
                Url::redirect('admin/login');
            }

            //echo "submit is set";
            $dogpic = Cln::fixValue($_POST['dogpic']);
            $dogid = $_POST['dogid'];
            $dogname = Cln::fixValue($_POST['dogname']);
            $sex = ucfirst($_POST['sex']);
            $comments = Cln::fixValue($_POST['comments']);
            $adopted = (isset($_POST['adopted']) == '1' ? '1' : '0'); ///added 
            //$adopted = $_POST['adopted']; ///added
            //$ocheck = (isset($_POST['ocheck']) == '1' ? '1' : '0'); ///added
            $lastedit = date("Y-m-d H:i:s");
            echo $adopted;
            if (!isset($error)) {
                $postdata = array(
                    'dogpic' => $dogpic,
                    'dogname' => $dogname,
                    'sex' => $sex,
                    'comments' => $comments,
                    'adopted' => $adopted,
                    'lastedit' => $lastedit
                );
                $where = array('dogid' => $dogid);
                $this->Dog->update($postdata, $where);



                /* $postdata = array(
                  'firstName' => $firstName,
                  'lastName' => $lastName
                  );
                  $where = array('id' => $id);
                  $this->_dog->update($postdata, $where); */
                //Session::set('dogpage'
                //Url::redirect('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
                return Redirect::to('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
                //dog?page=2&psch=b
                //$_SESSION['dogsearch']
                //$_SESSION['dogpage'] 
            }
        }

        //$data['title'] = 'Edit';
        $dogid = $_REQUEST['dogid'];
        //$dogid = $id;
        "zzz===" . $dogid . "===zzz";
        $data['row'] = $this->Dog->getDog($dogid);
        //View::owner = $this->_dog->get_dog($id);
        //$data = $this->_dog->get_dog($id);
        //View::renderTemplate('edithd',$data);
        View::renderTemplate('edithd', $data);
        View::render('dog/edit', $data);
        //View::render('dog/edit', $data, $error);
        //View::render('dog/edit',$data,false,$error);
        View::renderTemplate('editft', $data);
    }

```

**Comment by LuckyCyborg** [comment]
You have a style to write code...
Only you can follow it, someone else no.

But the **Redirect::to()** looks good as command.

To figure you about what is it, think that **Redirect::to()** behave exactly like in Laravel.

**Comment by LuckyCyborg** [comment]
@jimgwhit BTW, you use somewhere there in Controller, **Url::redirect()** ?

You updated **Helpers\Url** ?

**Comment by jimgwhit** [comment]
@LuckyCyborg  Is the session correct like
```
Session::get('dogpage')
```
and
```
Session::set('dogsearch', $dogsearch);

```
I changed that to
```
if (!isset($_SESSION['token'])) {
                $_SESSION['token'] = md5(uniqid(rand(), TRUE));
            }
            if ($_POST['token'] != $_SESSION['token']) {
                return Redirect::to('admin/login');
            }
```

**Comment by LuckyCyborg** [comment]
Session::set() and Session::get() are perfect

For deleting a variable use: Session::forget()
Instead of Session::pull() : Session::remove()

**Comment by LuckyCyborg** [comment]
I made:

```php
return Redirect::to('dashboard?p=' . 5 . '&psch=' . 'dog' . '&aval=' . 666);
```
And go perfectly to.

**Comment by LuckyCyborg** [comment]
Oh, and a important thing: new Session API do not touch $_SESSION, use a internal store.

Be warned to not expect to see values from Session to $_SESSION

**Comment by jimgwhit** [comment]
not using $_SESSION was commented

**Comment by jimgwhit** [comment]
main error seems to be
```
Message: The HTTP status code is not a redirect ("200" given).
```

**Comment by LuckyCyborg** [comment]
Because the second parameter for Redirect::to() should be a redirect code and it have 200

Then, somewhere you have an Url::redirect() with the third param 200 or a Redirect::to() with the second param 200

**Comment by LuckyCyborg** [comment]
My bet is in the first variant: You have somewhere an **Url::redirect()** with third param with value **200**

**Comment by jimgwhit** [comment]
now getting Message: Please configure the ENCRYPT_KEY.

           Code: 0

           File: C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\nova\system\Support\Facades\Crypt.php

           Line: 40

**Comment by jimgwhit** [comment]
the instructions show
```
Also, there is introduced a new class, called Core\Redirect, built on top of Core\Response, which permit in Route Filters or Controller Methods commands like:
// Create a Redirect Response to a location within the application
return Redirect::to('user/profile');

```
This is your instructions in the PR, am I suppose to add a , 200

**Comment by LuckyCyborg** [comment]
@jimgwhit And guess what is it? It said clear, right?

**Comment by jimgwhit** [comment]
where do I and how do I configure ENCRYPT_KEY

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> This is your instructions in the PR, am I suppose to add a , 200

Well, after we big PR, we passed at **Symfony's HTTP Foundation** based Response APi, which is more strict.

> where do I and how do I configure ENCRYPT_KEY

Where it could be?

**Comment by jimgwhit** [comment]
I see in config define('ENCRYPT_KEY', ''); but is that optional?

**Comment by jimgwhit** [comment]
so I need to add a comma 200 like , 200

**Comment by LuckyCyborg** [comment]
You should configure it, if you use Cookies.

And you should do **not** add 200! It is **302** for redirect

**Comment by Kingorgg** [comment]
@jimgwhit 
> where do I and how do I configure ENCRYPT_KEY

in your console use `php nova make:key` and that will generate an Encrypt key for you, if the define is empty.

**Comment by LuckyCyborg** [comment]
And there you should do not add a code 200, or whatever.

See:

```php
    /**
     * Create a new redirect response to the given path.
     *
     * @param  string  $path
     * @param  int     $status
     * @param  array   $headers
     * @param  bool    $secure
     * @return \Http\RedirectResponse
     */
    public function to($path, $status = 302, $headers = array(), $secure = null)
```

**Comment by jimgwhit** [comment]
I defined ENCRYPT_KEY, now a redirect is working with
```
return Redirect::to('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
```
Thanks both of you, oh I had old redirect renamed redirect_bak, I guess autoload did not like that, I deleted, redumped autoload, all seems good. Sorry I was mad earlier. And @Kingorgg you have been nothing but good to me.  How do you stay up on all these PR's?

**Comment by jimgwhit** [comment]
@Kingorgg and @LuckyCyborg I spoke to soon. I am not getting an error, but say I was on page 4 when I did an edit, the redirect is not returning to page 4 instead, page one.

**Comment by LuckyCyborg** [comment]
That's not **Redirect::to()** fault. You have something in code to adapt.

**Comment by jimgwhit** [comment]
the old Url::redirect would work, am I doing the session wrong, please refer me again to new session instructions.

**Comment by LuckyCyborg** [comment]
**Session::get()** and **Session::set()** are as you know

verify if you have a Cookie called **nova_session**

**Comment by jimgwhit** [comment]
I usually don't use cookies, what is code to check that?

**Comment by LuckyCyborg** [comment]
Look in browser

**Comment by jimgwhit** [comment]
I do not know where, but in my edit view I put
```
                $spage = Support\Facades\Session::get('dogpage');
                $spsch = Support\Facades\Session::get('dogsearch');
                $aval = Support\Facades\Session::get('dogaval');
```
But still returning to page 1

**Comment by LuckyCyborg** [comment]
Like I said, I tested with:

```php
return Redirect::to('dashboard?p=' . 5 . '&psch=' . 'dog' . '&aval=' . 666);
```

and the redirection is perfect.

var_dump that variables $spage, $spsch and $aval to see if they are correct

In other hand, I suggest you to prepare a fresh new site for test and to play with the new Session API, to know better it.

**Comment by jimgwhit** [comment]
It seems that nothing is storing in sessions. what is the .666

**Comment by LuckyCyborg** [comment]
Whatever number

**Comment by LuckyCyborg** [comment]
Please look on **app/Storage/Sessions** . there are some files. some or a big number?

**Comment by LuckyCyborg** [comment]
Jim, out of curiosity, your Controllers are custom or they extends Core\Controller? 

Also, you cancelled something from Core\Controller?

**Comment by jimgwhit** [comment]
@LuckyCyborg 
```
class Dog extends Controller
```
I did a fresh install, redownloaded, unzipped, and composer install.  Same thing, I can paginate records, goto edit page, edit, it saves changes, but sessions are empty.

**Comment by jimgwhit** [comment]
In the welcome controller you still have 
```
<?php
/**
 * Welcome controller
 *
 * @author David Carr - dave@novaframework.com
 * @version 3.0
 */

namespace App\Controllers;

use Core\View;
use Core\Controller;
use Helpers\Session;  //FROM FRAME, NOT ME

use Request;

/**
 * Sample controller showing a construct and 2 methods and their typical usage.
 */
class Welcome extends Controller
{
    /**
     * Call the parent construct
     */
    public function __construct()
    {
        parent::__construct();

        // Load the Language file.
        $this->language->load('Welcome');
    }

    /**
     * Define Index page title and load template files.
     */
    public function index()
    {
        $data['title'] = $this->language->get('welcomeText');
        $data['welcomeMessage'] = $this->language->get('welcomeMessage');

        View::renderTemplate('header', $data);
        View::render('Welcome/Welcome', $data);
        View::renderTemplate('footer', $data);
    }

    /**
     * The New Style Rendering - create and return a proper View instance.
     */
    public function subPage()
    {
        return View::make('Welcome/SubPage')
            ->shares('title', $this->trans('subpageText'))
            ->withWelcomeMessage($this->trans('subpageMessage'));
    }
}

```

**Comment by jimgwhit** [comment]
I tryed changing back to
```
use Helpers\Session as Session;
```
and all works, so why isn't the
```
Support\Facades\Session
```
working?
The new return Redirect::to works fine.

**Comment by jimgwhit** [comment]
@LuckyCyborg any idea, also see two previous comments.

**Comment by LuckyCyborg** [comment]
@jimgwhit To have a functional Session Storage you should use only the new APIs (excluding the Database) and to have the **Encryption** properly set.

Then, about ENCRYPT_KEY, OpenSSL extension loaded, etc.

See that Session Storage save files on directory **app/Storage/Session**, a hint about its proper work is if you clean cookies on Web-Browser, remove all **see_\*** files from that folder and refresh the page.

Should appear two cookies: **PHPSESSID** and **nova_session**, and in the storage folder should appear two files too.

That's all for first.

**Comment by jimgwhit** [comment]
@LuckyCyborg I have ENCRYPT_KEY set, but what about OpenSSL, I use wamp for development, I have no idea how to implement open ssl on a wamp/xamp type install. Are you saying all users who develop on wamp are out of luck?  
Is this going to be a linux only framework for development?

**Comment by LuckyCyborg** [comment]
You should have OpenSSL extension, just read the documentation of WAMP. 

If it not have this extension, there are another LAMP stacks for Windows.

**Comment by jimgwhit** [comment]
@LuckyCyborg I have it, I figured out that sessions work in controller, but I can't get them working in a view.   
This works in controller
```
$spage = Support\Facades\Session::get('dogpage');
```
But not in a view. I tryed with and without a use statement in view, any ideas?

**Comment by LuckyCyborg** [comment]
That should not happen. You are sure that you do not have 'use' for another Session class?

I will test this way. So, we have a presumptive problem in calling the Session (Storage) in View files, to understand right?

**Comment by jimgwhit** [comment]
@LuckyCyborg I even commented out use
```
//use \Support\Facades\Session as Session;
```
and call direct:
```
$spage = Support\Facades\Session::get('dogpage');
```
even tryed extra slash in view
```
$spage = \Support\Facades\Session::get('dogpage');
```

**Comment by LuckyCyborg** [comment]
OK. Thanks for reporting. I will look for this night.

So, that Big Mouth Jim can be also useful for Project, doing hardcore testing... :+1:

**Comment by LuckyCyborg** [comment]
@jimgwhit I test test as following:

I added on **App\Modules\Users\Controllers\Users\@profile** :
```php
Session::set('the_test', 'this is a test!!!');
```
And into **app/Modules/Users/Views/Users/Dashboard.php** : 
```
<?= Session::get('the_test'); ?>
```

And the things works fine, the message appear on Dashobard after visiting the Profile.

Sorry, but I can't confirm your problem.

**Comment by jimgwhit** [comment]
@LuckyCyborg  I use custom headers is there a line of code in a header that is required for it to work?

**Comment by LuckyCyborg** [comment]
All you have is to manage to not kill the framework in middle of nowhere, and leave it to do its flow.

**Comment by jimgwhit** [comment]
@LuckyCyborg after more test, I have a controller method indexadmin at top of the Indexadmin view I can put
```
<?php echo "page ".Session::get('dogpage'); ?>
```
That works.  
But if I click on an edit link and open the dog for an edit, which is named Edit in view and try same
```
<?php echo "page ".Session::get('dogpage'); ?>
```
It don't work.  Are you sure Sessions are persisting across views, please test more. It is only working in a view with same name as controller method, Or first view only.

**Comment by LuckyCyborg** [comment]
>  Are you sure Sessions are persisting across views

Yes, I tested that today, setting a variable in Profile page and showing it in Dashboard page.

**Comment by jimgwhit** [comment]
@LuckyCyborg you set and echoed, but you didn't render another view and see if it persisted. I can get it to echo out in the first called view like you, but not another view.

**Comment by LuckyCyborg** [comment]
You tested the Users from Nova? Of course not.

I set the variable in one page, then I loaded another page, where it was present. 

The variables are sent from a page to another.

**Comment by jimgwhit** [comment]
@LuckyCyborg I can do what you did, that is not the issue, sessions are not persisting.  If you set a session in a controller method, try to use that in ANOTHER method, it is not there. It gets set, and is there for the first view called only, then it disapears.
Set one in a crud operation, click edit to edit a record, have a session stored to return where you left off at, very common pratice, the session is not there. It will be on the first view you load after setting it, but if you route to another method / view, it's gone. It should persist across any views / methods.

**Comment by daveismyname** [comment]
I can confirm there is a problem. 

take this, a tiny controller:

````
<?php
namespace App\Controllers;

use Core\Controller;
use Core\View;
use Session;

class Dave extends Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        Session::set('intro', 'hello Dave!!');

        pr(Session::all());
    }
}
````

a session called intro is created the output of the page:

````
Array
(
    [_token] => 6tiKBMgHRWVtYvhVBaiCSYGkt7y9FtbZyZVu8oRsqU2K3rhpEqAdrTaEbtlBvtikMfFRTz706KXtew6Luw1CprgWrb9nvbv1kUsBVSEx6HgRLb9km16daByzZkZBK5vI
    [flash] => Array
        (
            [old] => Array
                (
                )

            [new] => Array
                (
                )

        )

    [language] => en
    [intro] => hello Dave!!
)
````

all expected to this point.

Now in a view not linked to this controller the subpage view of welcome:

````
<?php use Session as Session;?>

<div class="page-header">
	<h1><?=$title;?></h1>
</div>

<p><?=$welcomeMessage;?></p>

<?php
echo Session::get('intro');
pr(Session::all());
?>

<a class="btn btn-md btn-success" href="<?=DIR;?>">
	<?php echo Language::show('backHome', 'Welcome'); ?>
</a>
````

I've used a 'use' to be explicit. the output:

````
Subpage
Hello, welcome from the welcome controller and subpage method! 
This content can be changed in /app/Views/Welcome/SubPage.php

Array
(
    [_token] => 6tiKBMgHRWVtYvhVBaiCSYGkt7y9FtbZyZVu8oRsqU2K3rhpEqAdrTaEbtlBvtikMfFRTz706KXtew6Luw1CprgWrb9nvbv1kUsBVSEx6HgRLb9km16daByzZkZBK5vI
    [flash] => Array
        (
            [old] => Array
                (
                )

            [new] => Array
                (
                )

        )

    [language] => en
)
````

it's missing  [intro] => hello Dave!!

now I so change the code to use Helpers\Session it then works as expected.

**Comment by jimgwhit** [comment]
@daveismyname thanks for helping test.  I often update a record, and use sessions to return to a page I left off on like
```
$spage = Session::get('dogpage');
$spsch = Session::get('dogsearch');
$aval = Session::get('dogaval');
echo "<a href=" . DIR . "dog/indexadmin?p=" . $spage . "&psch=" . $spsch . "&aval=" . $aval . ">Back to List</a>";
```
So if I edited from page 32, I can return to page 32, with same search criteria, etc.

**Comment by daveismyname** [comment]
> So, that Big Mouth Jim can be also useful man for/on Project, doing hardcore testing... 👍

come on being respectful works both ways. Leave out the insults that applies to us all.

**Comment by jimgwhit** [comment]
You have to admit even lucky got mean with you once, but I apolozied for the other PR.

**Comment by jimgwhit** [comment]
Hey me and lucky have a love hate thing going.

**Comment by daveismyname** [comment]
Yes, if we all avoid the insults then there is never an issue. At the end of the way we're all trying to build stuff so lets concentrate on that.

**Comment by jimgwhit** [comment]
@daveismyname you are right, but let's add some humor at times.

**Comment by daveismyname** [comment]
Agreed.

So as it stands the Helpers\Session is persistent but the facade Session has a problem. As illustrated above.

**Comment by jimgwhit** [comment]
I have dug around in there that is that sympony stuff, yikes, hopefully lucky will fix it if he ain't mad at me again, just kidding.

**Comment by LuckyCyborg** [comment]
Interesting. I will look for this problem... 

BTW, the Facade is just its facade, the worker is **Session\Store**.

**Comment by jimgwhit** [comment]
@LuckyCyborg said
> the Facade is just its facade, the worker is Session\Store  
I am a database guy, that comment is forign language to me.  I bet Dave understands it, maybe.

**Comment by daveismyname** [comment]
Basically it's a shortcut a way to call classes statically that are not static to begin with.

**Comment by jimgwhit** [comment]
No way to call the get and set in store direct I bet. Like in the helper one.

**Comment by jimgwhit** [comment]
Lucky is playing with us, he already has it figured out I bet.

**Comment by LuckyCyborg** [comment]
Look there. i set a variable on **App\Controllers\Demo@index** and made a redirect to **subpage**, aka **App\Controllers\Welcome@subPage**. which is modified to dump Session on Controller's Method and associated View. Works perfect.

![snapshot7](https://cloud.githubusercontent.com/assets/13488485/15590257/1a2621ec-2397-11e6-8019-878c86fee81b.png)

**Comment by daveismyname** [comment]
Share your code so we can test that exact setup.

**Comment by LuckyCyborg** [comment]
I commited the current tree, with the Session test too, if you want to look into, is in my fork

**Comment by LuckyCyborg** [comment]
When you call **/demo/test** you have a redirect to subpage

**Comment by LuckyCyborg** [comment]
```php
    public function index()
    {
        echo 'hello';

        Session::set('the_test', 'this is a test!!!');

        return Redirect::to('subpage');
    }
```
```php
    /**
     * The New Style Rendering - create and return a proper View instance.
     */
    public function subPage()
    {
        echo '<pre>' .var_export(Session::all(), true) .'</pre>';

        return View::make('Welcome/SubPage')
            ->shares('title', $this->trans('subpageText'))
            ->withWelcomeMessage($this->trans('subpageMessage'));
    }
```
```php
<div class="page-header">
	<h1><?=$title;?></h1>
</div>

<pre>'<?= var_export(Session::all(), true); ?></pre>

<p><?=$welcomeMessage;?></p>

<a class="btn btn-md btn-success" href="<?=DIR;?>">
	<?php echo Language::show('backHome', 'Welcome'); ?>
</a>
```

```php
Router::any('demo/test',            'App\Controllers\Demo@index');
```

**Comment by jimgwhit** [comment]
Yes but @LuckyCyborg sessions are gone after the first use, goto another page / controller and try to echo the session.

**Comment by LuckyCyborg** [comment]
I made ten times refresh/reload of page. The Session dump is preserved.

**Comment by LuckyCyborg** [comment]
Also, there is the Users private area, and how the user stay logged-in, it is very clear demo for Session data preservation, because it use Session\Store.

**Comment by daveismyname** [comment]
ok I tested my class and went to the view I've found that having the return Redirect in place does preserve what's been entered **BUT** if I take out the redirect and set a session then manually go to subpage it does not save.

Does the new Session relay on middleware?

**Comment by jimgwhit** [comment]
No @LuckyCyborg make another controller, and another method, try echoing that same session var, it won't be there. Of course it's there refreshing same page. It should persist if you use 5 controllers and 5 views across all of them.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> Does the new Session relay on middleware?

Yes. It works only on new Style APIs, when the Middleware receive a View, Template, Response or Redirect instance.

**Comment by LuckyCyborg** [comment]
Oh, now i understand! 

You, Jim, you use the triplets rendering. Then you return nothing from Action. 

That's why Session Store doesn't work in your case.

**Comment by jimgwhit** [comment]
@LuckyCyborg I render the edit view regular way
```
        View::renderTemplate('edithd', $data);
        View::render('dog/edit', $data);
        View::renderTemplate('editft', $data);
```
If that won't work, how do I do it right?

**Comment by daveismyname** [comment]
OK so that's the problem, so in cases where the new api is not being used best to use the Helpers\Session.

**Comment by jimgwhit** [comment]
@daveismyname will the Helpers\Session remain in the framework? That is why I am trying to learn the new stuff, for fear that some things will be removed.

**Comment by LuckyCyborg** [comment]
@daveismyname Yes, this is not a problem, is just a consequence of using different API mixed, when the classic triplet rendering is used, the best way is to use the **Helpers\Session**.

**Comment by daveismyname** [comment]
Good to know had me worried there!

Him Yes is will not be going anywhere. Backward compat is a must.

**Comment by jimgwhit** [comment]
@LuckyCyborg can you show me a quick refresher on how to render same with new api.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

The new style is presented by Welcome@subPage
```php
    /**
     * The New Style Rendering - create and return a proper View instance.
     */
    public function subPage()
    {
        echo '<pre>' .var_export(Session::all(), true) .'</pre>';

        return View::make('Welcome/SubPage')
            ->shares('title', $this->trans('subpageText'))
            ->withWelcomeMessage($this->trans('subpageMessage'));
    }
```

**Comment by jimgwhit** [comment]
I will test more and create a new issue if needed.

**Comment by jimgwhit** [comment]
Thanks both of you.

**Comment by LuckyCyborg** [comment]
OK, there we are... :+1:

**Comment by LuckyCyborg** [comment]
See that the Users Module also use the new API.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, Dave...

There is a way to arrive to a Response processing when using the triplet rendering:

After all, every View::renderX command generate a View or Template instance and render it.

**IF**, instead of directly rendering them, I will make the Core\View to store those instances in a stack, the Middleware can be instructed that the instances stack is not empty, then fetch them one by one and build a Response instance, then make Session Storage and other things to works even in this case.

To make that, there is no API change and another visible change for end-user, just how the framework works.

If you agree for, I can start to make this Design after I finish with the ORM...
I

**Comment by jimgwhit** [comment]
@LuckyCyborg would you really do that for us?
