### ISSUE TITLE
i will upgrade language system in nova

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#892]
this my sample . it can change route with language code
[http://nasr.webineh.net
](url)
this routing with code is very better use cooke 

it is very power seo anf use hreflang for each language in meta tags

this idea use in laravel

https://github.com/mcamara/laravel-localization

**Comment by amiroperator** [comment]
@vahidalvandi You can make a PR and if @daveismyname accepted it, changes will be merged

**Comment by LuckyCyborg** [comment]
@vahidalvandi To note that Nova Framwork do not sports a Laravel-style localization.

AND, we, the developers, we already discussed and established that to make Language aware the Routing is beyond the target audience of the Nova Framework version 3.

Good for you that you made it, eventually share it, but it will not arrive on Nova by default.

All the best.

**Comment by geomorillo** [comment]
Sure thing.. :+1:

**Comment by vahidalvandi** [comment]
this is a nice option for any language routing in cms and content for google and other serach engines

**Comment by LuckyCyborg** [comment]
Sure, in a **CMS**, but Nova is **NOT** a CMS!

Nova Framework is a Framework, and eventually the end-user would write a CMS on top of it.

**Comment by vahidalvandi** [comment]
yes.. but nova core dont suport lang code after each link 

like =

site.com    = default
site.com/en = language 1
site.com/es = language 2

site.com/es/blog  = language 2 blog page

nova should suport language code

**Comment by LuckyCyborg** [comment]
@vahidalvandi Again, that should be resolved on application part, by the end-user/developer, and he have the required tools.

What you do not understand? **NOVA IS NOT A CMS!**

**Comment by vahidalvandi** [comment]
yes..
in end user we add route like 

(:any)=>controler/test@home   =>>>>this route home with code like === site.com/en

we dont need add lang code in default language ... :+1: 

how i can route one controller with one function for default language and other language...

so , (:any) can get any character i smvc 2.2 i add one pattern in core router (:lang) after user this patternm , just give 2 char not number and any size of input,,,

is nova should add a new pattern with (:lang) to just input 2 character code

**Comment by LuckyCyborg** [comment]
@vahidalvandi 

> is nova should add a new pattern with (:lang) to just input 2 character code 

Under Nova Framework, you can configure the Routing Patterns, in its configuration.

**Comment by vahidalvandi** [comment]
where is the configuration ??

nova\system\Core\Route.php   ???

i cant find any config!!

**Comment by Kingorgg** [comment]
@vahidalvandi **app/Config/Routing.php**

**Comment by vahidalvandi** [comment]
Nope!

false...

**Comment by daveismyname** [comment]
https://github.com/nova-framework/framework/blob/master/app/Config/Routing.php in there is 

````
Config::set('routing', array(
    'patterns' => array(
        //':hex'    => '[[:xdigit:]]+',
        //':uuidV4' => '\w{8}-\w{4}-\w{4}-\w{4}-\w{12}'
    ),
    'default' => array(
        'controller' => DEFAULT_CONTROLLER,
        'method'     => DEFAULT_METHOD
    )
));
````

What's false about that?

**Comment by vahidalvandi** [comment]
thanks :+1: :+1: 

in nova how i can detect one controller call with which one

cms/home=>>controller@home
cms/main ==>controller@home

----
i need Detects to which one route called?

**Comment by LuckyCyborg** [comment]
@daveismyname He use probably a old version of Nova.

**Comment by LuckyCyborg** [comment]
@vahidalvandi You can obtain the matched Route instance on Controllers via
```php
$route = Router::matchedRoute();
```

**Comment by vahidalvandi** [comment]
please take a sample 

$route = Router::matchedRoute();

**Comment by LuckyCyborg** [comment]
@vahidalvandi To make a "sample" I should first to understand what you want.

**Comment by vahidalvandi** [comment]
please description how it work 

`$route = Router::matchedRoute();
`
no need make sample..

**Comment by LuckyCyborg** [comment]
In a Controller, while executing it, you can retrieve the matched by Routing **Route** instance with this method.

Do a **var_dump** and see which contains the **$route**

**Comment by vahidalvandi** [comment]
i can use $route = Router::matchedRoute(); in controller and show refrence ??

**Comment by LuckyCyborg** [comment]
You can obtain this way all the information about Route which are know by Framework.

**Comment by vahidalvandi** [comment]
i will test it.

very thanks.

**Comment by vahidalvandi** [comment]
use Routing\Router;

for use $route = Router::matchedRoute();  we must call it in controller ?
