### ISSUE TITLE
Bindings followup issue #893

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#894]
@LuckyCyborg Right from php manual your link.
~~~
Execute the prepared statement. If the prepared statement included parameter markers, you must either:

call PDOStatement::bindParam() and/or PDOStatement::bindValue() to bind either variables or values (respectively) to the parameter markers. Bound variables pass their value as input and receive the output value, if any, of their associated parameter markers
~~~
The new api is not secure without proper bindings. You may be good programmer but I know my database stuff. Do not delete this until issue is addressed.  

from manual, proper secure binding
~~~
<?php
/* Execute a prepared statement by binding PHP variables */
$calories = 150;
$colour = 'red';
$sth = $dbh->prepare('SELECT name, colour, calories
    FROM fruit
    WHERE calories < :calories AND colour = :colour');
$sth->bindValue(':calories', $calories, PDO::PARAM_INT);
$sth->bindValue(':colour', $colour, PDO::PARAM_STR);
$sth->execute();
?>
~~~
You prepare then bind.

**Comment by LuckyCyborg** [comment]
@jimgwhit You Jim, you consider that **you are better programmer than me** or those who develop CodeIgniter, CakePHP or Laravel?

In Database API you should go with QueryBuilder or Models for processing. Connection API do not offer other facilities that safe executing SQL commands.
