### ISSUE TITLE
Reporting someone who closes issue without addressing.

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#895]
@LuckyCyborg I have already reported the problem to Dave. You have made a very unsafe and unsecured API without proper bindings you can delete my issue all day long but I will investigate how to turn this over to the gitHub folks.  Issue #893 and #894 need fixed.   
A prepare only without follow-up bindings is nowhere near as secure. And you should know that now quit being stubborn and fix the issue properly. And I am not playing games here. There is no way I can use that junk you wrote unsecurly.  
And I really feel the community needs to be warned about proper security in a database management system. You started this nastiness in other issue I tried to be nice I realize we both have tempers so please calm down and fix the issue.  
It would probably only take you a few minutes to fix anyway.

**Comment by LuckyCyborg** [comment]
Please stop playing with my time. There are no issues, just the lack of knowledge from your part.

Is not my fault that you are unable to assimilate basic elements of knowledge.

All the best!
