### ISSUE TITLE
If statement not finished

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#896]
@daveismyname  and @LuckyCyborg you have
~~~
public function prepareBindings(array $bindings)
    {
        foreach ($bindings as $key => $value) {
            if ($value instanceof DateTime) {
                // We need to transform all DateTime instances into an actual date string.
                $bindings[$key] = $value->format($this->getDateFormat());
            } else if ($value === false) {
                $bindings[$key] = 0;
            }
        }
        return $bindings;
    }
~~~
If construct never finished and proper bindings were never implemented.  
This new api is not secure. This is very dangerous to use in a production environment.

**Comment by LuckyCyborg** [comment]
So, amaze me, what is it the difference from what we use us and Laravel **5.2.27** ?
```php
    /**
     * Prepare the query bindings for execution.
     *
     * @param  array  $bindings
     * @return array
     */
    public function prepareBindings(array $bindings)
    {
        $grammar = $this->getQueryGrammar();

        foreach ($bindings as $key => $value) {
            // We need to transform all instances of DateTimeInterface into the actual
            // date string. Each query grammar maintains its own date string format
            // so we'll just ask the grammar for the format to get from the date.
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = $value->format($grammar->getDateFormat());
            } elseif ($value === false) {
                $bindings[$key] = 0;
            } 
        }

        return $bindings;
    } 
```
See? Even the **Laravel 5.2.x** do not use what you expect...

And how Laravel have about of 10000 active programmers, you believe that you are smarter than me, bu also than them?

You do not believe that if if was true, someone observed long time ago?

**Comment by jimgwhit** [comment]
@LuckyCyborg I told you I stopped using laravel. Have you been on the Laravel  forums 9,999 of them are idiots, read some of the post. Most of them folks seem to only like the latest fad. My only concern is secure database management. And as far as that goes I was programming before Taylor Otwell was even born. Or he may have been a little baby at the time.

**Comment by LuckyCyborg** [comment]
@jimgwhit Stop with the words and please demonstrate your claims!

Laravel is about 10000 programmers beyond of **Taylor Otwellt**, right now. 

You believe that you smarter than all of them?

For your knowledge, everything on **Database\Connection** is bind as **string**, because there is not a need for more. 

Is it supposed to use the **QueryBuilder** or a **Model**, which generate well designed and escaped SQL commands.

**Comment by jimgwhit** [comment]
@LuckyCyborg on tablet now, look into more tomorrow. But answer, how are the parameters being bound now? I don't see binding anywhere.

**Comment by LuckyCyborg** [comment]
@jimgwhit You really read my responses, you tard?

I given you already examples, you can't figure yet that they are bind on **execute()** ?

# SEE THERE: http://php.net/manual/en/pdostatement.execute.php

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> I go on that forum sometimes just for they entertainment value.

Maybe in a huge community like that of Laravel, the joke works, but in our little community...

Oh well, I guarantee you that for me you have **no entertainment value** value, after all. :smirk:
