### ISSUE TITLE
New database API working great, just test results here.

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#901]
@LuckyCyborg remember the other night you helped me get going on the new database api.  
All worked perfect including pagination, however after PR through 899 the first page shows up, however no pagination links. I get one page of records only.

**Comment by LuckyCyborg** [comment]
@jimgwhit

You talk about **Helpers\Paginator** ?

It wasn't touched from Ice Age, look on code, you messed something up.

**Comment by jimgwhit** [comment]
@LuckyCyborg yes Helpers\Paginator, The other night all worked PERFECT. All I did today is update all through pr 899. When it worked is was prior to pr 890, when you told me about use DB.

**Comment by LuckyCyborg** [comment]
The you made the update right, maybe...

I know that you have a personal style on updating

**Comment by jimgwhit** [comment]
@LuckyCyborg my url is
```
http://localhost/nova/dogeq/indexadmin
```
if I manually type in
```
http://localhost/nova/dogeq/indexadmin?p=2
```
It goes to page 2, just no pagination links showing.  
And I did a composer update, and a dump autoload.

**Comment by LuckyCyborg** [comment]
There should not be problems on #899 because nothing is changed in logic of Database API, is just support for SQLite and PostgresSQL add.

You missed something on update, maybe...

**Comment by jimgwhit** [comment]
Let me sho my controller and model code:
controller
```
<?php

namespace App\Controllers;

use Core\Controller;
use Core\View;
use Core\Template;
use Helpers\Csrf;
use Helpers\Password;
use Helpers\Url;
use Auth;
use Redirect;
use Request;
use Session;
use Input;
use Helpers\Paginator as HelpersPaginator;
use App\Models\DogeqModel;
use DB;
class Dogeq extends Controller
{

    private $Dogeq;

    public function __construct()
    {
        parent::__construct();
        $this->Dogeq = new \App\Models\DogeqModel();
    }

    public function indexAdmin()
    {

        $dogsearch = (isset($_REQUEST['psch']) <> '' ? $_REQUEST['psch'] : "");
        $aval = (isset($_REQUEST['aval']) <> '' ? $_REQUEST['aval'] : "");
        Session::set('dogsearch', $dogsearch);
        Session::set('dogaval', $aval);
        //$dogsearch = $dogsearch . "%";
        $dogrows = DB::table('dogs')->where('dogname', 'like', $dogsearch)->count();
        Session::set('dogrows', $dogrows);
        $pages = new HelpersPaginator('5', 'p');
        Session::set('dogpage', $pages->getInstance());
        $pages->setTotal($dogrows);
        $data['pageLinks'] = $pages->pageLinks();$data['dogs'] = $this->Dogeq->getDogsadmin($pages->getLimit2(), $pages->getPerpage(), $dogsearch, $aval);
        
        $data['content'] = View::make('Dogeq/Indexadmin')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
        return Template::make('dogtmpl', $data);

    }
```
model
```
<?php

namespace App\Models;

use Database\Model as BaseModel;
use DB;

class DogeqModel extends BaseModel
{
    protected $table = 'dc_dogs';
    protected $primaryKey = 'dogid';
    public function __construct()
    {
        parent::__construct();
        
    }
    
    public function dogCountadmin($dogsearch = "", $aval = "")
    {
        $dogsearch = $dogsearch . "%";
        if ($aval == "n") {
            $result = $this->db->select('SELECT COUNT(dogid) as total FROM ' . PREFIX . 'dogs WHERE dogname LIKE :search and adopted = 1', array('search' => $dogsearch));
        }
        if ($aval == "y") {
            $result = $this->db->select('SELECT COUNT(dogid) as total FROM ' . PREFIX . 'dogs WHERE dogname LIKE :search and adopted = 0', array('search' => $dogsearch));
        }
        if ($aval == "") {
            $result = $this->db->select('SELECT COUNT(dogid) as total FROM ' . PREFIX . 'dogs WHERE dogname LIKE :search', array('search' => $dogsearch));
        }
        return $result[0]->total;
    }
    
    public function getDogsadmin($offset = "", $rowsperpage = "", $dogsearch = "", $aval = "")
    {
        $pagingQuery = "LIMIT {$offset}, {$rowsperpage}";
        $dogsearch = $dogsearch . "%";
        if ($aval == "n") {
            return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search and adopted = 1 ORDER BY lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }
        if ($aval == "y") {
            return  DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search and adopted = 0 ORDER BY sex, lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }

        if ($aval == "") {
            return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search ORDER BY lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }
        //return $this->db->select("SELECT * FROM ".PREFIX."dogs WHERE dogname LIKE :search and adopted = :adopted ORDER BY adopted, sex, dogname " . $pagingQuery,
        //array('search' => $dogsearch));							
    }
    
}

```

**Comment by jimgwhit** [comment]
@LuckyCyborg I got it I commented out the count line by mistake, sorry.

**Comment by LuckyCyborg** [comment]
And this model of yours works fine with all those selects?

**Comment by jimgwhit** [comment]
@LuckyCyborg ok that works, now I want to use the new session api with original database helper and triplet, can you give example, or does the original database helper work exactly as is with no changes?  
To above, yes, even laravel  has database, querybuilder, and orm, for that simple stuff I use database.  
see
```
public function getDogsadmin($offset = "", $rowsperpage = "", $dogsearch = "", $aval = "")
    {
        $pagingQuery = "LIMIT {$offset}, {$rowsperpage}";
        $dogsearch = $dogsearch . "%";
        if ($aval == "n") {
            return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search and adopted = 1 ORDER BY lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }
        if ($aval == "y") {
            return  DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search and adopted = 0 ORDER BY sex, lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }

        if ($aval == "") {
            return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search ORDER BY lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
        }
        							
    }
```
Only one select depending on search

**Comment by jimgwhit** [comment]
@LuckyCyborg exach same as original database helper just had to change
```
$this->db->select
```
to
```
DB::select
```

**Comment by LuckyCyborg** [comment]
@jimgwhit But to remember that Database\Connection is not the Illuminate one and there the things are simplified.

Facts are that all bind parameters  give are treated as **PDO::PARAM_STR**, that would not work on **LIMIT** and **OFFSET**, where  you should transform literally the values in integers and include directly on Query String.

That's not a security issue because always you will give a integer, with whatever value.

This is way the Database API can work fine without explicit binding the params.

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous 2 comments also,  
I'll be a blank blank, I just tryed the new session api with original database helper and the triplet combination, guess what?  
# Hey it works. 
I did not have to make no config changes to use original database helper and new database api in same app, but separate controller and model.

**Comment by jimgwhit** [comment]
@LuckyCyborg you said
> Facts are that all bind parameters give are treated as PDO::PARAM_STR, that would not work on LIMIT and OFFSET, where you should transform literally the values in integers and include directly on Query String.

Give example, pagination is working.

**Comment by LuckyCyborg** [comment]
Come on! What example you want for converting a variable to integer and adding it to a string?

Fact are that would not work:
```
LIMIT :limit OFFSET :offset
```

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous, I am doing this:
```
$pagingQuery = "LIMIT {$offset}, {$rowsperpage}";
```
And in query I
```
return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search ORDER BY lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
```
I don't pass {$offset} and {$rowsperpage} as parameters, that is just taked on at end.

**Comment by LuckyCyborg** [comment]
:+1:

**Comment by jimgwhit** [comment]
@LuckyCyborg , so there is no problem with the way I do it?

**Comment by LuckyCyborg** [comment]
I perfect, just ensure that {$offset} and {$rowsperpage} are integers, converting them forced

**Comment by jimgwhit** [comment]
@LuckyCyborg you said
> Facts are that all bind parameters give are treated as PDO::PARAM_STR  

Is it possible that you could send parameters through a switch statement, and bind the correct type?  ### Please It would be a small amount of code, and an added method.

**Comment by LuckyCyborg** [comment]
I do not need to complicate the things without a sense, because the QueryBuilder use unnamed binding of parameters. I.e.
```
'SELECT * FROM `nova_users` WHERE `username` = ?'
```

**Comment by jimgwhit** [comment]
@LuckyCyborg it would be more for inserts and updates.

**Comment by LuckyCyborg** [comment]
@jimgwhit Only on LIMIT and OFFEST the binding should be **PDO::PARAM_STR**

**Comment by jimgwhit** [comment]
@LuckyCyborg  the way bindings are done now would decimal still be decimal, int still be int, float still be float, a formatted date remains a formarred date, etc?

**Comment by LuckyCyborg** [comment]
Yes.

**Comment by jimgwhit** [comment]
Perfect.

**Comment by LuckyCyborg** [comment]
:+1:

**Comment by jimgwhit** [comment]
@LuckyCyborg Up next I will play with the querybuilder some.

**Comment by LuckyCyborg** [comment]
But change that Issue title, it is a crap.
