### ISSUE TITLE
Lucky nothing bad just tech stuff on new API

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#917]
@LuckyCyborg as of now in the new database api I can
```
DB::table('dogs')
                ->where('dogid', $dogid)
                ->update($data);  // array of parameters
```
and of course it works. OR I can
```
$sql = "UPDATE " . PREFIX . "dogs SET dogpic = :dogpic, dogname = :dogname, sex = :sex, comments = :comments, adopted = :adopted, lastedit = :lastedit WHERE dogid = :dogid";
                 $stmt = DB::getPdo()->prepare($sql);
                 return $stmt->execute($data);
```
Just a note here not question (PREFIX not needed in QB, regular PDO needed).  
Or I can copy the update method from old Database helper, name it updatePdo and
```
DB::updatePdo(PREFIX . "dogs", $data, array('dogid' => $dogid));
//or if a $where varaible
DB::update(PREFIX . "dogs", $data, $where);
```
### All these work great.
Also a regular select like
```
return DB::select("SELECT * FROM " . PREFIX . "dogs WHERE dogname LIKE :search and adopted = 0 ORDER BY sex, lastedit DESC " . $pagingQuery, array('search' => $dogsearch));
```
Already works out of the box for a select query.  
Now the question: Is there a tweak you could do so the regular style updates and inserts will work in the new api, yet not affect QB syntax?  Like
```
DB::update(PREFIX . "dogs", $data, array('dogid' => $dogid));
or if a $where varaible
DB::update(PREFIX . "dogs", $data, $where);
```
This style.  
  Of course with the now available
```
 DB::getPdo()
```
Is is no big deal to
```
$sql = "UPDATE " . PREFIX . "dogs SET dogpic = :dogpic, dogname = :dogname, sex = :sex, comments = :comments, adopted = :adopted, lastedit = :lastedit WHERE dogid = :dogid";
                 $stmt = DB::getPdo()->prepare($sql);
                 return $stmt->execute($data);
```
But just wondering about other technique as well.  
I am glad we have the DB::getPdo() now, makes for super flexibility.  
of course $data above is
```
$data = array(
                    'dogid' => $dogid,
                    'dogpic' => $dogpic,
                    'dogname' => $dogname,
                    'sex' => $sex,
                    'comments' => $comments,
                    'adopted' => $adopted,
                    'lastedit' => $lastedit
                );
```
or
```
$data = array(
                    'dogpic' => $dogpic,
                    'dogname' => $dogname,
                    'sex' => $sex,
                    'comments' => $comments,
                    'adopted' => $adopted,
                    'lastedit' => $lastedit
                );
```
depending on which style used.  
NOTE: I have been testing out update, I have not done insert yet.

**Comment by LuckyCyborg** [comment]
@jimgwhit There are no **WHERE** parameter on the direct commands to **Database\Connection**.

**Database\Connection** is designed as **a backend for QueryBuilder**, and even it respect a similarity to **Illuminate\Database** API.

If you want WHERE parameters for selects, go **Helpers\Database**, which now is just a **frontend** to **Database\Connection** too and you are free to use it as you like.

**Comment by jimgwhit** [comment]
@LuckyCyborg are you saying both can be used at same time now?

**Comment by LuckyCyborg** [comment]
**Yes**. You do not read Release Notes?

**Comment by jimgwhit** [comment]
@LuckyCyborg if so, instead of
```
`DB::update(PREFIX . "dogs", $data, array('dogid' => $dogid));
``
what do I replace the
```
```
DB::update
```
with?

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous
does
```
$this->db->update
```
and
```
DB::update
```
work / can be called from same model?

**Comment by LuckyCyborg** [comment]
@jimgwhit I recommended you to not mix the things and styles. Use a single style for a Controller.

**Comment by jimgwhit** [comment]
@LuckyCyborg in new api I tryed
```
public function update($data, $where)
    {
        \Helpers\Database::update(PREFIX . "dogs", $data, $where);
    }
```
Not work, am I better off if I like regular queries most of the time just doing it like this
```
public function update($data)
    {
        

         $sql = "UPDATE " . PREFIX . "dogs SET dogpic = :dogpic, dogname = :dogname, sex = :sex, comments = :comments, adopted = :adopted, lastedit = :lastedit WHERE dogid = :dogid";
                 $stmt = DB::getPdo()->prepare($sql);
                 return $stmt->execute($data);
```
And / or why didn't this
```
public function update($data, $where)
    {
        \Helpers\Database::update(PREFIX . "dogs", $data, $where);
    }
```
work?

**Comment by LuckyCyborg** [comment]
Because the **Helpers\Database** you should instantiate in old good style.

**Comment by jimgwhit** [comment]
@LuckyCyborg 
> Because the Helpers\Database you should instantiate in old good style.  

Do you mean instantiate in old good style in the new api? Could you give an example.   
Helpers\Database works fine if I am not using new api, just can't get that method working in new api.

**Comment by LuckyCyborg** [comment]
```
$db = Database::get();

// Use the Database instance there.
```
Come on! You forgotten that?

**Comment by jimgwhit** [comment]
@LuckyCyborg if I do and update in the new api, just before the update call
```
$db = Database::get();

```
Will that mess up other stuff using DB:: ?
and after use should I
```
$db = NULL;
```

**Comment by LuckyCyborg** [comment]
@jimgwhit 

Jim! Use the Database instance like you user ever.

**Comment by jimgwhit** [comment]
@LuckyCyborg you do understand question, correct.  
I may want joins, thus I will use QB, but for a simple update I may want to use new api, but not QB.

**Comment by LuckyCyborg** [comment]
QueryBuilder is part of new Database API

**Comment by jimgwhit** [comment]
@LuckyCyborg $db = Database::get(); didnot work
I tryed
```
public function update($data, $where)
    {
        $cb = new \Helpers\Database();  // cb rather than db tryed db first
        $cb->update(PREFIX . "dogs", $data, $where);
    }
```
but error
```
Call to protected Helpers\\Database::__construct()
```
So there is no way to call a Helpers\Database method while in a model of the new API?

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous also plus in laravel you can
```
$krows = \Illuminate\Support\Facades\DB::table('pets')->where('petname', 'like', $petsearch)->count();
```
in other words call it with
```
\Illuminate\Support\Facades\
```
So I figured I could do the same like
```
\Helpers\Database::update(PREFIX . "dogs", $data, $where);
```

**Comment by LuckyCyborg** [comment]
JIM! 

**Helpers\Database** IS NOT like Illuminate! 

### IT IS DAVE'S DATABASE!

**Comment by jimgwhit** [comment]
You know I try to be nice, and every time I do that is what I get.  I was just looking for a way to make all those methods available, because the original database helper is pretty neat also.  
SO bottom line  
### there is no way to call a Helpers\Database method while in a model of the new API?

**Comment by geomorillo** [comment]
no

**Comment by jimgwhit** [comment]
At least I can use
```
$sql = "UPDATE " . PREFIX . "dogs SET dogpic = :dogpic, dogname = :dogname, sex = :sex, comments = :comments, adopted = :adopted, lastedit = :lastedit WHERE dogid = :dogid";
                 $stmt = DB::getPdo()->prepare($sql);
                 $stmt->execute($data);
                
```
I just like and am used of regular queries, but will use QB sometimes.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

This SQL command can be given via **DB::update()**, as:
```php
$sql = "UPDATE " . PREFIX . "dogs SET dogpic = :dogpic, dogname = :dogname, sex = :sex, comments = :comments, adopted = :adopted, lastedit = :lastedit WHERE dogid = :dogid";

DB::update($sql, $data);
```
That's all

**Comment by jimgwhit** [comment]
@LuckyCyborg good to know, similar to my getPdo example, but would work out of box.

**Comment by jimgwhit** [comment]
Maybe @Kingorgg could enhance API docs with a few more examples.
