### ISSUE TITLE
Size is out of hand

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#932]
@daveismyname I noticed it taking a long time just to do a zip backup  of dev site. Here is what I found:  
Vendor folders only
* Laravel 4.2       15.5 MB
* Laravel 5.1       21.1 MB  

### Nova a whopping   36.4 MB  

Laravel has bootstrap, ORM, Querybuilder, etc, why is Nova's vendor folder twice as big?

**Comment by LuckyCyborg** [comment]
When installed, Nova ships the **AdminLTE** theme, which is **a premium Backend theme**, but it not exactly small, having around **22 MB**.

Add also **12 MB** given by the Vendor shipped **Twitter Bootstrap 3**, and you have a figure about **34 MB**. It is much?
