### ISSUE TITLE
almasaeed2010 in vendor Very heavy 20MB

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#939]
in vendor almasaeed2010  contain same front end files itis very heavy please delete it

**Comment by pandory-network** [comment]
u can delete it self. remove "almasaeed2010/adminlte": "~2.0", from composer.json

 almasaeed2010/adminlte its a admin template, its was added for example modules

**Comment by vahidalvandi** [comment]
total size after use composer install About ~35 MB  . this not optimize size .. master nova must have minimal size :+1:

**Comment by pandory-network** [comment]
nova is lightwight, the 2 last composer packages almasaeed2010/adminlte and twbs/bootstrap only for the Default/Admin Templates and Demo Modules like Dashboard/User

**Comment by LuckyCyborg** [comment]
@vahidalvandi Nova have **2.4 MB** without the DEMO Templates.

And you are supposed to write your own Templates.

**Comment by vahidalvandi** [comment]
it should delete in master nova , and use in other sample or tutorial

**Comment by LuckyCyborg** [comment]
Why I should delete from it from master Nova while I use it in every project?

Also to note @daveismyname do the same, using **AdminLTE** extensively.

**Comment by vahidalvandi** [comment]
Nova is Framework !!! and may use in same project dont need admin templete

**Comment by LuckyCyborg** [comment]
@vahidalvandi Again, those are shipped as DEMO! Use them or DELETE them! It is your call!

**Comment by amiroperator** [comment]
@vahidalvandi مشکلیت چیه داداش ؟

**Comment by vahidalvandi** [comment]
it download in any use composer ,.....

**Comment by vahidalvandi** [comment]
please type English .... my amir

**Comment by amiroperator** [comment]
Whats your problem ?

**Comment by vahidalvandi** [comment]
please read above issues :+1:

**Comment by amiroperator** [comment]
You can delete them they're just some demos.

**Comment by vahidalvandi** [comment]
in master composer should delete

**Comment by LuckyCyborg** [comment]
Why?

**Comment by vahidalvandi** [comment]
please see this link 
https://almsaeedstudio.com/blog/new-and-free-bootstrap-admin-template-2016

it have more style for every one , we dont need add heavy script in composer , and we need use
composer create-project nova-framework/framework foldername -s dev

**for each use this command download unnecessary vednor**

**Comment by vahidalvandi** [comment]
so last update almasaeed2010  is for 5 months ago but same demo like 
https://github.com/puikinsh/gentelella
3 day ago...

**Comment by LuckyCyborg** [comment]
@vahidalvandi Again, AdminLTE theme is shipped as **DEMO**, just like **Default** Template, just like the Modules and some App controllers.  

They are not required by Framework to work, but in a initial phase of testing is nice to have.

When you start you project, you have just to cancel the Templates and Modules which are no need for.

**Comment by vahidalvandi** [comment]
this unusual in master

**Comment by LuckyCyborg** [comment]
Is unusual to remove the default Templates ?

I used to develop new Templates and Modules for every project.

**Comment by vahidalvandi** [comment]
you use but all users not use for every project,,,

**Comment by LuckyCyborg** [comment]
Come on! You deploy sites using the **Default Template** ?

**Comment by vahidalvandi** [comment]
no I don't deploy by default templete

**Comment by LuckyCyborg** [comment]
Then, what is your problem?

**Comment by vahidalvandi** [comment]
Come on!  
Come on! 
close,
