### ISSUE TITLE
data base migration in nova

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#941]
In your opinion can we add Phinx in core nova 

phinx.org

**Comment by jimgwhit** [comment]
Out of curiosity, you couldn't add this to composer and just use it on your own?  What would be the problem with something like that?

**Comment by LuckyCyborg** [comment]
Gods forbid! Finally having same opinion with Jim about one thing... :sake:

**Comment by LuckyCyborg** [comment]
@jimgwhit You are native English, please correct my grammar on:

`Anounce the interested Listeners about the booting the Framework.`

**Comment by jimgwhit** [comment]
Initiate the Listeners ......

**Comment by LuckyCyborg** [comment]
@jimgwhit Do that phrase right on Academic English, please!

**Comment by jimgwhit** [comment]
@LuckyCyborg earlier in a chat you gave an example like
```
return $this->getView()
            ->shares('title', __('Users'))
            ->with('users', $users);
```
I am using like this
```
$this->layout = 'indextpl';
        return View::make('Dog/Index')->with('data2', $data['dogs'])
```
What is difference in getView() and return View::make

**Comment by LuckyCyborg** [comment]
No one, `getView()` calculate a View path from certain info, while on second way, you specify directly what you want.

**Comment by daveismyname** [comment]
At the moment that should be down to the end user, we may add that to the core in future.
