### ISSUE TITLE
Lucky example

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#947]
@LuckyCyborg could you do a small crud example that includes fastcache, say a customer table with at least 30 or more customers to show usage of ORM or querybuilder, combined with pagination, combined with the fastcache. It would make for good understanding of how all works together.  Or @daveismyname could you do it in a crud video showing usage of fastcache?  Either api is fine.  
And is the fastcache only for the new api or both now, i.e., will it work with database helper results and new querybuilder results.  

I fully know how to use the querybuilder, but confused about fastcache.  
### That's fastcache now not fastcash.  

Bet you can't say that 3 times fast.  
Oh, and is it necessary on site with only medium to small amount of hits / queries?  
And is there any auto cache php is using anyway?  Please explain, I never had to put any thought into this.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> That's fastcache now not fastcash.

I dare to say contrary: a Fast Cache is **all about** Fast Cash. As a well implemented Cache can speed-up your site from supporting 1000 simultaneous Visitors to a whooping 12.000 figure.

In other hand, combining CRUD with Cache is a plain a stupid idea. The Caching apply to data which is unchanged on the next minutes. For example: **public pages**.

**Comment by jimgwhit** [comment]
> the single valuable caching method available is: caching to files.  

Is that default without fastcache? In other words how would have catching been accomplished in version 2.2 and I'm just trying to learn here caching is new to me.

**Comment by LuckyCyborg** [comment]
@jimgwhit You speak gibberish. Try again!

2.2 do not have Caching, and there it is, and also, **Caching to Files** is much better than nothing. 

BUT, Caching is really a fine Art, depending on application and his developers.

Like how I can't make you to learn how to sing Classic Opera, this way is about Caching too.

Just to figure that: **there is Caching support**, but using it right **is a Fine Art** comparable with Classic Opera.

**Comment by jimgwhit** [comment]
@LuckyCyborg hopefully Dave will do a video with a simple demonstration or maybe you could write a controlletter and  a demonstration. How did a ver 2.2 handle many hits.

**Comment by LuckyCyborg** [comment]
@jimgwhit I wondering what is "many hits" for a pets site...

The Caching is useful when you talk about figures behind 100-500 Visitors, all simultaneous on-line.

**Comment by jimgwhit** [comment]
Sounds like caching is where you cached a certain result, how can Google handle caching when you have not only millions of results but millions of different searches simultaneously no two people searching the exact same thing at the same time I guess it is just very confusing find me to understand this  

I looked at fast cache documentation and it sounds like they are catching one particular query that will be used over and over again for a while, but Google has millions of queries not used over and over again each is unique.

**Comment by LuckyCyborg** [comment]
@jimgwhit Guess why Google use **server-farms** for its job, and pay billions on Artificial Intelligence.

You believe that Google is a site hosted in a lame server for $50 monthly?

**Comment by jimgwhit** [comment]
@LuckyCyborg so coming back to smaller sites is a use case for caching, caching paginator results for example caching page 1 or page 2 assuming it will be used several times simultaneously by several people?

**Comment by LuckyCyborg** [comment]
Sure thing.

BUT, you have to learn to do it right, and the results depends on the specific site and the developer's talent. 

Like I said, is a Fine Art, do not expect to learn it a forum or there.

**Comment by jimgwhit** [comment]
Remember though I started out in Java Technologies it was a trucking company and an intranet, not massive website just the two offices used it for truck dispatch. 6 hits at most at a time. But yes I made real real good money as the database manager just never dealt with super big giant FedEx size sites.

**Comment by jimgwhit** [comment]
@LuckyCyborg see previous reply also quick question concerning security I know it's best to put main files above HTdocs but you put new htaccess files in those folders doesn't that help with security and like I know right now I cannot access the error log online because of that htaccess file you put in which was a good idea.

**Comment by LuckyCyborg** [comment]
I tried to shield-up the Framework, and usually this "halp!" for securing the site, still having the Cache, Logs and Session files naked on web, in case of server-miss-configuration, is not the best idea.

And this server-miss-configuration happens. More frequently than you think, even if is for several minutes.

Even the Facebook guys hit on that, in the past.

**Comment by jimgwhit** [comment]
@LuckyCyborg in a controller method I have
```
$this->layout = 'adpttpl';
return View::make('Dog/Indexadpt')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
```
Of course in construct I have
```
$this->template = 'Dog';  // Dog for all of this controller, but varoius layouts.
```
I never made a $content variable.
In adpttpl.php template I have  
* the header stuff at top
```
<?php
echo $data['content'];   //THIS IN MIDDLE LIKE YOUR EXAMPLES
?>
```
* and of course footer stuff.  

How does this work without making the $content variable, somehow it is working fine.

**Comment by LuckyCyborg** [comment]
The Layouts are a special case of Views.

**Comment by jimgwhit** [comment]
@LuckyCyborg so
```
$data['content'] = View::make('Dog/Indexadpt')->with('data2', $data['dogs'])->with('data3', $data['pageLinks']);
return Template::make('adpttpl', $data, 'Dog');
```
is correct, right?  
And how does the first example above still work when I never made a $data['content'] variable, just trying to understand, and make sure I am doing it right.

**Comment by LuckyCyborg** [comment]
The **Middleware** do a **fetch()** the returned (by you) View instance and then will inject the resulted to 'content' on the specified Template Layout, using, like you do manually, a Template instance.

This permit you to do the tasks, without to repeat the same code hundred times.

**Comment by jimgwhit** [comment]
@LuckyCyborg so bottom line, either is correct above.
