### ISSUE TITLE
Unable to load the view

### ISSUE THREAD

**Issue by JohnRamon** [nova-framework/framework#957]
I updated to the latest version and on any page that submitted to itself to reload the view to show error i get this error... Any ideas?

        $data['title'] = $this->language->get('title_name');

        View::renderTemplate('header', $data);
        View::render('login/login', $data,$error);
        View::renderTemplate('footer', $data);

Exception information:

           Date: Jun 07, 2016 21:44PM

           Message: Unable to load the view 'login/login'. File '/Users/testserver/Sites/psg/app/Modules/Array/Views/login/login.php' not found.

           Code: 1

           File: /Users/testserver/Sites/psg/system/Core/BaseView.php

           Line: 80

           Stack trace:

           #0 /Users/testserver/Sites/psg/system/Core/BaseView.php(65): Core\BaseView->render()
#1 [internal function]: Core\BaseView->fetch()
#2 /Users/testserver/Sites/psg/system/Core/BaseView.php(325): call_user_func_array(Array, Array)
#3 /Users/testserver/Sites/psg/system/Core/Controller.php(174): Core\BaseView->__call('fetch', Array)
#4 /Users/testserver/Sites/psg/system/Core/Controller.php(174): Core\View->fetch()
#5 /Users/testserver/Sites/psg/system/Core/Controller.php(146): Core\Controller->createResponse(NULL)
#6 /Users/testserver/Sites/psg/system/Routing/BaseRouter.php(203): Core\Controller->execute('index', Array)
#7 /Users/testserver/Sites/psg/system/Routing/BaseRouter.php(234): Routing\BaseRouter->invokeController('App\\Controllers...', 'index', Array)
#8 /Users/testserver/Sites/psg/system/Routing/Router.php(269): Routing\BaseRouter->invokeObject('App\\Controllers...', Array)
#9 /Users/testserver/Sites/psg/system/bootstrap.php(74): Routing\Router->dispatch()
#10 /Users/testserver/Sites/psg/public/index.php(68): require('/Users/testserve...')
#11 {main}

           ---------

**Comment by LuckyCyborg** [comment]
@JohnRamon The error is very precise, it say that can't find the View file:

```
Unable to load the view 'login/login'. 

File '/Users/testserver/Sites/psg/app/Modules/Array/Views/login/login.php' not found.
```

**Comment by LuckyCyborg** [comment]
And please learn to use capitalized names. That's the Nova style.

For example:
```
Login/Login
```

**Comment by JohnRamon** [comment]
My views are in 

/Users/testserver/Sites/psg/app/Views/login/login.php loads fine when i submit any form it looks in /Users/testserver/Sites/psg/app/Modules/Array/Views/login/login.php

Why is it looking in there?

I see nothing in the documentation about the Modules folder and why it would start looking in there when a form is submitted

**Comment by LuckyCyborg** [comment]
@JohnRamon Just remove the third parameter from **View::render()**, as the $error. 

Now this $error should integrate on $data directly:
```php
$data['error'] = $error;
```

**Comment by JohnRamon** [comment]
Thank you that seemed to work, you rock!!!
