### ISSUE TITLE
Message formatter error

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#965]
@LuckyCyborg After updating up through comment 051b3da4a113c1a984675ada1c67c9a645475c79 I now get this apache error, worked fine prior to this round of updates:
```
Class 'MessageFormatter' not found in C:\\Bitnami\\wampstack-5.6.22-0\\apache2\\htdocs\\nova\\system\\Core\\Language.php on line 172
```

**Comment by DonWagner** [comment]
Is that not because INTL needs to be enable??

**Comment by jimgwhit** [comment]
@DonWagner that did the trick, with 10 pull request hourly it's hard to keep track. This thing is becoming a plate of spagatti.

**Comment by DonWagner** [comment]
Thats an very old thing! :smile: so don't know why you first got the problem now.

**Comment by DonWagner** [comment]
24 days old news from V. 3.20 :)

https://github.com/nova-framework/framework/releases/tag/v3.20.0

**Comment by southcoastweb** [comment]
I had the same error 2 days ago and i was only about 4 days behind on prs. As soon as i added intl it fixed the issue for me as well. So not sure if something else triggered the error as Im sure jim is not far behind on prs neither.

**Comment by LuckyCyborg** [comment]
It is fault of no one that some persons do not read the Release Notes,and not do a check of the requirements of the current **README.md**

**Comment by DonWagner** [comment]
As I recall this requirement is not written on novaframework.com.

**Comment by LuckyCyborg** [comment]
> As I recall this requirement is not written on novaframework.com

Yep, @daveismyname or @Kingorgg should update there, but it is written on the shipped **README.md**, from the root directory.

**Comment by Kingorgg** [comment]
@DonWagner and @LuckyCyborg: Requirements have now been updated on the main website (novaframework.com)

**Comment by LuckyCyborg** [comment]
Thanks, Daniel!

But I bet that some do not visit that page often, i.e. our friend which love pets.

**Comment by jimgwhit** [comment]
@LuckyCyborg Requirements for a framework shouldn't change every 30 minutes.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Requirements for a framework shouldn't change every 30 minutes.

For you 24 days are 30 minutes? Sorry, but you have another time speed than me.

**Comment by mellat** [comment]
I have same error ! 
`Class 'MessageFormatter' not found` , 
Open:
/home
/user
/public_html
/system
/Language
/Language.php

**Comment by LuckyCyborg** [comment]
**Read The Fucking Manual** before to comment!

**Comment by southcoastweb** [comment]
@mellat You must have php intl enabled. It does state this now in system requirements. I believe thats what @LuckyCyborg meant to say :)

**Comment by LuckyCyborg** [comment]
@southcoastweb Sorry, but I can't feel mercy for someone who do not read even the freaking **README**, which is on site root, before claiming errors ...
