### ISSUE TITLE
Session api Session::has is working after all

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#969]
@LuckyCyborg  and @daveismyname  I have this
```
Session::set('loggin', 'islogged');
```
This works and persist.  
However this
```
public function chklog() {
     echo "in chklog";   /// this echo does work
      if (Session::has('loggin')) {
            echo "worked";   /// this echo does not work
            if (Session::get('loggin') != 'islogged') {
                return Redirect::to('admin');
            }
        }
        else {
            return Redirect::to('admin');
        }
    }
```
And tryed
```
!=
!==
<>
```
Does not work.  In the api docs you have login or not the redirect don't work here.
```
if (Session::has('users'))
{
    //
}
```
So Session::has isn't working, how do I check to see if the session is equal to a certain thing without Session::has  
But if I echo out 
```
echo "sess===" . Session::get('loggin');
```
as a test echo it works, so session does persist.  
### Edit:  
This is weird, I tryed
```
public function chklog() {
        
        $yeslog = Session::get('loggin');
        $tonl = (is_null($yeslog) || empty($yeslog) || strlen($yeslog) < 1 ? 'notlogged' : $tonl);
        echo "====".$tonl."====";   ////echo for testing
        if ($tonl !== 'islogged') {
            return Redirect::to('admin');
        }
        /// below here commented out
        /*if (Session::has('loggin')) {
            echo "worked";
            if (Session::get('loggin') != 'islogged') {
                return Redirect::to('admin');
            }
        }*/
    }
```
I purposely did not log in to test and the $tonl is correctly = notlogged from this line:
```
notlogged
```
So in this part, for some reason the redirect doesn't work, yet other places redirect works:
```
 if ($tonl !== 'islogged') {
            return Redirect::to('admin');
  }
```
That should work because $tonl !== 'islogged' and I do have the use Redirect; at top.  
Coud the fact that Session::get('loggin') does not exist be messing with the redirect somehow?  redirects are working every where else.  All new api stuff here.  

### Another edit:  

This is really bazarr, I took everything out of function except:
```
function chklog() {
        return Redirect::to('admin');
    }
```
Tryed public function and just function.  From the 
```
public function indexAdmin() {
        $this->chklog();
        // more code
```
I know $this->chklog(); is called because the test echos are working.  Why wouldn't a redirect work here?

**Comment by LuckyCyborg** [comment]
@jimgwhit 

```php
public function indexAdmin() {
        $this->chklog();
        // more code
}
```
Commenting on this method, while **chklog()** returns a **Redirect** instance, you do nothing with it.

A valid sequence will be:
```php
public function indexAdmin() {
        $result = $this->chklog();

        if ($result instanceof Redirect) {
            return $result;
        }
        // more code
}
```
Sure, maybe looks more complicated, but in my Nova's Design the authentication checking should be done in Route Filters or in Middleware, i.e. on **before()**;

**Comment by jimgwhit** [comment]
@LuckyCyborg all controller methods don't require login, just indexAdmin.  Teh regular index is for general public. But this should work no matter what, but it doesn't
```
function chklog() {
        return Redirect::to('admin');
    }
```
shoultn't return Redirect::to('admin'); work if that is only thing in that function for a test?  
return Redirect::to('admin'); works other places I use it.

**Comment by LuckyCyborg** [comment]
@jimgwhit If the only method protected is "indexAdmin", you can go:

```php
protected function before() {
    if ($this->getMethod() == 'indexAdmin') {
        $result = $this->chklog();

        if ($result instanceof Redirect) {
            return $result;
        }
    }

    // Leave to parent's method the Execution Flow decisions.
    return parent::before();
}

public function indexAdmin() {
    // more code
}
```

**Comment by jimgwhit** [comment]
@LuckyCyborg above didnot work, but this is also wierd, if I put
```
public function indexAdmin() {
         return Redirect::to('admin');
        //$this->chklog();
        $dogsearch = (isset($_REQUEST['psch']) <> '' ? $_REQUEST['psch'] : "");
        $aval = (isset($_REQUEST['aval']) <> '' ? $_REQUEST['aval'] : "");
        \Session::set('dogsearch', $dogsearch);
        \Session::set('dogaval', $aval);
        ///////more code
```
return Redirect::to('admin'); right in public function indexAdmin() it works perfect.  
Just some how calling another function, and having the 
```
Redirect::to('admin');
```
does not work, this is puzzling.

**Comment by geomorillo** [comment]
where is the docs about this?

**Comment by daveismyname** [comment]
at https://github.com/nova-framework/framework/wiki/Redirect

**Comment by geomorillo** [comment]
docs incomplete?

**Comment by LuckyCyborg** [comment]
@jimgwhit You have to return from the executed **Action** the Redirect instance. 

There is nothing wierd, your **chklog()** return a **Redirect** instance, but you do **nothing** with it.

You have to check the return value of **chklog()**, and if it is a **Redirect** instance, just return this value from Action.

If you do not return to Middleware that Redirect Response instance, it will do nothing.

**Comment by jimgwhit** [comment]
I did a work around and got it working.  I created a private var:
```
private $toredir;
```
I call the function:
```
public function indexAdmin() {
        $this->chklog();
        if ($this->toredir == 'notlogged') {
            return Redirect::to('admin');
        }
/////////more code
```
and in chklog
```
function chklog() {
        $yeslog = Session::get('loggin');
        $this->toredir = (is_null($yeslog) || empty($yeslog) || strlen($yeslog) < 1 ? 'notlogged' : 'islogged');
        return $this->toredir;
    }
```
Now if not logged it it redirects

**Comment by LuckyCyborg** [comment]
@geomorillo 

> docs incomplete?

Docs are complete, but our friend do not understand that a **check()** returning a value, you have to continue to process it, to obtain a required result.

**Comment by geomorillo** [comment]
what i mean where is this check() in the docs?

**Comment by LuckyCyborg** [comment]
@geomorillo Not in Nova's docs because, it is a custom method used by @jimgwhit , which use his own Authentication.

It is called `chklog();`

**Comment by jimgwhit** [comment]
@geomorillo I had to tweak it for nova, it worked a little different in ver 2.2, but now it works.  I am just basically redirecting back to a page to let someone know they are not properly logged in.

**Comment by geomorillo** [comment]
yes i saw that... was copy pasting the wrong function 
https://github.com/nova-framework/framework/wiki/Middleware
i think this docs maybe should updated , can you check them?

**Comment by jimgwhit** [comment]
Commented out here, but same will work in the before
```
/* protected function before() {
      if ($this->getMethod() == 'indexAdmin') {
      return Redirect::to('admin');  // just a test redirect
      }
      return parent::before();
      } */
```
I might put the logic in a before, still converting stuff to nova from 2.2

**Comment by jimgwhit** [comment]
@LuckyCyborg now I did
```
public function indexAdmin() {
        $this->chklog();
        if ($this->toredir == 'notlogged') {
            return Redirect::to('admin');
        }
/////////more code
```
changed chklog to
```
function chklog() {
        //$yeslog = Session::get('loggin');  /////commented out
        //$this->toredir = (is_null($yeslog) || empty($yeslog) || strlen($yeslog) < 1 ? 'notlogged' : 'islogged');  /////commented out
        if (Session::has('loggin')) {
            $this->toredir = Session::get('loggin');
        }
        else {
            $this->toredir = 'notlogged';
        }
        return $this->toredir;
    }
```
Guess what it works.

**Comment by jimgwhit** [comment]
I also test echoed $this->toredir and all is fine. So I guess in nova a return, just finish processing in parent method.  Thanks for your help.

**Comment by daveismyname** [comment]
> yes i saw that... was copy pasting the wrong function 
> https://github.com/nova-framework/framework/wiki/Middleware
> i think this docs maybe should updated , can you check them?

Update to what? sorry I'm not following you.

**Comment by LuckyCyborg** [comment]
@daveismyname Our Colombian friend confused the custom method used by @jimgwhit as being a Framework shipped one, I guess.

BTW; please look in **gitter**, I raised  two questions to you.

**Comment by geomorillo** [comment]
i told you im not confused $this->getMethod() is not the same function inside the middleware docs also should i use Url::redirect or Redirect::to ??

**Comment by LuckyCyborg** [comment]
@geomorillo I recommend you to use **Redirect::to()**, in the near the **Url::redirect()** will be supported via throwning a special Exception, finally arriving to a **Redirect::to()** instance returned to kernel.

**Comment by geomorillo** [comment]
ok

**Comment by jimgwhit** [comment]
@geomorillo change over to Redirect::to will need a
```
use Redirect;
```
at top of controller, this is that symphony stuff.
