### ISSUE TITLE
change .htaccess in public

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#972]
this command sometimes error 500 in server

line 21 = 

`	RewriteRule ^(.*)$ index.php?$1 [QSA,L]
`

please change it to

`	RewriteRule ^(.*)$ index.php?url=$1 [QSA,L]
`

**Comment by jimgwhit** [comment]
Actually if that's working for you you are free to change things as you need it in your own server. Probably no need to change in GitHub version master. I myself have received no such error. I wonder why you did get an error.
