### ISSUE TITLE
About a meaningful (code)name for CLI utility, and please not 'Nova'

### ISSUE THREAD

**Issue by LuckyCyborg** [nova-framework/framework#975]
Right now, Nova have a powerful service support and I started to implement a small console API inside the **System**.

Our **nova** console utility can be enhanced and integrated with the Nova's **Services**, making it **extensible** and even more powerful. Read: it could become similar with Laravel's **Artisan**.

One single problem: its name. To think that I would need to create some classes on System, to integrate the console part, and **Nova**, well is not so meaningful for one which see a class named that on **\Foundation\** namespace, for example.

My proposal is to be **Smith** or **BlackSmith**, a pun intended to my Team Leader saying of that using the console utilities is a thing for **blacksmiths**.

### You have better ideas for the CLI codename?

To note that the discussion is about the internal and public API **codename** for the console utility, **not** about the literal name of that utility, which can remain the same, as 'nova' and the Dave's video lessons to keep being accurate.

For example, the core class of CLI utility will be:
```
Foundation\Smith
``` 
or
```
Foundation\BlackSmith
```

**Comment by geomorillo** [comment]
Quasar

**Comment by LuckyCyborg** [comment]
@geomorillo 
> How about **Forge** Console

Thanks! Yeah, in our line of thinking, is another name full of pun! A **Forge** is exactly a thing which the blacksmiths use. :+1:

**Comment by Kingorgg** [comment]
I agree with Forge.

**Comment by daveismyname** [comment]
I also agree with Forge.

**Comment by LuckyCyborg** [comment]
@/all Then, **Forge** will remain!
