### ISSUE TITLE
csrf

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/framework#977]
@LuckyCyborg  and @daveismyname 
I am original contributor csrf, but since the change in nova, it's not working, please help me figure this out.  
In view: I tryed various
* name="csrf_token"  
* name="csrfToken"  

and
```
<input type="hidden" name="csrf_token" value="<?php echo '12487xcder'; ?>" />
```
I put
```
'12487xcder';
```
To purposely fail to test it, but it doesn't.  ///// the 12487xcder for testing
here is controller:
```
$data['csrfToken'] = Csrf::makeToken('edit');  // would store to session here
        $data['content'] = View::make('Admin/Login')
                ->shares('title', 'Login')
                ->with('data2', $data['csrfToken']);
        return Template::make('logintpl', $data, 'Dog');
```
and the test:
```
if (!Csrf::isTokenValid('edit')) {
            echo "something wrong";
            //return Redirect::to('admin/login'); // Or to a url you choose.......
            }
/////more code
// return Redirect::to('dog/indexadmin');
```
I never get the  echo "something wrong";  
I know it's stored in session, I test echoed it out, please help.  
Hold on I am further testing.  
I think I figured it out, sorry.

**Comment by LuckyCyborg** [comment]
So, you are kind to enlighten us what you discovered about that subject, Jim?

**Comment by jimgwhit** [comment]
@LuckyCyborg it works, just forgot to comment out another redirect.  
I just wanted to test for myself, as any developer should the security stuff.  
Of course some don't and that's where problems could come in.

**Comment by LuckyCyborg** [comment]
@jimgwhit To note that **Helpers\Csrf** use **Helpers\Session**, if you want to use the new way, in controllers set the csrfToken from **Session::token()** and apply to route the Filter "csrf".

**Comment by jimgwhit** [comment]
@LuckyCyborg you said  
> set the csrfToken from Session::token() and apply to current Route the Filter "csrf".  

I don't see a Session::token() in API, could you give a more detailed example of using csrf token with new API.

**Comment by Kingorgg** [comment]
Look at app/Filters.php to see the CSRF filter and then look at the users module.

You will want to look at Controllers/Authorize, Views/Authorize/Login and the Routes in that module. 

That will show you how to use CSRF.

**Comment by LuckyCyborg** [comment]
@jimgwhit The response to your question was given by our friend @Kingorgg , and Nova ship a complete **Backend** example, by its demo Modules, including Authorization, CSRF, etc.

The Demos utility is given as demonstration how those things are (or should be) implemented.

First to open issues, look on given examples, Nova ship them (making it so fat) with a reason.
