### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by daveismyname** [nova-framework/framework#984]
How can the database cache be turned off? 

changing a value in the database is not reflected on the application as it's been cached. Also where is the setting for the length of time the cache is kept?

**Comment by LuckyCyborg** [comment]
@daveismyname Database do not use Cache (yet). 

Which thing you suspect to be cached?

**Comment by daveismyname** [comment]
for instance I have the site title coming out from the database I can see a cache file in the storage if I change the title in the database its not changed on the site unless I delete the cache file in the storage.

**Comment by daveismyname** [comment]
I have CONFIG_STORE set to database

**Comment by LuckyCyborg** [comment]
The Config API use the Cache, to improve its performance, BUT, when you **set()** something, it automatically will invalidate the cache of the entire options group. That is supposed for doing.

**Comment by daveismyname** [comment]
OK that works, but is there no way to turn that off/refresh the cache manually do when doing manual changes in a database, I can see this cropping up a lot from users.

**Comment by LuckyCyborg** [comment]
Huh? Why a end user to have to modify manually the options on database?

I can stop caching on development mode, but we will complicate the code, and being... well, on Config API, I can rely only on ENVIRONMENT.

**Comment by daveismyname** [comment]
OK no I'll make sure I make a note of this when updating the docs again ;(
