### ISSUE TITLE
potential for v4?

### ISSUE THREAD

**Issue by daveismyname** [nova-framework/framework#986]
I know I've been the biggest support on staying v3 but with the constant updates happening I feel it would be better to jump to v4 now and separate the application into app and system to the framework can be updated from a composer update.

thoughts?

**Comment by LuckyCyborg** [comment]
I was always the biggest partisan of separating the application on app and system, thing of nature to simplify considerable the updating the system by end users.

Also permitting having multiple apps, i.e. a slim bare one, without nothing demos, and one fat and full fledged.

Yet, to note that going on Composer package with system, we need to enclose everything in a common namespace i.e. **\Nova **. And that's a epic API break, then the major version increasing is well justified.

BTW, I suggest you to create two new repository, called **app** and **system**, also to register them to **packagist**, to me playing with.

**Comment by daveismyname** [comment]
OK we are in agreement I will add those repos

**Comment by daveismyname** [comment]
https://packagist.org/packages/nova-framework/app
https://packagist.org/packages/nova-framework/system

both exist both repo's contain a composer will that will need configuring.

**Comment by LuckyCyborg** [comment]
@daveismyname Roger that! Tomorrow I will start over that.

**Comment by daveismyname** [comment]
👍

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg 
* Will system be moved to vendor
* Will some of the helpers remain out of vendor for customization
* I can see the new API stuff being in vendor, but not the original database helper

**Comment by daveismyname** [comment]
Yes system will be moved I should think everything in the system would be moved let's wait and see what can work with this setup of course always interested on your thoughts

**Comment by LuckyCyborg** [comment]
@jimgwhit Sorry, Jim...

BUT there will not be **system** folder anymore. Custom Helpers will go to **App\Helpers**

@daveismyname How about to nuke the legacy support? Your community already learned to use new APIs and some struggle now ORM.

**Comment by daveismyname** [comment]
Just to be clear what aspects do you propose to remove? I'll check back in morning

**Comment by LuckyCyborg** [comment]
@daveismyname 

For example, the support for **View::render()** and **View::renderTemplate()** and the following Helpers:

**Helpers\Csrf**
**Helpers\Database**
**Helpers\Session**

Those which will want those Helpers can simply backport them to **App\Helpers**.

**Comment by jimgwhit** [comment]
I use the new api, sessions, rendering, but with original database helper.

**Comment by LuckyCyborg** [comment]
@jimgwhit Look, I suppose that version four to give (legacy) support to three, not to two-two. 

Facts are that **Hash** Facade give you exactly what offer also **Helpers\Password**, while for new APIs, **Password** is something entirely different: Auth's Password Broker.

Also, **Database API** support long queries, just like **Illuminate\Database** do.

In other hand, that **Helpers\Paginator** is hard-coded to Bootstrap3, even it work with QueryBuilder too, while that QueryBuilder give you native pagination support.

If you really want to keep and use those three Helpers, nothing stop you to port them from **Nova 3** to namespace **App\Helpers**.

Alternatively, maybe someone will be have the will to create and maintain a Composer package shipping them. Or the two-two die-harders know only to ask for?

BTW, in any chosen variant, there will be the need to change the code, even if we keep them, becoming:

Nova\Helpers\Paginator
Nova\Helpers\Password
Nova\Helpers\Database

**Comment by daveismyname** [comment]
I'm inclined to agree with @LuckyCyborg there are 2 ways to work with quite a few areas, makes sense to reduce that to one, as mentioned the helpers can be added under app/Helpers by the end user.

I could add the classes to separate packages that can be added to composer as the end user desires.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, I have direct write access to app and system repositories?

In the initial stage, I guess is better to push directly to, instead to use my own forks.

**Comment by daveismyname** [comment]
Yes you have write access to the Nova organisation so that includes all repos.

**Comment by LuckyCyborg** [comment]
@daveismyname Look there:

```
bash-4.3# git push
Username for 'https://github.com': LuckyCyborg
Password for 'https://LuckyCyborg@github.com': 
remote: Permission to nova-framework/system.git denied to LuckyCyborg.
fatal: unable to access 'https://github.com/nova-framework/system.git/': The requested URL returned error: 403
bash-4.3# 
```

**Comment by daveismyname** [comment]
ah ok 1 minute.

**Comment by daveismyname** [comment]
try it now.

**Comment by LuckyCyborg** [comment]
@daveismyname Yep, worked. Thanks!

Same thing I need to app repository, too.

**Comment by daveismyname** [comment]
done it there too

**Comment by LuckyCyborg** [comment]
@daveismyname Thanks, but looks that there is no propagation on packagist. How much time will be need for?

**Comment by daveismyname** [comment]
didn't get it working last night, will look at it again.

**Comment by LuckyCyborg** [comment]
@daveismyname OK

**Comment by LuckyCyborg** [comment]
@daveismyname Thanks!

**Comment by LuckyCyborg** [comment]
@daveismyname We agree on using for System the namespace **\\Nova\\** ?

**Comment by daveismyname** [comment]
Yes.

**Comment by amiroperator** [comment]
I think if there was a functions file like system in app for every module or whole framework that would be better

**Comment by LuckyCyborg** [comment]
@amiroperator There is no need for. 

The **nova-framework/system** ships the framework, after all, while the **nova-framework/app** will ship the Application, where the end-user have its site.

**Comment by southcoastweb** [comment]
Can i quote a conversation we had the other night @LuckyCyborg : ' The system folder is mine and the app folder is yours' , made perfect sense to me. I moved all my helpers into the App folder and the system is completely untouched from master and it worked well on the following PRs.

**Comment by DonWagner** [comment]
This sounds like a great development.

What about the demo modules?

At some point these a great, i love them and uses them to read and learn from, but i still think it would be better if these could be ship separate, and not be a part of the mani parts like nova-framework/system and nova-framework/app. 

Maybe like before, the smvc homepage had/have a section to addons.
This section could get a makeover and the demos could bee added in to this section.

In that case, it would also be nice if the users could se which versions the modules was made for.

**Comment by daveismyname** [comment]
there will be a demo repo for this purpose I believe, the addons sections could be utilised for this end too.

**Comment by LuckyCyborg** [comment]
@daveismyname Right now, i will work on full App tree. And I suggest to remain as it is.

On future, for those which want a naked app, you could create a **nova-framework/bare-app** which ship no demo and no template.

**Comment by daveismyname** [comment]
why? that really makes no sense to bring the demos as part of the main framework, having the main app to essentials only the demos should be elsewhere. 

Otherwise 2 repo's need to be kept up to date whilst a demo tree or forget a demo tree having addons modules that a user can add themselves make more sense as they can be maintained seperatly from the framework leaving the choice to the end user to include the demo or not.

**Comment by LuckyCyborg** [comment]
@daveismyname The main Framework is **nova-framework/system**, the apps are just apps.

**Comment by daveismyname** [comment]
On install it will still contain demos why?

keeping nova-framework/app free of demo means it can be used right away without having to remove unwanted things that should not be there to start with as they are just demos.

**Comment by LuckyCyborg** [comment]
And what will differ if we ship the bare app on **nova-framework/bare-app** ?

Please figure that on version four, the framework will be **nova-framework/system** !!!

**Comment by daveismyname** [comment]
I know that! but I know you, you won't be able to leave app alone so the end result is 2 repos will need to be updated constantly instead of 1.

**Comment by daveismyname** [comment]
Why do you want demos on the app release?

**Comment by LuckyCyborg** [comment]
> Why do you want demos on the app release?

Helps me on development. AND I literally use those Modules and Templates. :smirk: 

Oh, I will update myself those apps, thank you. 

The bare one need minimal maintenance. Even that full fledged will not change much.

Facts are that you can ship dozens of apps, after all.

**Comment by LuckyCyborg** [comment]
> you won't be able to leave app alone so the end result is 2 repos will need to be updated constantly instead of 1.

Moving the demos on another repository will result in maintaining two repositories also. 

And for me, demos are even the Templates.

**Comment by daveismyname** [comment]
When I use composer to install Nova I don't want to have to spent time removing modules and demo code that I may not be using so you want to use something for your company so the answer is to make it more inconvenient for everyone else.

Is there an option when using composer create-project to specify the app repo so either one can be selected I think that would solve this.

> Moving the demos on another repository will result in maintaining two repositories also.

Not if the app is left alone once it's setup it should not need to changed frequently otherwise what's the point in separating them if app is going to be edited all the time, that will result in the same upgrade issue we have now.

**Comment by LuckyCyborg** [comment]
@daveismyname Just trust me in that. Is not first time when I doing that Design.

You have only to prepare that **nova-framework/bare-app** too, I you will see that there is nothing to maintain if I not touch the Boot Stage.

**Comment by geomorillo** [comment]
So if we return to the upgrade issue after doing your Design can we remove those demos?

**Comment by LuckyCyborg** [comment]
You will have just to use **nova-framework/bare-app** instead of **nova-framework/app**, which ship no demos and no templates. 

Nothing will be in the way for you.

**Comment by daveismyname** [comment]
> You will have just to use nova-framework/bare-app instead of nova-framework/app, which ship no demos and no templates.

How will that install from composer command?

**Comment by LuckyCyborg** [comment]
```
composer create-project nova-framework/bare-app foldername -s dev
```
instead of
```
composer create-project nova-framework/app foldername -s dev
```

**Comment by daveismyname** [comment]
Ok that's easy thank you.

**Comment by LuckyCyborg** [comment]
See? Then give me also the *bare-app** repository to play with.

**Comment by daveismyname** [comment]
already doing so :)

**Comment by LuckyCyborg** [comment]
:+1:

**Comment by daveismyname** [comment]
https://packagist.org/packages/nova-framework/bare-app

**Comment by LuckyCyborg** [comment]
Thanks!

**Comment by LuckyCyborg** [comment]
@daveismyname 
```
Username for 'https://github.com': LuckyCyborg
Password for 'https://LuckyCyborg@github.com': 
remote: Permission to nova-framework/bare-app.git denied to LuckyCyborg.
fatal: unable to access 'https://github.com/nova-framework/bare-app.git/': The requested URL returned error: 403
```

**Comment by daveismyname** [comment]
I've just added you to there now.

**Comment by LuckyCyborg** [comment]
Thanks!

**Comment by LuckyCyborg** [comment]
@daveismyname You can test the preliminary App with vendor based system. This one:

https://github.com/nova-framework/app

**Comment by daveismyname** [comment]
OK that installs perfectly threw me at first with the dev address being different but works good.

The language switcher isn't changing language though.

**Comment by LuckyCyborg** [comment]
> The language switcher isn't changing language though.

It change, but someone should update the Language files. Only the new style APIs available there, you remember?

**Comment by daveismyname** [comment]
ah ok I'm not familiar with the new style language, is that the message.php files?

**Comment by daveismyname** [comment]
Personally I won't be using them but I'm sure others will be.

**Comment by LuckyCyborg** [comment]
> ah ok I'm not familiar with the new style language, is that the message.php files? 

Yes. This one. The Key is the original string, the Value is the translated string.

**Comment by LuckyCyborg** [comment]
Now going to job. **I'll be back!**

**Comment by daveismyname** [comment]
Ok thanks 👍

**Comment by Kingorgg** [comment]
@LuckyCyborg 
> It change, but someone should update the Language files. Only the new style APIs available there, you remember?

I'll update them.

**Comment by LuckyCyborg** [comment]
@Kingorgg Thanks, Daniel!

**Comment by LuckyCyborg** [comment]
@daveismyname and @Kingorgg I will leave to your decision how will be implemented the **Default Template** on https://github.com/nova-framework/bare-app/tree/master/app

My suggestion is to use CDN or direct Assets shipping.

**Comment by jimgwhit** [comment]
@daveismyname the demos are important for new users also who may not know how to use the features yet. Having a blank framework without at least a demo leaves people in the dark.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> he demos are important for new users also who may not know how to use the features yet. Having a blank framework without at least a demo leaves people in the dark.

That's WHY we will ship two APPs: one with all shiny demos, and one stripped bare, for Gurus.

**Comment by jimgwhit** [comment]
@LuckyCyborg  if I want to use the database helper in version 4 could you please tell me how to implement it? Surely version 4 will be flexible enough to use custom helpers etc.

**Comment by LuckyCyborg** [comment]
@jimgwhit Just adapt it for **App\Helpers**.

**Comment by jimgwhit** [comment]
@LuckyCyborg said  
> Eventually, create a Helpers which add the Wheres on top of Database API  

Could you give a short example of what this would look like because now all is integrated.  Not the where thing but how to go about the integration. Including a helper won't be possible because that will be inventor I'm guessing so the integration I'm not sure where and how.

**Comment by LuckyCyborg** [comment]
@jimgwhit Come on! Now I should write custom Helpers for you?

**Comment by southcoastweb** [comment]
When can we start testing with it ?

**Comment by LuckyCyborg** [comment]
@southcoastweb 

> When can we start testing with it ?

It is alive. Use:

```
git clone https://github.com/nova-framework/app.git novatesting
```
And go ahead! :smile:

**Comment by daveismyname** [comment]
just installed from composer command using app:

````
composer create-project nova-framework/app -s dev
````

When I run it:

````
Cannot use Nova\Core\Template as Template because the name is already in use
````

**Comment by daveismyname** [comment]
In novalocal/app/vendor/nova-framework/system/src/Support/Facades/Response.php

**Comment by LuckyCyborg** [comment]
OK. Thanks

**Comment by LuckyCyborg** [comment]
Please update the composer

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, to avoid delays on packagist updates, I suggest you to use git cloning for now.

**Comment by daveismyname** [comment]
that worked ;)

**Comment by southcoastweb** [comment]
Cannot use Nova\Core\View as View because the name is already in use.
 /home/nova4/vendor/nova-framework/system/src/Support/Facades/Response.php

**Comment by southcoastweb** [comment]
is that the one you just done? oops

**Comment by LuckyCyborg** [comment]
Do not use composer, use git cloning

**Comment by LuckyCyborg** [comment]
![snapshot22](https://cloud.githubusercontent.com/assets/13488485/16208715/ca8641fc-3733-11e6-8b9f-f3160c842e40.png)

![snapshot23](https://cloud.githubusercontent.com/assets/13488485/16208765/ffe17baa-3733-11e6-9dd1-f760b962e05c.png)

**Comment by southcoastweb** [comment]
nice 👍 
Im just uploading the bare-app right now to my test server.

**Comment by LuckyCyborg** [comment]
Bare App is not ready!

**Comment by southcoastweb** [comment]
Call to a member function withContent() on null
lol i just found that out

**Comment by LuckyCyborg** [comment]
You believe that I will give yours the Nova 4 on one freaking day? :smile:

**Comment by southcoastweb** [comment]
the days not over..
😃

**Comment by LuckyCyborg** [comment]
But the full **App** is working. Good to test it.

**Comment by southcoastweb** [comment]
i knew you could type quick
if i remove the line withContent() from routes it loads fine to a blank screen
Ill remove it and do the full version then

**Comment by LuckyCyborg** [comment]
@southcoastweb At Bare App i wait @daveismyname and @Kingorgg to do something with the **Default Template** which should not rely on Vendor, or we will add 12MB to fat.

**Comment by LuckyCyborg** [comment]
This is **Bare App**

![snapshot24](https://cloud.githubusercontent.com/assets/13488485/16209328/d17622b8-3736-11e6-876e-f9b2289b911a.png)

**Comment by amiroperator** [comment]
I think we don't any controller or welcome page or template for Bare App.
People must write own code there

**Comment by LuckyCyborg** [comment]
@amiroperator There is no controller beyond the language changer. The page is generated by Routing, directly.

Yet, for now we need a template, to show the Errors Pages. Which are themed.

**Comment by daveismyname** [comment]
I'll use a CDN for bootstrap using a single layout file keep is stripped down with a welcome controller. it should come with something to see even it it's tiny.

**Comment by LuckyCyborg** [comment]
@daveismyname No Welcome Controller, just a Route:

```php
Router::any('', function() {
    $view = View::make('Default')
        ->shares('title', __('Welcome'))
        ->withContent(__('Yup! It works.'));

    $template = Template::make('default')->withContent($view);

    return Response::make($template);
});
```

**Comment by daveismyname** [comment]
ah that will work.

**Comment by amiroperator** [comment]
You don't need all file in default except default.php. Why you are keeping them ?

**Comment by daveismyname** [comment]
I said just a single layout file did I not?

**Comment by LuckyCyborg** [comment]
@daveismyname I updated the Bare App to (momentary) use the Vendor shipped Bootstrap 3, to see it working.

The Template is in yours hand.

**Comment by daveismyname** [comment]
OK I'll update it, thanks.

**Comment by LuckyCyborg** [comment]
@daveismyname :+1:

**Comment by amiroperator** [comment]
Is that custom necessary you didn't remove?

**Comment by daveismyname** [comment]
I haven't uploaded my changed yet, none of them have been removed on the repo yet.

**Comment by LuckyCyborg** [comment]
I removed footer/header from both apps

**Comment by daveismyname** [comment]
I'm working on the bare-app repo theme on my local will upload it in a few moments.

**Comment by LuckyCyborg** [comment]
OK! I'm curious about your take! :smile:

**Comment by LuckyCyborg** [comment]
And yeah, there is no need for Custom Layout and its RTL counterpart...

**Comment by daveismyname** [comment]
agreed.

**Comment by daveismyname** [comment]
Is the language change needed on the bare? as standard?

**Comment by daveismyname** [comment]
I ask for others, myself I don't need it.

**Comment by amiroperator** [comment]
I don't need it too

**Comment by Kingorgg** [comment]
No, I don't think it should be needed on the bare-app. If the user wants it, they should be able to add it themselves.

**Comment by daveismyname** [comment]
maybe we should leave that for the full app install?

**Comment by amiroperator** [comment]
Let people write their code

**Comment by daveismyname** [comment]
OK.

**Comment by LuckyCyborg** [comment]
I have intention to write RESTful APIs with the Bare App, then I guess not.

**Comment by Kingorgg** [comment]
What about removing the models from bare-app as well?

**Comment by amiroperator** [comment]
> What about removing the models from bare-app as well?
agreed

**Comment by LuckyCyborg** [comment]
Are used by Auth API, the User one. The Role is on Relation with the first.

**Comment by Kingorgg** [comment]
Okay, no problem :+1:

**Comment by daveismyname** [comment]
There is a Welcome view inside Emails is that still needed I assume it's not?

**Comment by daveismyname** [comment]
I'll leave the Auth email views for anyone who wants to use the Auth as is.

**Comment by LuckyCyborg** [comment]
Yeah, that was a test.

**Comment by LuckyCyborg** [comment]
But **app/Views/Emails/Auth** are part of Auth API.

**Comment by daveismyname** [comment]
Yes I've left them.

**Comment by daveismyname** [comment]
by the way does anything call app/Views/Default.php?

**Comment by LuckyCyborg** [comment]
You deleted the Language from Template? WHY?

**Comment by daveismyname** [comment]
I thought that was not being included?

**Comment by LuckyCyborg** [comment]
Are expected by Language API, and they are **not** optional.

You ship a Template (or Module), they should have that Langauge folder. even if the messages are empty.

**Comment by daveismyname** [comment]
ah OK I'll add it back.

**Comment by LuckyCyborg** [comment]
OK. Thanks.

**Comment by daveismyname** [comment]
OK I think that does it, I did re-add the language changer since the languages are there.

**Comment by LuckyCyborg** [comment]
@daveismyname Please use **scripts/makelangs.php** to update the Language files.

**Comment by daveismyname** [comment]
I ran that saw output in composer but nothing new to commit. No changes detected.

**Comment by LuckyCyborg** [comment]
OK

**Comment by LuckyCyborg** [comment]
@daveismyname See that I updated the Language files for the Default Template

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg Why not  do away with the bare repo and have the one with the stuff and the demos and just have a script that will delete all unnecessary things if someone chooses to run the script wouldn't this be much simpler. Maybe just whip out a CLI script. This two repo thing mas get out of hand quickly.

**Comment by daveismyname** [comment]
because I want a bare bones one, that requires me to do nothing to be ready to go with it. You don't want it, fine ignore it.

**Comment by daveismyname** [comment]
> This two repo thing may get out of hand quickly.

The bare bones should not need to be touched (or very little) so I don't see how.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> The bare bones should not need to be touched (or very little) so I don't see how.

Yep. There I agree. The bare bones application need to be adjusted maybe/only when there are changes on Boot Stage or are introduced/removed configuration options.

**Comment by LuckyCyborg** [comment]
@daveismyname Oh, a idea: 

How we go breaking API, I see no sense to ship two identical facades to Router. 

My proposal is to ship only **Route**, just like Laravel, and to remove the Facade called **Router**.

**Comment by daveismyname** [comment]
OK so the only change would be when setting a route that **Route::** would be used instead of **Router::** right?

Yes I can agree with that, I'll make a note to update the v4 docs when I start them.

**Comment by LuckyCyborg** [comment]
@daveismyname Yes, this is the only change. And adjusting your generator. Which I made it.

**Comment by daveismyname** [comment]
Jim move on, you asked it's been answered. Lets not have 30+ posts on something that does not need discussing it's done.

**Comment by jimgwhit** [comment]
@daveismyname did you read the whole thing?

**Comment by LuckyCyborg** [comment]
@daveismyname Then, the Nova's Artis... err, **Forge** is functional. :smirk: 

I nuked the old CLI and in next days I will complete the commands given by previous CLI and maybe beyond. 

To note that was need to update the Boot Stage and Configuration on both apps.

**Comment by jimgwhit** [comment]
@LuckyCyborg  said
> BTW, no more dumping whatever variables in the Layouts or Views  

That makes about as much sense is two male dogs doing the nasty. What about passing variables such as pagination links and other stuff you may want to pass like a special array.  
You wanted this laravel like, but it's pulling away from that more and more it seems like I totally do not understand what you mean by The Dumping a variable.  
What do you think A render is for, is to pass things to the view for display.

**Comment by LuckyCyborg** [comment]
@jimgwhit As in if you put **$js** on a Layout, is fine, BUT make sure yourself that that variable exists, or Exception Handling Service will yell.

**Comment by jimgwhit** [comment]
@LuckyCyborg I have two examples, one:
```
function view() {
        require_once 'Mobile_Detect.php';
        $detect = new Mobile_Detect;
        if ($detect->isMobile()) {
            $data['mflag'] = TRUE;
        } else {
            $data['mflag'] = FALSE;
        }
        $dogid = Input::get('dogid');
        $data['row'] = $this->Dog->getDog($dogid);
        $this->layout = 'viewtpl';
        return View::make('Dog/View')
                        ->shares('title', 'Dog View')
                        ->with('data2', $data['row'])
                        ->with('data3', $data['mflag']);
    }
```
You see with('data3', $data['mflag']), something like this is still passed the normal way, correct?  
And two, 
I load css and js like this
```
<link href="<?php echo Helpers\Url::templatePath(); ?>css/styleadmin.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo Helpers\Url::templatePath(); ?>js/jquery.js"></script>  
```
Now this would still work in the layout file, correct?  Not sure what $js you are talking about.  But I don't pass js in a variable anyway.

**Comment by LuckyCyborg** [comment]
@jimgwhit You know what is is a undefined variable?

As in doing:
```php
echo $js;
```
while nowhere was set that variable. That's after all a bad thing, and go WARNING. And Exception Handling Service is more strict than the previous Error Handler.

Or you write perfect code, or it will yell. That's all.

**Comment by jimgwhit** [comment]
@LuckyCyborg so my above is still fine for nova 4?

**Comment by LuckyCyborg** [comment]
@jimgwhit Sure thing. Is about undefined variables, not about defining your variables.

**Comment by jimgwhit** [comment]
Glad you missed my new issue #988.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> You seem nice today, are you alright?

That's probably because I missed to read #988 , thank you! I should read it?

**Comment by vahidalvandi** [comment]
The pace of change you too much....
And do not provide a complete documentation for version 3

**Comment by LuckyCyborg** [comment]
> The pace of change you too much....

As in?

The Nova 3 was updated 3 days ago, last time.

> And do not provide a complete documentation for version 3

With the documentation task are another guys. :smile:

**Comment by LuckyCyborg** [comment]
Then, Gentlemen, the **Nova 4** arrived to the objectives which I proposed for.

I invite you to a careful testing and be kind to report back the eventual issues found.

**Comment by daveismyname** [comment]
closed, any bug issues should be posted as individual issues to be investigated.
