### ISSUE TITLE
error in select database helpers

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#989]
if i can select statement like bellow return error 

**Message: SQLSTATE[HY000]: General error

Code: HY000

File: D:\xampp\htdocs\shop\development\app\Helpers\Database.php

Line: 109**

`CREATE TEMPORARY TABLE top10customers
SELECT p.customerNumber, 
       c.customerName, 
       FORMAT(SUM(p.amount),2) total
FROM payments p
INNER JOIN customers c ON c.customerNumber = p.customerNumber
GROUP BY p.customerNumber
ORDER BY total DESC
LIMIT 10`

in database work fine but return a error in line 109 database helpers
` return $stmt->fetchAll($fetchMode);`

**my current version 2.2**

**Comment by LuckyCyborg** [comment]
It is still supported **SMVC 2.2** ?

**Comment by daveismyname** [comment]
Use the method rawsql for quarries like this.

**Comment by vahidalvandi** [comment]
i create new function

```
  public function execsql($sql)
    {
        return $this->exec($sql);
    }
```

wirk fine but result with select methodare not the same

**Comment by vahidalvandi** [comment]
$this->db->raw()
are not the same result with select

**Comment by vahidalvandi** [comment]
i solved this.
