### ISSUE TITLE
why need php 5.5 ?

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#990]
i have encode software ans support php 5.4 ,  if i use php 5.4 not work correctly?

**Comment by geomorillo** [comment]
Nova Framework is a PHP 5.5+ MVC Framework some functions on 5.4 are outdated or missing so it won't work on 5.4, there is not gonna be support for 5.4.

**Comment by daveismyname** [comment]
It's not actively blocked it may work but it's very old upgrade to 5.6 if you can.

**Comment by vahidalvandi** [comment]
In your opinion php 5.6 How long will it remain stable ?

**Comment by daveismyname** [comment]
2 years, 6 months.

http://php.net/supported-versions.php

**Comment by tomvlk** [comment]
Just a note: 5.5 will be 'end of life' next month.

**Comment by daveismyname** [comment]
yeah 16 days.
