### ISSUE TITLE
have error in localhost

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#992]
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Class 'MessageFormatter' not found"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in D:\xampp2\htdocs\nova\system\Core\Language.php:172
#0 Exception\Handler:handleShutdown in [internal]:0

-----
i config corectlly

**Comment by l2wok** [comment]
you php not have 'intl'
install or uncomment in php.ini
(i have this error on debain webserver, apt-get install php5-intl and all ok)

**Comment by vahidalvandi** [comment]
ok
