### ISSUE TITLE
install nusoap with composer 

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/framework#995]
i need install nusoal class bellow to smvc 2.2

https://github.com/noiselabs/NoiselabsNuSOAPBundle

help me

thanks

**Comment by daveismyname** [comment]
in your command line go to the project enter:

````
composer require noiselabs/nusoap-bundle
````

that will download the repo and add it to composer, upload vendor to the server.

then follow the package instructions.

**Comment by vahidalvandi** [comment]
ok work fine.
