### ISSUE TITLE
seo in url

### ISSUE THREAD

**Issue by eagle-design** [nova-framework/framework#998]
site.com/123/first-lang/second-text
How to use  "/first-lang/second-text" in url ( for seo ) ?

* i dont want to get these texts in php 

how to say they are not routing ... ?

**Comment by LuckyCyborg** [comment]
About what Nova version you talk?

**Comment by eagle-design** [comment]
i dont know real version but 3
the ways are the same

**Comment by LuckyCyborg** [comment]
```php
Router::any('123(/(:any)(/(:all)))', 'App\Controllers\OneTwoThree@request');
```
